import type { Product } from "@/types";

const IMG = {
  // Granos
  arroz: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800",
  arrozCocido: "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=800",
  arrozIntegral: "https://images.unsplash.com/photo-1626078299034-94e7e7c9d4d4?w=800",
  frijolesNegros: "https://images.unsplash.com/photo-1610725664285-7c57e6eeac3f?w=800",
  frijolesColorados: "https://images.unsplash.com/photo-1546554137-f86b9593a222?w=800",
  frijolesBlancos: "https://images.unsplash.com/photo-1604152135912-04a022e23696?w=800",
  lentejas: "https://images.unsplash.com/photo-1612257999782-58ba0b8c8c99?w=800",
  garbanzos: "https://images.unsplash.com/photo-1611575619232-1b06ebbb3e94?w=800",
  chicharo: "https://images.unsplash.com/photo-1615485925600-97237c4fc1ec?w=800",
  espagueti: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800",
  macarron: "https://images.unsplash.com/photo-1599909366516-6c1ac8e21bf6?w=800",
  harinaTrigo: "https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?w=800",
  harinaMaiz: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800",
  // Carnes
  polloEntero: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=800",
  pechuga: "https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=800",
  alas: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800",
  muslos: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800",
  picadillo: "https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=800",
  carneMolida: "https://images.unsplash.com/photo-1602470521006-2c134e5d2ce8?w=800",
  masaCerdo: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=800",
  costillas: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800",
  lomoCerdo: "https://images.unsplash.com/photo-1611171711912-5e3a48e2e7dd?w=800",
  jamonLonchas: "https://images.unsplash.com/photo-1599909533343-9b8f8a64bf25?w=800",
  chorizo: "https://images.unsplash.com/photo-1601001815853-3835274ce8d5?w=800",
  salchichas: "https://images.unsplash.com/photo-1598516801832-a3b6a55c12fc?w=800",
  camarones: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800",
  pescado: "https://images.unsplash.com/photo-1611171711791-b34b41b1bb14?w=800",
  mariscos: "https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=800",
  // Aceites/condimentos
  aceiteSoya: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800",
  aceiteOliva: "https://images.unsplash.com/photo-1519218054301-87baf9a3b1d1?w=800",
  aceiteGirasol: "https://images.unsplash.com/photo-1612874742237-6526221588e1?w=800",
  sal: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800",
  azucar: "https://images.unsplash.com/photo-1610137504432-b8aaa70d99dc?w=800",
  azucarMorena: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=800",
  vinagre: "https://images.unsplash.com/photo-1591735030413-46b5e3d6f8b4?w=800",
  salsaTomate: "https://images.unsplash.com/photo-1592251616195-8d92cd8e1a48?w=800",
  mostaza: "https://images.unsplash.com/photo-1614548000010-aa1ed0a9e0bd?w=800",
  mayonesa: "https://images.unsplash.com/photo-1568625365131-079e026a927d?w=800",
  especias: "https://images.unsplash.com/photo-1596040033229-a0b3b46a0fd4?w=800",
  cafeLlave: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
  cafeBustelo: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800",
  te: "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?w=800",
  // Lácteos
  leche: "https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=800",
  lecheCondensada: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800",
  lecheEvaporada: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800",
  queso: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=800",
  quesoBlanco: "https://images.unsplash.com/photo-1542901031-ec5eeb518d50?w=800",
  mantequilla: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=800",
  margarina: "https://images.unsplash.com/photo-1612257999782-58ba0b8c8c99?w=800",
  mantequillaMani: "https://images.unsplash.com/photo-1604495772376-2c8c4ed47b95?w=800",
  dulceLeche: "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=800",
  cremaLeche: "https://images.unsplash.com/photo-1559054663-e8d23213f55c?w=800",
  // Conservas
  atun: "https://images.unsplash.com/photo-1607612822681-2caa9d3da90e?w=800",
  sardinas: "https://images.unsplash.com/photo-1606471191009-63994c53433b?w=800",
  jamoneta: "https://images.unsplash.com/photo-1599909533343-9b8f8a64bf25?w=800",
  spam: "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=800",
  vegetalesLata: "https://images.unsplash.com/photo-1597626133663-53bda3bdfe3a?w=800",
  arvejas: "https://images.unsplash.com/photo-1596591868231-05e808fd687b?w=800",
  maizDulce: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=800",
  duraznos: "https://images.unsplash.com/photo-1568097277739-5b40c8ce7e6e?w=800",
  pina: "https://images.unsplash.com/photo-1550828520-4cb496926fc9?w=800",
  mermelada: "https://images.unsplash.com/photo-1597571063304-90efaaaba3a7?w=800",
  pulpa: "https://images.unsplash.com/photo-1546548970-71785318a17b?w=800",
  // Aseo
  jabonDove: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800",
  jabonPalmolive: "https://images.unsplash.com/photo-1610115520833-d8d35cefef07?w=800",
  pastaColgate: "https://images.unsplash.com/photo-1607619056574-7b8baa9f900e?w=800",
  pastaCrest: "https://images.unsplash.com/photo-1607619056574-7b8baa9f900e?w=800",
  champu: "https://images.unsplash.com/photo-1556228852-80b6e5eeff06?w=800",
  champuPantene: "https://images.unsplash.com/photo-1556228724-3ed6ea4dec90?w=800",
  acondicionador: "https://images.unsplash.com/photo-1556228724-3ed6ea4dec90?w=800",
  desodorante: "https://images.unsplash.com/photo-1585232351009-aa87416fca90?w=800",
  toallas: "https://images.unsplash.com/photo-1606902965551-dce093cda6e7?w=800",
  panales: "https://images.unsplash.com/photo-1607000853019-fa39f1a90eb1?w=800",
  papelHigienico: "https://images.unsplash.com/photo-1584473457493-17c4c24290c9?w=800",
  cuchillasGillette: "https://images.unsplash.com/photo-1581651587921-a1d8af0a8ed5?w=800",
  // Limpieza
  detergente: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=800",
  cloro: "https://images.unsplash.com/photo-1581539250439-c96689b516dd?w=800",
  jabonFregar: "https://images.unsplash.com/photo-1583947581924-860bda3eba2b?w=800",
  esponjas: "https://images.unsplash.com/photo-1604335398480-1a0acea1f0c0?w=800",
  escoba: "https://images.unsplash.com/photo-1580237072617-771c3ecc4a24?w=800",
  trapeador: "https://images.unsplash.com/photo-1596263576925-d12d3a4e87b1?w=800",
  ambientador: "https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=800",
  papelCocina: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800",
  bolsasBasura: "https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=800",
} as const;

const img = (url: string, alt: string) => ({ url, alt, width: 800, height: 800 });

export const alimentos: Product[] = [
  // ===========================================================
  // GRANOS Y PASTAS (12)
  // ===========================================================
  {
    id: "p_alim_001",
    slug: "arroz-grano-largo",
    name: "Arroz de Grano Largo",
    description: "Arroz blanco de grano largo, calidad premium, perfecto para el día a día.",
    longDescription:
      "Arroz blanco de grano largo seleccionado, el grano que prefieren los cubanos. Cocción uniforme, granos sueltos y suaves. Empacado en bolsas de polietileno alimentario que mantienen la frescura. Producto fundamental de la dieta diaria, dura meses en buen estado.",
    category: "alimentos",
    subcategory: "granos",
    brand: "Mahatma",
    countryOfOrigin: "Estados Unidos",
    price: 8.99,
    currency: "USD",
    thumbnail: IMG.arroz,
    images: [img(IMG.arroz, "Bolsa de arroz Mahatma"), img(IMG.arrozCocido, "Arroz cocinado")],
    variants: [
      { id: "v_arroz_5", name: "5 lb", type: "weight", priceModifier: 0, inStock: true },
      { id: "v_arroz_10", name: "10 lb", type: "weight", priceModifier: 7, inStock: true },
      { id: "v_arroz_20", name: "20 lb", type: "weight", priceModifier: 14, inStock: true },
    ],
    specs: [
      { label: "Tipo", value: "Grano largo" },
      { label: "Marca", value: "Mahatma" },
      { label: "Origen", value: "USA" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.27,
    tags: ["básico", "grano", "familiar", "imprescindible"],
    rating: 4.8,
    reviewCount: 124,
    bestseller: true,
    featured: true,
  },
  {
    id: "p_alim_020",
    slug: "arroz-integral",
    name: "Arroz Integral",
    description: "Arroz integral nutritivo, conserva la fibra y los minerales del grano.",
    longDescription:
      "Arroz integral premium con la cáscara que conserva la fibra, vitaminas y minerales. Más nutritivo que el blanco, ideal para dietas saludables y para personas con diabetes. Bolsa de 5 lb que rinde para semanas de comida.",
    category: "alimentos",
    subcategory: "granos",
    brand: "Mahatma",
    countryOfOrigin: "Estados Unidos",
    price: 9.99,
    currency: "USD",
    thumbnail: IMG.arrozIntegral,
    images: [img(IMG.arrozIntegral, "Arroz integral en bolsa")],
    specs: [
      { label: "Tipo", value: "Integral grano largo" },
      { label: "Peso", value: "5 lb (2.27 kg)" },
      { label: "Beneficio", value: "Alto en fibra" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.27,
    tags: ["grano", "saludable", "fibra", "diabético"],
    rating: 4.6,
    reviewCount: 42,
  },
  {
    id: "p_alim_021",
    slug: "frijoles-negros",
    name: "Frijoles Negros",
    description: "Frijoles negros cubanos, base de la mesa criolla.",
    longDescription:
      "Frijoles negros seleccionados de calidad superior, granos uniformes que cocinan parejo. La base imprescindible del arroz con frijoles, la sopa de frijoles y la moros y cristianos. Bolsa de 5 lb que da para varias comidas familiares.",
    category: "alimentos",
    subcategory: "granos",
    brand: "Goya",
    countryOfOrigin: "Estados Unidos",
    price: 7.5,
    currency: "USD",
    thumbnail: IMG.frijolesNegros,
    images: [img(IMG.frijolesNegros, "Frijoles negros Goya")],
    specs: [
      { label: "Tipo", value: "Negros" },
      { label: "Peso", value: "5 lb" },
      { label: "Marca", value: "Goya" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.27,
    tags: ["frijol", "grano", "básico", "criollo"],
    rating: 4.9,
    reviewCount: 156,
    bestseller: true,
  },
  {
    id: "p_alim_022",
    slug: "frijoles-colorados",
    name: "Frijoles Colorados",
    description: "Frijoles colorados grandes, cremosos, para potajes.",
    longDescription:
      "Frijoles colorados grandes, ideales para los potajes con chorizo, calabaza y viandas que tanto gustan en Cuba. Granos seleccionados que mantienen su forma al cocinar.",
    category: "alimentos",
    subcategory: "granos",
    brand: "Goya",
    countryOfOrigin: "Estados Unidos",
    price: 7.5,
    currency: "USD",
    thumbnail: IMG.frijolesColorados,
    images: [img(IMG.frijolesColorados, "Frijoles colorados")],
    specs: [
      { label: "Tipo", value: "Colorados" },
      { label: "Peso", value: "5 lb" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.27,
    tags: ["frijol", "potaje", "criollo"],
    rating: 4.8,
    reviewCount: 87,
  },
  {
    id: "p_alim_023",
    slug: "frijoles-blancos",
    name: "Frijoles Blancos",
    description: "Frijoles blancos grandes, suaves y cremosos.",
    longDescription:
      "Frijoles blancos navy de excelente calidad. Perfectos para sopas, potajes y guisos. Cocinan rápido y quedan cremosos. Bolsa de 5 lb que rinde para varias comidas.",
    category: "alimentos",
    subcategory: "granos",
    brand: "Goya",
    countryOfOrigin: "Estados Unidos",
    price: 7.99,
    currency: "USD",
    thumbnail: IMG.frijolesBlancos,
    images: [img(IMG.frijolesBlancos, "Frijoles blancos")],
    specs: [
      { label: "Tipo", value: "Blancos navy" },
      { label: "Peso", value: "5 lb" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.27,
    tags: ["frijol", "blanco", "sopa"],
    rating: 4.7,
    reviewCount: 54,
  },
  {
    id: "p_alim_024",
    slug: "lentejas",
    name: "Lentejas",
    description: "Lentejas finas con alto contenido proteico.",
    longDescription:
      "Lentejas seleccionadas, fuente excelente de proteína vegetal y hierro. Cocinan rápido sin necesidad de remojo. Bolsa de 5 lb. Ideales para sopas y guisos.",
    category: "alimentos",
    subcategory: "granos",
    brand: "Goya",
    countryOfOrigin: "Canadá",
    price: 8.5,
    currency: "USD",
    thumbnail: IMG.lentejas,
    images: [img(IMG.lentejas, "Lentejas en bolsa")],
    specs: [
      { label: "Peso", value: "5 lb" },
      { label: "Beneficio", value: "Rica en proteínas y hierro" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.27,
    tags: ["grano", "proteína", "saludable"],
    rating: 4.7,
    reviewCount: 38,
  },
  {
    id: "p_alim_025",
    slug: "garbanzos",
    name: "Garbanzos",
    description: "Garbanzos grandes seleccionados, base de potajes y ensaladas.",
    longDescription:
      "Garbanzos calibre grande, granos uniformes que cocinan parejo. Perfectos para el potaje de garbanzos, hummus, ensaladas y guisos. Alto en proteína y fibra.",
    category: "alimentos",
    subcategory: "granos",
    brand: "Goya",
    countryOfOrigin: "México",
    price: 8.99,
    currency: "USD",
    thumbnail: IMG.garbanzos,
    images: [img(IMG.garbanzos, "Garbanzos secos")],
    specs: [
      { label: "Peso", value: "5 lb" },
      { label: "Calibre", value: "Grande" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.27,
    tags: ["grano", "garbanzo", "potaje"],
    rating: 4.6,
    reviewCount: 31,
  },
  {
    id: "p_alim_026",
    slug: "chicharo",
    name: "Chícharo",
    description: "Chícharo seco para sopa cubana tradicional.",
    longDescription:
      "Chícharo amarillo seco, el grano de la sopa cubana de chícharos por excelencia. Cocina cremoso, perfecto con jamón, papas y hueso de cerdo.",
    category: "alimentos",
    subcategory: "granos",
    brand: "Goya",
    countryOfOrigin: "Canadá",
    price: 7.5,
    currency: "USD",
    thumbnail: IMG.chicharo,
    images: [img(IMG.chicharo, "Chícharo amarillo")],
    specs: [
      { label: "Peso", value: "5 lb" },
      { label: "Tipo", value: "Amarillo partido" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.27,
    tags: ["grano", "chícharo", "sopa", "criollo"],
    rating: 4.8,
    reviewCount: 67,
  },
  {
    id: "p_alim_027",
    slug: "espagueti-paquete",
    name: "Espagueti Barilla (4 paquetes)",
    description: "4 paquetes de espagueti italiano Barilla.",
    longDescription:
      "Pack de 4 paquetes de espagueti Barilla, la marca italiana líder. Pasta de sémola de trigo durum que cocina al dente y mantiene la textura. Cada paquete trae 1 lb (453 g).",
    category: "alimentos",
    subcategory: "granos",
    brand: "Barilla",
    countryOfOrigin: "Italia",
    price: 5.99,
    currency: "USD",
    thumbnail: IMG.espagueti,
    images: [img(IMG.espagueti, "Espagueti Barilla")],
    specs: [
      { label: "Cantidad", value: "4 paquetes de 1 lb" },
      { label: "Tipo", value: "Sémola trigo durum" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.81,
    tags: ["pasta", "espagueti", "italiana"],
    rating: 4.8,
    reviewCount: 92,
    bestseller: true,
  },
  {
    id: "p_alim_028",
    slug: "macarron-coditos",
    name: "Macarrón Coditos",
    description: "Macarrón en forma de coditos, ideal para ensalada fría.",
    longDescription:
      "Macarrón en forma de coditos, perfecto para la clásica ensalada fría con mayonesa, jamón, queso y maíz. También funciona muy bien con cualquier salsa. Pack económico.",
    category: "alimentos",
    subcategory: "granos",
    brand: "Barilla",
    countryOfOrigin: "Italia",
    price: 4.99,
    currency: "USD",
    thumbnail: IMG.macarron,
    images: [img(IMG.macarron, "Macarrón coditos")],
    specs: [
      { label: "Cantidad", value: "3 paquetes de 1 lb" },
      { label: "Forma", value: "Coditos" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.36,
    tags: ["pasta", "macarrón", "ensalada"],
    rating: 4.6,
    reviewCount: 48,
  },
  {
    id: "p_alim_029",
    slug: "harina-trigo",
    name: "Harina de Trigo",
    description: "Harina de trigo todo uso, marca premium.",
    longDescription:
      "Harina de trigo refinada todo uso, ideal para panes, pizzas, tortas y empanadas. Bolsa de 5 lb sellada que mantiene la frescura por meses.",
    category: "alimentos",
    subcategory: "granos",
    brand: "Gold Medal",
    countryOfOrigin: "Estados Unidos",
    price: 6.99,
    currency: "USD",
    thumbnail: IMG.harinaTrigo,
    images: [img(IMG.harinaTrigo, "Harina de trigo")],
    specs: [
      { label: "Tipo", value: "Todo uso" },
      { label: "Peso", value: "5 lb" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.27,
    tags: ["harina", "panadería", "básico"],
    rating: 4.7,
    reviewCount: 36,
  },
  {
    id: "p_alim_030",
    slug: "harina-maiz",
    name: "Harina de Maíz",
    description: "Harina de maíz amarilla para tamales y arepas.",
    longDescription:
      "Harina de maíz amarilla precocida, base para tamales, harina con leche, arepas y empanadas. Marca confiable que muchas familias cubanas conocen.",
    category: "alimentos",
    subcategory: "granos",
    brand: "Goya",
    countryOfOrigin: "México",
    price: 6.5,
    currency: "USD",
    thumbnail: IMG.harinaMaiz,
    images: [img(IMG.harinaMaiz, "Harina de maíz")],
    specs: [
      { label: "Tipo", value: "Amarilla precocida" },
      { label: "Peso", value: "5 lb" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.27,
    tags: ["harina", "maíz", "tamal", "criollo"],
    rating: 4.7,
    reviewCount: 28,
  },

  // ===========================================================
  // CARNES Y POLLO (15)
  // ===========================================================
  {
    id: "p_alim_002",
    slug: "pollo-entero-congelado",
    name: "Pollo Entero Congelado",
    description: "Pollo entero fresco congelado, sin menudencias, listo para cocinar.",
    longDescription:
      "Pollo entero seleccionado, criado en granjas certificadas, congelado al momento del despresado para preservar la frescura y los nutrientes. Sin menudencias, limpio y listo para cocinar. Llega a Matanzas en cadena de frío garantizada.",
    category: "alimentos",
    subcategory: "carnes-y-pollo",
    brand: "Tyson",
    countryOfOrigin: "Estados Unidos",
    price: 22.99,
    currency: "USD",
    thumbnail: IMG.polloEntero,
    images: [img(IMG.polloEntero, "Pollo entero congelado")],
    variants: [
      { id: "v_pollo_4", name: "Aprox. 4 lb", type: "weight", priceModifier: 0, inStock: true },
      { id: "v_pollo_6", name: "Aprox. 6 lb", type: "weight", priceModifier: 9, inStock: true },
    ],
    specs: [
      { label: "Tipo", value: "Pollo entero sin menudencias" },
      { label: "Estado", value: "Congelado" },
      { label: "Cadena de frío", value: "Garantizada" },
      { label: "Peso aprox.", value: "4 lb (1.8 kg)" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 1.8,
    tags: ["carne", "pollo", "congelado", "familiar"],
    rating: 4.7,
    reviewCount: 89,
    bestseller: true,
  },
  {
    id: "p_alim_006",
    slug: "pechuga-pollo",
    name: "Pechuga de Pollo",
    description: "Pechuga de pollo deshuesada, congelada en cadena de frío.",
    longDescription:
      "Pechuga de pollo deshuesada y sin piel, cortes magros listos para empanizar, asar o sofreír. Congelada al momento del despresado. Empacada al vacío en porciones manejables.",
    category: "alimentos",
    subcategory: "carnes-y-pollo",
    brand: "Tyson",
    countryOfOrigin: "Estados Unidos",
    price: 18.5,
    currency: "USD",
    thumbnail: IMG.pechuga,
    images: [img(IMG.pechuga, "Pechugas de pollo")],
    specs: [
      { label: "Peso", value: "3 lb" },
      { label: "Tipo", value: "Sin piel ni hueso" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 1.36,
    tags: ["pollo", "pechuga", "congelado"],
    rating: 4.8,
    reviewCount: 76,
    bestseller: true,
  },
  {
    id: "p_alim_007",
    slug: "alas-pollo",
    name: "Alas de Pollo",
    description: "Alas de pollo congeladas, perfectas para empanizar o asar.",
    longDescription:
      "Alas de pollo seleccionadas, ideales para empanizar, asar a la parrilla o cocinar al horno con BBQ. Empaque de 3 lb con cadena de frío garantizada.",
    category: "alimentos",
    subcategory: "carnes-y-pollo",
    brand: "Tyson",
    countryOfOrigin: "Estados Unidos",
    price: 14.99,
    currency: "USD",
    thumbnail: IMG.alas,
    images: [img(IMG.alas, "Alas de pollo")],
    specs: [
      { label: "Peso", value: "3 lb" },
      { label: "Estado", value: "Congelado" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 1.36,
    tags: ["pollo", "alas", "congelado"],
    rating: 4.6,
    reviewCount: 52,
  },
  {
    id: "p_alim_008",
    slug: "muslos-pollo",
    name: "Muslos de Pollo",
    description: "Muslos de pollo jugosos, con piel, congelados.",
    longDescription:
      "Muslos de pollo con piel y hueso, los más sabrosos para asar y para fricasés. Congelados con cadena de frío. Empaque de 3 lb que rinde para varias comidas familiares.",
    category: "alimentos",
    subcategory: "carnes-y-pollo",
    brand: "Perdue",
    countryOfOrigin: "Estados Unidos",
    price: 13.99,
    currency: "USD",
    thumbnail: IMG.muslos,
    images: [img(IMG.muslos, "Muslos de pollo")],
    specs: [
      { label: "Peso", value: "3 lb" },
      { label: "Tipo", value: "Con piel y hueso" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 1.36,
    tags: ["pollo", "muslos", "congelado"],
    rating: 4.7,
    reviewCount: 44,
  },
  {
    id: "p_alim_009",
    slug: "picadillo-res",
    name: "Picadillo de Res",
    description: "Carne molida de res 80/20, ideal para picadillo a la cubana.",
    longDescription:
      "Carne molida de res 80/20 (80% magra, 20% grasa) ideal para el picadillo a la habanera con sofrito, papas, aceitunas y pasas. Congelada en porciones de 1 lb. Cadena de frío garantizada.",
    category: "alimentos",
    subcategory: "carnes-y-pollo",
    countryOfOrigin: "Estados Unidos",
    price: 19.99,
    currency: "USD",
    thumbnail: IMG.picadillo,
    images: [img(IMG.picadillo, "Picadillo de res")],
    specs: [
      { label: "Tipo", value: "Molida 80/20" },
      { label: "Peso", value: "3 lb (3 paquetes)" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 1.36,
    tags: ["res", "picadillo", "congelado", "criollo"],
    rating: 4.9,
    reviewCount: 134,
    bestseller: true,
  },
  {
    id: "p_alim_010",
    slug: "carne-molida-premium",
    name: "Carne Molida Premium 80/20",
    description: "Carne molida de res premium para hamburguesas y guisos.",
    longDescription:
      "Carne molida de res premium 80/20, cortada a partir de cortes selectos. Ideal para hamburguesas caseras, albóndigas, lasaña o cualquier guiso. Empaque de 3 lb.",
    category: "alimentos",
    subcategory: "carnes-y-pollo",
    countryOfOrigin: "Estados Unidos",
    price: 24.99,
    currency: "USD",
    thumbnail: IMG.carneMolida,
    images: [img(IMG.carneMolida, "Carne molida premium")],
    specs: [
      { label: "Tipo", value: "Premium 80/20" },
      { label: "Peso", value: "3 lb" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 1.36,
    tags: ["res", "premium", "molida"],
    rating: 4.7,
    reviewCount: 41,
  },
  {
    id: "p_alim_011",
    slug: "masa-cerdo",
    name: "Masa de Cerdo",
    description: "Masa de cerdo en trozos, para freír al estilo cubano.",
    longDescription:
      "Masa de cerdo en trozos perfectos para la clásica masa de puerco frita con mojo cubano. Carne marmoleada que queda crujiente por fuera y jugosa por dentro. Empaque de 3 lb congelado.",
    category: "alimentos",
    subcategory: "carnes-y-pollo",
    countryOfOrigin: "Estados Unidos",
    price: 26.99,
    currency: "USD",
    thumbnail: IMG.masaCerdo,
    images: [img(IMG.masaCerdo, "Masa de cerdo")],
    specs: [
      { label: "Peso", value: "3 lb" },
      { label: "Corte", value: "En trozos" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 1.36,
    tags: ["cerdo", "masa", "criollo", "frito"],
    rating: 4.9,
    reviewCount: 102,
    bestseller: true,
  },
  {
    id: "p_alim_012",
    slug: "costillas-cerdo",
    name: "Costillas de Cerdo",
    description: "Costillas de cerdo congeladas, para asar o guisar.",
    longDescription:
      "Costillas de cerdo en racks, perfectas para BBQ a la parrilla o guisadas con sofrito criollo. Carne con buen marmoleo. Empaque de 3 lb.",
    category: "alimentos",
    subcategory: "carnes-y-pollo",
    countryOfOrigin: "Estados Unidos",
    price: 22.5,
    currency: "USD",
    thumbnail: IMG.costillas,
    images: [img(IMG.costillas, "Costillas de cerdo")],
    specs: [
      { label: "Peso", value: "3 lb" },
      { label: "Tipo", value: "Costillas en rack" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 1.36,
    tags: ["cerdo", "costillas", "BBQ"],
    rating: 4.7,
    reviewCount: 38,
  },
  {
    id: "p_alim_013",
    slug: "lomo-cerdo",
    name: "Lomo de Cerdo",
    description: "Lomo de cerdo en pieza entera, magro y versátil.",
    longDescription:
      "Lomo de cerdo en pieza entera, corte magro perfecto para asar al horno o filetear. Empaque al vacío congelado. Pieza de 3 lb aproximadamente.",
    category: "alimentos",
    subcategory: "carnes-y-pollo",
    countryOfOrigin: "Estados Unidos",
    price: 25.99,
    currency: "USD",
    thumbnail: IMG.lomoCerdo,
    images: [img(IMG.lomoCerdo, "Lomo de cerdo")],
    specs: [
      { label: "Peso", value: "3 lb" },
      { label: "Corte", value: "Pieza entera" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 1.36,
    tags: ["cerdo", "lomo", "magro"],
    rating: 4.8,
    reviewCount: 32,
  },
  {
    id: "p_alim_014",
    slug: "jamon-lonchas",
    name: "Jamón en Lonchas",
    description: "Jamón cocido en lonchas finas, marca Oscar Mayer.",
    longDescription:
      "Jamón cocido en lonchas finas marca Oscar Mayer, listo para sándwiches y bocaditos. Empaque de 1 lb sellado al vacío. Sabor delicado, bajo en grasa.",
    category: "alimentos",
    subcategory: "carnes-y-pollo",
    brand: "Oscar Mayer",
    countryOfOrigin: "Estados Unidos",
    price: 11.99,
    currency: "USD",
    thumbnail: IMG.jamonLonchas,
    images: [img(IMG.jamonLonchas, "Jamón Oscar Mayer en lonchas")],
    specs: [
      { label: "Peso", value: "1 lb" },
      { label: "Tipo", value: "Cocido en lonchas" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 0.45,
    tags: ["jamón", "embutido", "sándwich"],
    rating: 4.6,
    reviewCount: 67,
  },
  {
    id: "p_alim_015",
    slug: "chorizo-espanol",
    name: "Chorizo Español",
    description: "Chorizo español curado, sabor auténtico y picante.",
    longDescription:
      "Chorizo español curado al estilo tradicional, con pimentón ahumado y especias. Sabor intenso, perfecto para el potaje de chícharo, paella, lentejas con chorizo o simplemente al plato. Pack de 1 lb.",
    category: "alimentos",
    subcategory: "carnes-y-pollo",
    brand: "Goya",
    countryOfOrigin: "España",
    price: 13.5,
    currency: "USD",
    thumbnail: IMG.chorizo,
    images: [img(IMG.chorizo, "Chorizo español")],
    specs: [
      { label: "Peso", value: "1 lb" },
      { label: "Estilo", value: "Curado tradicional" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 0.45,
    tags: ["chorizo", "español", "embutido"],
    rating: 4.8,
    reviewCount: 78,
  },
  {
    id: "p_alim_016",
    slug: "salchichas-vienesas",
    name: "Salchichas Vienesas",
    description: "Salchichas vienesas en lata, listas para comer.",
    longDescription:
      "Pack de salchichas vienesas en lata marca Bar-S, listas para comer. Practicidad total: se calientan en agua o se comen frías. Excelentes para la merienda de los niños o para emergencias.",
    category: "alimentos",
    subcategory: "carnes-y-pollo",
    brand: "Bar-S",
    countryOfOrigin: "Estados Unidos",
    price: 7.99,
    currency: "USD",
    thumbnail: IMG.salchichas,
    images: [img(IMG.salchichas, "Salchichas vienesas")],
    specs: [
      { label: "Cantidad", value: "Pack 6 latas" },
      { label: "Tipo", value: "Vienesas en agua" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.5,
    tags: ["salchicha", "lata", "merienda"],
    rating: 4.5,
    reviewCount: 56,
  },
  {
    id: "p_alim_017",
    slug: "camarones-congelados",
    name: "Camarones Congelados",
    description: "Camarones pelados congelados, talla mediana, listos para cocinar.",
    longDescription:
      "Camarones pelados y desvenados, congelados al momento del proceso. Talla mediana 41/50 (camarones por libra). Empaque de 1 lb sellado. Cadena de frío garantizada.",
    category: "alimentos",
    subcategory: "carnes-y-pollo",
    countryOfOrigin: "Ecuador",
    price: 18.99,
    currency: "USD",
    thumbnail: IMG.camarones,
    images: [img(IMG.camarones, "Camarones congelados")],
    specs: [
      { label: "Peso", value: "1 lb" },
      { label: "Talla", value: "41/50" },
      { label: "Estado", value: "Pelados desvenados" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 0.45,
    tags: ["mariscos", "camarón", "congelado"],
    rating: 4.7,
    reviewCount: 49,
  },
  {
    id: "p_alim_018",
    slug: "pescado-filetes",
    name: "Filetes de Pescado",
    description: "Filetes de pescado blanco congelados, sin espinas.",
    longDescription:
      "Filetes de pescado blanco (tilapia o basa), congelados, sin espinas, listos para empanizar o cocinar al vapor. Empaque de 2 lb con porciones individuales. Cadena de frío garantizada.",
    category: "alimentos",
    subcategory: "carnes-y-pollo",
    countryOfOrigin: "Vietnam",
    price: 23.99,
    currency: "USD",
    thumbnail: IMG.pescado,
    images: [img(IMG.pescado, "Filetes de pescado")],
    specs: [
      { label: "Peso", value: "2 lb" },
      { label: "Tipo", value: "Pescado blanco" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 0.91,
    tags: ["pescado", "filetes", "congelado"],
    rating: 4.6,
    reviewCount: 31,
  },
  {
    id: "p_alim_019",
    slug: "mariscos-mixtos",
    name: "Mariscos Mixtos",
    description: "Mezcla de mariscos congelados: camarón, calamar, mejillón.",
    longDescription:
      "Mezcla premium de mariscos congelados que incluye camarones, calamar, mejillones y pulpo. Ideal para paellas, arroz marinero o sopas. Empaque de 2 lb con cadena de frío garantizada.",
    category: "alimentos",
    subcategory: "carnes-y-pollo",
    countryOfOrigin: "España",
    price: 28.99,
    currency: "USD",
    thumbnail: IMG.mariscos,
    images: [img(IMG.mariscos, "Mariscos mixtos")],
    specs: [
      { label: "Peso", value: "2 lb" },
      { label: "Mezcla", value: "Camarón, calamar, mejillón, pulpo" },
    ],
    inStock: true,
    stockLevel: "low",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 0.91,
    tags: ["mariscos", "mezcla", "premium"],
    rating: 4.8,
    reviewCount: 26,
  },

  // ===========================================================
  // ACEITES Y CONDIMENTOS (14)
  // ===========================================================
  {
    id: "p_alim_003",
    slug: "aceite-soya-galon",
    name: "Aceite de Soya 1 Galón",
    description: "Aceite de soya puro, ideal para cocinar y freír.",
    longDescription:
      "Aceite de soya 100% puro, refinado, perfecto para cualquier preparación culinaria. Botella de 1 galón (3.78 L) que rinde por meses. Sin colesterol, sin grasas trans.",
    category: "alimentos",
    subcategory: "aceites-condimentos",
    brand: "Crisco",
    countryOfOrigin: "Estados Unidos",
    price: 12.99,
    currency: "USD",
    thumbnail: IMG.aceiteSoya,
    images: [img(IMG.aceiteSoya, "Aceite de soya")],
    specs: [
      { label: "Volumen", value: "1 galón (3.78 L)" },
      { label: "Tipo", value: "Soya puro refinado" },
      { label: "Sin", value: "Colesterol ni grasas trans" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 3.5,
    tags: ["aceite", "cocina", "básico"],
    rating: 4.6,
    reviewCount: 67,
    bestseller: true,
  },
  {
    id: "p_alim_031",
    slug: "aceite-oliva-extra-virgen",
    name: "Aceite de Oliva Extra Virgen 1L",
    description: "Aceite de oliva extra virgen español, primera prensada en frío.",
    longDescription:
      "Aceite de oliva extra virgen español de primera prensada en frío. Acidez baja, aroma frutado, perfecto para ensaladas, pan tostado y como toque final en platos. Botella de 1 litro.",
    category: "alimentos",
    subcategory: "aceites-condimentos",
    brand: "Carbonell",
    countryOfOrigin: "España",
    price: 14.99,
    currency: "USD",
    thumbnail: IMG.aceiteOliva,
    images: [img(IMG.aceiteOliva, "Aceite de oliva extra virgen")],
    specs: [
      { label: "Volumen", value: "1 L" },
      { label: "Tipo", value: "Extra virgen primera prensada" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.05,
    tags: ["aceite", "oliva", "premium", "saludable"],
    rating: 4.9,
    reviewCount: 73,
  },
  {
    id: "p_alim_032",
    slug: "aceite-girasol",
    name: "Aceite de Girasol 1L",
    description: "Aceite de girasol, ligero y versátil.",
    longDescription:
      "Aceite de girasol refinado, sabor neutro, perfecto para freír sin que el sabor del aceite se imponga. Alternativa más ligera al aceite de soya. Botella de 1 litro.",
    category: "alimentos",
    subcategory: "aceites-condimentos",
    brand: "Mazola",
    countryOfOrigin: "Estados Unidos",
    price: 9.99,
    currency: "USD",
    thumbnail: IMG.aceiteGirasol,
    images: [img(IMG.aceiteGirasol, "Aceite de girasol")],
    specs: [
      { label: "Volumen", value: "1 L" },
      { label: "Tipo", value: "Girasol refinado" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 0.95,
    tags: ["aceite", "girasol", "ligero"],
    rating: 4.5,
    reviewCount: 24,
  },
  {
    id: "p_alim_033",
    slug: "sal-mesa",
    name: "Sal de Mesa 5 lb",
    description: "Sal de mesa fina yodada.",
    longDescription:
      "Sal de mesa fina yodada, lista para usar. Bolsa de 5 lb que dura meses para una familia. Ideal para todo uso culinario.",
    category: "alimentos",
    subcategory: "aceites-condimentos",
    brand: "Morton",
    countryOfOrigin: "Estados Unidos",
    price: 3.99,
    currency: "USD",
    thumbnail: IMG.sal,
    images: [img(IMG.sal, "Sal de mesa")],
    specs: [
      { label: "Peso", value: "5 lb" },
      { label: "Tipo", value: "Yodada fina" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.27,
    tags: ["sal", "básico", "condimento"],
    rating: 4.7,
    reviewCount: 22,
  },
  {
    id: "p_alim_034",
    slug: "azucar-blanca",
    name: "Azúcar Blanca 5 lb",
    description: "Azúcar blanca refinada para todo uso.",
    longDescription:
      "Azúcar blanca refinada granulada, ideal para café, postres, batidos y panadería. Bolsa de 5 lb sellada.",
    category: "alimentos",
    subcategory: "aceites-condimentos",
    brand: "Domino",
    countryOfOrigin: "Estados Unidos",
    price: 5.99,
    currency: "USD",
    thumbnail: IMG.azucar,
    images: [img(IMG.azucar, "Azúcar blanca")],
    specs: [
      { label: "Peso", value: "5 lb" },
      { label: "Tipo", value: "Refinada blanca" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.27,
    tags: ["azúcar", "básico", "endulzante"],
    rating: 4.6,
    reviewCount: 31,
  },
  {
    id: "p_alim_035",
    slug: "azucar-morena",
    name: "Azúcar Morena 3 lb",
    description: "Azúcar morena con sabor a melaza.",
    longDescription:
      "Azúcar morena con notas de melaza, perfecta para postres, galletas y cocción de carnes (BBQ, glaseados). Bolsa de 3 lb.",
    category: "alimentos",
    subcategory: "aceites-condimentos",
    brand: "Domino",
    countryOfOrigin: "Estados Unidos",
    price: 5.5,
    currency: "USD",
    thumbnail: IMG.azucarMorena,
    images: [img(IMG.azucarMorena, "Azúcar morena")],
    specs: [
      { label: "Peso", value: "3 lb" },
      { label: "Tipo", value: "Morena con melaza" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.36,
    tags: ["azúcar", "morena", "postre"],
    rating: 4.7,
    reviewCount: 18,
  },
  {
    id: "p_alim_036",
    slug: "vinagre-blanco",
    name: "Vinagre Blanco 1L",
    description: "Vinagre blanco destilado, multiusos.",
    longDescription:
      "Vinagre blanco destilado al 5%, multiusos: cocina, conservas, ensaladas y limpieza. Botella de 1 litro.",
    category: "alimentos",
    subcategory: "aceites-condimentos",
    brand: "Heinz",
    countryOfOrigin: "Estados Unidos",
    price: 4.5,
    currency: "USD",
    thumbnail: IMG.vinagre,
    images: [img(IMG.vinagre, "Vinagre blanco")],
    specs: [
      { label: "Volumen", value: "1 L" },
      { label: "Acidez", value: "5%" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.05,
    tags: ["vinagre", "condimento", "básico"],
    rating: 4.5,
    reviewCount: 14,
  },
  {
    id: "p_alim_037",
    slug: "salsa-tomate",
    name: "Salsa de Tomate (3 unidades)",
    description: "Pack de 3 botellas de salsa de tomate Hunt's.",
    longDescription:
      "Pack de 3 botellas de salsa de tomate Hunt's, ideal para pastas, pizzas, arroz a la mexicana y guisos. Cada botella 24 oz.",
    category: "alimentos",
    subcategory: "aceites-condimentos",
    brand: "Hunt's",
    countryOfOrigin: "Estados Unidos",
    price: 6.99,
    currency: "USD",
    thumbnail: IMG.salsaTomate,
    images: [img(IMG.salsaTomate, "Salsa de tomate")],
    specs: [
      { label: "Cantidad", value: "3 botellas de 24 oz" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.2,
    tags: ["salsa", "tomate", "condimento"],
    rating: 4.6,
    reviewCount: 38,
  },
  {
    id: "p_alim_038",
    slug: "mostaza",
    name: "Mostaza",
    description: "Mostaza amarilla clásica French's.",
    longDescription:
      "Mostaza amarilla clásica French's, perfecta para hot dogs, hamburguesas, sándwiches y aderezos. Frasco de 14 oz.",
    category: "alimentos",
    subcategory: "aceites-condimentos",
    brand: "French's",
    countryOfOrigin: "Estados Unidos",
    price: 4.99,
    currency: "USD",
    thumbnail: IMG.mostaza,
    images: [img(IMG.mostaza, "Mostaza French's")],
    specs: [
      { label: "Volumen", value: "14 oz" },
      { label: "Tipo", value: "Amarilla clásica" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 0.4,
    tags: ["mostaza", "condimento"],
    rating: 4.5,
    reviewCount: 12,
  },
  {
    id: "p_alim_039",
    slug: "mayonesa-hellmanns",
    name: "Mayonesa Hellmann's 30 oz",
    description: "Mayonesa Hellmann's tradicional.",
    longDescription:
      "Mayonesa Hellmann's tradicional, la marca más confiable. Ideal para ensaladas frías, sándwiches y aderezos. Pomo grande de 30 oz que dura para varias semanas.",
    category: "alimentos",
    subcategory: "aceites-condimentos",
    brand: "Hellmann's",
    countryOfOrigin: "Estados Unidos",
    price: 7.5,
    currency: "USD",
    thumbnail: IMG.mayonesa,
    images: [img(IMG.mayonesa, "Mayonesa Hellmann's")],
    specs: [
      { label: "Volumen", value: "30 oz" },
      { label: "Tipo", value: "Tradicional" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 0.95,
    tags: ["mayonesa", "condimento", "ensalada"],
    rating: 4.8,
    reviewCount: 62,
  },
  {
    id: "p_alim_040",
    slug: "especias-mixtas",
    name: "Kit Especias Mixtas",
    description: "Kit con orégano, comino, ajo, pimienta, laurel y más.",
    longDescription:
      "Kit completo de 10 especias para la cocina cubana: orégano, comino, ajo en polvo, pimienta negra, laurel, paprika, cebolla en polvo, perejil, sal de ajo y mojo seco. Frascos sellados.",
    category: "alimentos",
    subcategory: "aceites-condimentos",
    brand: "McCormick",
    countryOfOrigin: "Estados Unidos",
    price: 14.99,
    currency: "USD",
    thumbnail: IMG.especias,
    images: [img(IMG.especias, "Kit de especias")],
    specs: [
      { label: "Cantidad", value: "10 frascos" },
      { label: "Marca", value: "McCormick" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 0.8,
    tags: ["especias", "kit", "criollo"],
    rating: 4.8,
    reviewCount: 47,
    featured: true,
  },
  {
    id: "p_alim_041",
    slug: "cafe-la-llave",
    name: "Café La Llave 10 oz",
    description: "Café cubano oscuro La Llave, sabor intenso.",
    longDescription:
      "Café La Llave, el favorito de los cubanos. Tueste oscuro, molienda fina, sabor intenso y aromático. Brick de 10 oz sellado al vacío que mantiene la frescura.",
    category: "alimentos",
    subcategory: "aceites-condimentos",
    brand: "La Llave",
    countryOfOrigin: "Estados Unidos",
    price: 7.99,
    currency: "USD",
    thumbnail: IMG.cafeLlave,
    images: [img(IMG.cafeLlave, "Café La Llave")],
    specs: [
      { label: "Peso", value: "10 oz (283 g)" },
      { label: "Tueste", value: "Oscuro" },
      { label: "Molienda", value: "Fina" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 0.28,
    tags: ["café", "cubano", "imprescindible"],
    rating: 4.9,
    reviewCount: 198,
    bestseller: true,
    featured: true,
  },
  {
    id: "p_alim_042",
    slug: "cafe-bustelo",
    name: "Café Bustelo 10 oz",
    description: "Café Bustelo tueste oscuro, alternativa al La Llave.",
    longDescription:
      "Café Bustelo, otra leyenda del café cubano. Tueste oscuro, molienda fina, ideal para cafetera moka. Sabor robusto que combina perfecto con un poquito de azúcar.",
    category: "alimentos",
    subcategory: "aceites-condimentos",
    brand: "Café Bustelo",
    countryOfOrigin: "Estados Unidos",
    price: 7.5,
    currency: "USD",
    thumbnail: IMG.cafeBustelo,
    images: [img(IMG.cafeBustelo, "Café Bustelo")],
    specs: [
      { label: "Peso", value: "10 oz" },
      { label: "Tueste", value: "Oscuro" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 0.28,
    tags: ["café", "cubano"],
    rating: 4.8,
    reviewCount: 134,
    bestseller: true,
  },
  {
    id: "p_alim_043",
    slug: "te-bolsas-100",
    name: "Té en Bolsas (caja x100)",
    description: "Caja de 100 bolsas de té negro Lipton.",
    longDescription:
      "Caja económica de 100 bolsas de té negro Lipton. Ideal para mantener una buena cantidad por meses. Cada bolsa rinde para 1 taza grande.",
    category: "alimentos",
    subcategory: "aceites-condimentos",
    brand: "Lipton",
    countryOfOrigin: "Estados Unidos",
    price: 5.99,
    currency: "USD",
    thumbnail: IMG.te,
    images: [img(IMG.te, "Té Lipton")],
    specs: [
      { label: "Cantidad", value: "100 bolsas" },
      { label: "Tipo", value: "Té negro" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 0.4,
    tags: ["té", "bebida"],
    rating: 4.6,
    reviewCount: 28,
  },

  // ===========================================================
  // LÁCTEOS (12)
  // ===========================================================
  {
    id: "p_alim_004",
    slug: "leche-en-polvo-nido-5lb",
    name: "Leche en Polvo Nido 5 lb",
    description: "Leche en polvo entera Nido, calidad premium, larga duración.",
    longDescription:
      "Leche en polvo entera Nido de Nestlé, fortificada con vitaminas A, C y D, y minerales esenciales. Bolsa de 5 lb (2.27 kg) que rinde aproximadamente 18 litros de leche reconstituida. Ideal para familias, dura meses sin refrigerar.",
    category: "alimentos",
    subcategory: "lacteos",
    brand: "Nido (Nestlé)",
    countryOfOrigin: "México",
    price: 32.99,
    currency: "USD",
    thumbnail: IMG.leche,
    images: [img(IMG.leche, "Leche en polvo Nido")],
    specs: [
      { label: "Peso", value: "5 lb (2.27 kg)" },
      { label: "Rinde", value: "~18 litros" },
      { label: "Vitaminas", value: "A, C, D + minerales" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.27,
    tags: ["lácteo", "leche", "familiar", "premium"],
    rating: 4.9,
    reviewCount: 215,
    bestseller: true,
    featured: true,
  },
  {
    id: "p_alim_044",
    slug: "leche-polvo-familia",
    name: "Leche en Polvo Familia 4 lb",
    description: "Leche en polvo Familia, alternativa más económica.",
    longDescription:
      "Leche en polvo entera marca Familia, de calidad similar al Nido a un precio más amigable. Fortificada con vitaminas. Bolsa de 4 lb que rinde unos 14 litros.",
    category: "alimentos",
    subcategory: "lacteos",
    brand: "Familia",
    countryOfOrigin: "Colombia",
    price: 26.99,
    currency: "USD",
    thumbnail: IMG.leche,
    images: [img(IMG.leche, "Leche en polvo Familia")],
    specs: [
      { label: "Peso", value: "4 lb" },
      { label: "Rinde", value: "~14 litros" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.81,
    tags: ["lácteo", "leche", "económico"],
    rating: 4.5,
    reviewCount: 78,
  },
  {
    id: "p_alim_045",
    slug: "leche-descremada-polvo",
    name: "Leche Descremada en Polvo",
    description: "Leche descremada en polvo, baja en grasa.",
    longDescription:
      "Leche descremada en polvo, ideal para personas con dietas bajas en grasa o con colesterol alto. Conserva el calcio y proteínas. Bolsa de 4 lb.",
    category: "alimentos",
    subcategory: "lacteos",
    brand: "Nido (Nestlé)",
    countryOfOrigin: "México",
    price: 28.99,
    currency: "USD",
    thumbnail: IMG.leche,
    images: [img(IMG.leche, "Leche descremada en polvo")],
    specs: [
      { label: "Peso", value: "4 lb" },
      { label: "Tipo", value: "Descremada 0% grasa" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.81,
    tags: ["lácteo", "saludable", "descremada"],
    rating: 4.6,
    reviewCount: 41,
  },
  {
    id: "p_alim_046",
    slug: "leche-condensada-nestle",
    name: "Leche Condensada Nestlé (caja x12)",
    description: "Caja de 12 latas de leche condensada Nestlé.",
    longDescription:
      "Caja de 12 latas de leche condensada Nestlé La Lechera. Ideal para flanes, dulce de leche, café con leche y postres tradicionales cubanos. Cada lata 14 oz.",
    category: "alimentos",
    subcategory: "lacteos",
    brand: "La Lechera (Nestlé)",
    countryOfOrigin: "México",
    price: 21.99,
    currency: "USD",
    thumbnail: IMG.lecheCondensada,
    images: [img(IMG.lecheCondensada, "Leche condensada La Lechera")],
    specs: [
      { label: "Cantidad", value: "12 latas de 14 oz" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 5.1,
    tags: ["lácteo", "condensada", "postre"],
    rating: 4.9,
    reviewCount: 112,
    bestseller: true,
  },
  {
    id: "p_alim_047",
    slug: "leche-evaporada",
    name: "Leche Evaporada (caja x12)",
    description: "Caja de 12 latas de leche evaporada Carnation.",
    longDescription:
      "Caja de 12 latas de leche evaporada Carnation, ideal para café con leche, dulces y postres. Cada lata 12 oz.",
    category: "alimentos",
    subcategory: "lacteos",
    brand: "Carnation (Nestlé)",
    countryOfOrigin: "Estados Unidos",
    price: 18.99,
    currency: "USD",
    thumbnail: IMG.lecheEvaporada,
    images: [img(IMG.lecheEvaporada, "Leche evaporada")],
    specs: [
      { label: "Cantidad", value: "12 latas de 12 oz" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 4.4,
    tags: ["lácteo", "evaporada"],
    rating: 4.7,
    reviewCount: 56,
  },
  {
    id: "p_alim_048",
    slug: "queso-amarillo",
    name: "Queso Amarillo 3 lb",
    description: "Queso amarillo en bloque, perfecto para sándwiches.",
    longDescription:
      "Bloque de queso amarillo americano de 3 lb, ideal para sándwiches calientes, hamburguesas y para fundir sobre tostadas. Sellado al vacío para conservación prolongada.",
    category: "alimentos",
    subcategory: "lacteos",
    brand: "Land O' Lakes",
    countryOfOrigin: "Estados Unidos",
    price: 19.99,
    currency: "USD",
    thumbnail: IMG.queso,
    images: [img(IMG.queso, "Queso amarillo en bloque")],
    specs: [
      { label: "Peso", value: "3 lb" },
      { label: "Tipo", value: "Amarillo americano" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 1.36,
    tags: ["queso", "lácteo", "sándwich"],
    rating: 4.8,
    reviewCount: 89,
    bestseller: true,
  },
  {
    id: "p_alim_049",
    slug: "queso-blanco",
    name: "Queso Blanco 2 lb",
    description: "Queso blanco fresco al estilo cubano.",
    longDescription:
      "Queso blanco fresco al estilo cubano, sabor suave, ideal para acompañar el desayuno cubano con tostada o para fundir sobre platanitos maduros.",
    category: "alimentos",
    subcategory: "lacteos",
    brand: "Tropical",
    countryOfOrigin: "Estados Unidos",
    price: 15.99,
    currency: "USD",
    thumbnail: IMG.quesoBlanco,
    images: [img(IMG.quesoBlanco, "Queso blanco")],
    specs: [
      { label: "Peso", value: "2 lb" },
      { label: "Tipo", value: "Fresco estilo cubano" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 0.91,
    tags: ["queso", "blanco", "cubano"],
    rating: 4.7,
    reviewCount: 64,
  },
  {
    id: "p_alim_050",
    slug: "mantequilla",
    name: "Mantequilla 3 lb",
    description: "Mantequilla cremosa en barras.",
    longDescription:
      "Mantequilla cremosa Land O' Lakes en barras, 3 lb totales en 12 barras de 1/4 lb cada una. Ideal para repostería, pan tostado y cocinar.",
    category: "alimentos",
    subcategory: "lacteos",
    brand: "Land O' Lakes",
    countryOfOrigin: "Estados Unidos",
    price: 14.99,
    currency: "USD",
    thumbnail: IMG.mantequilla,
    images: [img(IMG.mantequilla, "Mantequilla en barras")],
    specs: [
      { label: "Peso", value: "3 lb (12 barras)" },
      { label: "Tipo", value: "Con sal" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 1.36,
    tags: ["mantequilla", "lácteo"],
    rating: 4.8,
    reviewCount: 47,
  },
  {
    id: "p_alim_051",
    slug: "margarina",
    name: "Margarina 2 lb",
    description: "Margarina vegetal en pomo, alternativa más económica.",
    longDescription:
      "Margarina vegetal en pomo grande de 2 lb. Alternativa más económica a la mantequilla. Sin necesidad de refrigeración hasta abrir el pomo.",
    category: "alimentos",
    subcategory: "lacteos",
    brand: "Country Crock",
    countryOfOrigin: "Estados Unidos",
    price: 9.99,
    currency: "USD",
    thumbnail: IMG.margarina,
    images: [img(IMG.margarina, "Margarina")],
    specs: [
      { label: "Peso", value: "2 lb" },
      { label: "Tipo", value: "Vegetal" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 0.91,
    tags: ["margarina", "económica"],
    rating: 4.4,
    reviewCount: 22,
  },
  {
    id: "p_alim_052",
    slug: "mantequilla-mani",
    name: "Mantequilla de Maní 28 oz",
    description: "Mantequilla de maní cremosa Skippy.",
    longDescription:
      "Mantequilla de maní Skippy cremosa, frasco grande de 28 oz. Excelente fuente de proteína. Para sándwiches, batidos y galletas.",
    category: "alimentos",
    subcategory: "lacteos",
    brand: "Skippy",
    countryOfOrigin: "Estados Unidos",
    price: 8.99,
    currency: "USD",
    thumbnail: IMG.mantequillaMani,
    images: [img(IMG.mantequillaMani, "Mantequilla de maní")],
    specs: [
      { label: "Volumen", value: "28 oz" },
      { label: "Tipo", value: "Cremosa" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 0.85,
    tags: ["maní", "proteína", "merienda"],
    rating: 4.7,
    reviewCount: 51,
  },
  {
    id: "p_alim_053",
    slug: "dulce-de-leche",
    name: "Dulce de Leche 1 lb",
    description: "Dulce de leche cremoso, postre tradicional.",
    longDescription:
      "Dulce de leche cremoso de tradición latinoamericana. Frasco de 1 lb. Para postres, helados, galletas, alfajores o simplemente con cuchara.",
    category: "alimentos",
    subcategory: "lacteos",
    brand: "Conaprole",
    countryOfOrigin: "Argentina",
    price: 7.5,
    currency: "USD",
    thumbnail: IMG.dulceLeche,
    images: [img(IMG.dulceLeche, "Dulce de leche")],
    specs: [
      { label: "Peso", value: "1 lb" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 0.45,
    tags: ["dulce", "postre", "lácteo"],
    rating: 4.8,
    reviewCount: 36,
  },
  {
    id: "p_alim_054",
    slug: "crema-leche",
    name: "Crema de Leche",
    description: "Crema de leche en lata, lista para postres.",
    longDescription:
      "Pack de 4 latas de crema de leche Nestlé Media Crema, perfecta para postres, salsas y arroz a la cubana cremoso. No requiere refrigeración hasta abrir.",
    category: "alimentos",
    subcategory: "lacteos",
    brand: "Nestlé Media Crema",
    countryOfOrigin: "México",
    price: 6.99,
    currency: "USD",
    thumbnail: IMG.cremaLeche,
    images: [img(IMG.cremaLeche, "Crema de leche")],
    specs: [
      { label: "Cantidad", value: "4 latas de 7.6 oz" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 0.95,
    tags: ["crema", "lácteo", "postre"],
    rating: 4.6,
    reviewCount: 24,
  },

  // ===========================================================
  // CONSERVAS (14)
  // ===========================================================
  {
    id: "p_alim_055",
    slug: "atun-aceite-caja",
    name: "Atún en Aceite (caja x10)",
    description: "Caja de 10 latas de atún en aceite de oliva.",
    longDescription:
      "Caja económica de 10 latas de atún en aceite de oliva, sólido en trozos. Ideal para ensaladas, sándwiches y empanadas. Cada lata 5 oz.",
    category: "alimentos",
    subcategory: "conservas",
    brand: "Bumble Bee",
    countryOfOrigin: "Estados Unidos",
    price: 19.99,
    currency: "USD",
    thumbnail: IMG.atun,
    images: [img(IMG.atun, "Atún en aceite")],
    specs: [
      { label: "Cantidad", value: "10 latas de 5 oz" },
      { label: "Tipo", value: "En aceite de oliva" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.7,
    tags: ["atún", "conserva", "proteína"],
    rating: 4.7,
    reviewCount: 87,
    bestseller: true,
  },
  {
    id: "p_alim_056",
    slug: "atun-agua-caja",
    name: "Atún en Agua (caja x10)",
    description: "Caja de 10 latas de atún en agua, opción ligera.",
    longDescription:
      "Caja económica de 10 latas de atún sólido en agua, opción más ligera y baja en grasa. Cada lata 5 oz.",
    category: "alimentos",
    subcategory: "conservas",
    brand: "Bumble Bee",
    countryOfOrigin: "Estados Unidos",
    price: 18.99,
    currency: "USD",
    thumbnail: IMG.atun,
    images: [img(IMG.atun, "Atún en agua")],
    specs: [
      { label: "Cantidad", value: "10 latas de 5 oz" },
      { label: "Tipo", value: "En agua" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.7,
    tags: ["atún", "conserva", "saludable"],
    rating: 4.6,
    reviewCount: 54,
  },
  {
    id: "p_alim_057",
    slug: "sardinas-aceite-caja",
    name: "Sardinas en Aceite (caja x12)",
    description: "Caja de 12 latas de sardinas en aceite vegetal.",
    longDescription:
      "Caja económica de 12 latas de sardinas en aceite vegetal Goya. Excelente fuente de omega-3 y proteína. Cada lata 4.25 oz.",
    category: "alimentos",
    subcategory: "conservas",
    brand: "Goya",
    countryOfOrigin: "Marruecos",
    price: 16.99,
    currency: "USD",
    thumbnail: IMG.sardinas,
    images: [img(IMG.sardinas, "Sardinas en aceite")],
    specs: [
      { label: "Cantidad", value: "12 latas de 4.25 oz" },
      { label: "Tipo", value: "En aceite vegetal" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.85,
    tags: ["sardinas", "conserva", "omega-3"],
    rating: 4.8,
    reviewCount: 76,
    bestseller: true,
  },
  {
    id: "p_alim_058",
    slug: "jamoneta-caja",
    name: "Jamoneta (caja x6)",
    description: "Caja de 6 latas de jamoneta enlatada.",
    longDescription:
      "Caja de 6 latas de jamoneta tipo española, lista para comer. Ideal para sándwiches y bocaditos. Sabor tradicional. Cada lata 12 oz.",
    category: "alimentos",
    subcategory: "conservas",
    brand: "La Cubanita",
    countryOfOrigin: "Estados Unidos",
    price: 24.99,
    currency: "USD",
    thumbnail: IMG.jamoneta,
    images: [img(IMG.jamoneta, "Jamoneta enlatada")],
    specs: [
      { label: "Cantidad", value: "6 latas de 12 oz" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.1,
    tags: ["jamoneta", "conserva", "criollo"],
    rating: 4.7,
    reviewCount: 92,
    bestseller: true,
  },
  {
    id: "p_alim_059",
    slug: "salchichas-lata-caja",
    name: "Salchichas en Lata (caja x12)",
    description: "Caja de 12 latas de salchichas en agua.",
    longDescription:
      "Caja económica de 12 latas de salchichas vienesas en agua marca Bar-S. Listas para calentar. Cada lata 5 oz con 7 salchichas aprox.",
    category: "alimentos",
    subcategory: "conservas",
    brand: "Bar-S",
    countryOfOrigin: "Estados Unidos",
    price: 17.99,
    currency: "USD",
    thumbnail: IMG.salchichas,
    images: [img(IMG.salchichas, "Salchichas en lata")],
    specs: [
      { label: "Cantidad", value: "12 latas de 5 oz" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.95,
    tags: ["salchicha", "conserva"],
    rating: 4.5,
    reviewCount: 38,
  },
  {
    id: "p_alim_060",
    slug: "spam-original",
    name: "Spam Original (caja x6)",
    description: "Caja de 6 latas de Spam clásico.",
    longDescription:
      "Caja de 6 latas de Spam Original. Carne de cerdo enlatada lista para comer. Versátil: se puede freír, asar o comer fría. Cada lata 12 oz.",
    category: "alimentos",
    subcategory: "conservas",
    brand: "Spam",
    countryOfOrigin: "Estados Unidos",
    price: 22.99,
    currency: "USD",
    thumbnail: IMG.spam,
    images: [img(IMG.spam, "Spam original")],
    specs: [
      { label: "Cantidad", value: "6 latas de 12 oz" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.05,
    tags: ["spam", "conserva", "cerdo"],
    rating: 4.6,
    reviewCount: 64,
  },
  {
    id: "p_alim_061",
    slug: "vegetales-mixtos-caja",
    name: "Vegetales Mixtos (caja x6)",
    description: "Caja de 6 latas de vegetales mixtos en agua.",
    longDescription:
      "Caja de 6 latas de mezcla de vegetales (zanahoria, papa, arvejas, maíz, habichuelas) en agua, lista para acompañar cualquier plato.",
    category: "alimentos",
    subcategory: "conservas",
    brand: "Del Monte",
    countryOfOrigin: "Estados Unidos",
    price: 11.99,
    currency: "USD",
    thumbnail: IMG.vegetalesLata,
    images: [img(IMG.vegetalesLata, "Vegetales mixtos en lata")],
    specs: [
      { label: "Cantidad", value: "6 latas de 14.5 oz" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.5,
    tags: ["vegetales", "conserva"],
    rating: 4.5,
    reviewCount: 42,
  },
  {
    id: "p_alim_062",
    slug: "arvejas-lata-caja",
    name: "Arvejas en Lata (caja x6)",
    description: "Caja de 6 latas de arvejas verdes.",
    longDescription:
      "Caja de 6 latas de arvejas verdes Del Monte, listas para comer o acompañar arroz. Cada lata 15 oz.",
    category: "alimentos",
    subcategory: "conservas",
    brand: "Del Monte",
    countryOfOrigin: "Estados Unidos",
    price: 9.99,
    currency: "USD",
    thumbnail: IMG.arvejas,
    images: [img(IMG.arvejas, "Arvejas en lata")],
    specs: [
      { label: "Cantidad", value: "6 latas de 15 oz" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.55,
    tags: ["arvejas", "conserva"],
    rating: 4.5,
    reviewCount: 28,
  },
  {
    id: "p_alim_063",
    slug: "maiz-dulce-caja",
    name: "Maíz Dulce (caja x6)",
    description: "Caja de 6 latas de maíz dulce.",
    longDescription:
      "Caja de 6 latas de maíz dulce en grano Del Monte. Tierno y dulce, perfecto para ensaladas, arroces y guarniciones.",
    category: "alimentos",
    subcategory: "conservas",
    brand: "Del Monte",
    countryOfOrigin: "Estados Unidos",
    price: 10.99,
    currency: "USD",
    thumbnail: IMG.maizDulce,
    images: [img(IMG.maizDulce, "Maíz dulce")],
    specs: [
      { label: "Cantidad", value: "6 latas de 15 oz" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.55,
    tags: ["maíz", "conserva"],
    rating: 4.6,
    reviewCount: 31,
  },
  {
    id: "p_alim_064",
    slug: "frijoles-lata-caja",
    name: "Frijoles en Lata (caja x12)",
    description: "Caja de 12 latas de frijoles negros refritos.",
    longDescription:
      "Caja económica de 12 latas de frijoles negros estilo cubano Goya, listos para calentar. Cada lata 15 oz. Para emergencias o cuando no hay tiempo de cocinar.",
    category: "alimentos",
    subcategory: "conservas",
    brand: "Goya",
    countryOfOrigin: "Estados Unidos",
    price: 14.99,
    currency: "USD",
    thumbnail: IMG.vegetalesLata,
    images: [img(IMG.vegetalesLata, "Frijoles en lata")],
    specs: [
      { label: "Cantidad", value: "12 latas de 15 oz" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 5.1,
    tags: ["frijoles", "conserva"],
    rating: 4.7,
    reviewCount: 56,
  },
  {
    id: "p_alim_065",
    slug: "duraznos-almibar",
    name: "Duraznos en Almíbar (caja x6)",
    description: "Caja de 6 latas de duraznos en almíbar.",
    longDescription:
      "Caja de 6 latas de duraznos en mitades en almíbar Del Monte. Postre listo o para acompañar postres y helados.",
    category: "alimentos",
    subcategory: "conservas",
    brand: "Del Monte",
    countryOfOrigin: "Estados Unidos",
    price: 13.99,
    currency: "USD",
    thumbnail: IMG.duraznos,
    images: [img(IMG.duraznos, "Duraznos en almíbar")],
    specs: [
      { label: "Cantidad", value: "6 latas de 15 oz" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.55,
    tags: ["fruta", "conserva", "postre"],
    rating: 4.7,
    reviewCount: 47,
  },
  {
    id: "p_alim_066",
    slug: "pina-almibar",
    name: "Piña en Almíbar (caja x6)",
    description: "Caja de 6 latas de piña en rodajas.",
    longDescription:
      "Caja de 6 latas de piña en rodajas en almíbar Dole. Perfecta para postres, batidos y para acompañar carnes (pollo a la piña, pernil).",
    category: "alimentos",
    subcategory: "conservas",
    brand: "Dole",
    countryOfOrigin: "Filipinas",
    price: 12.99,
    currency: "USD",
    thumbnail: IMG.pina,
    images: [img(IMG.pina, "Piña en almíbar")],
    specs: [
      { label: "Cantidad", value: "6 latas de 20 oz" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 3.4,
    tags: ["piña", "conserva", "fruta"],
    rating: 4.7,
    reviewCount: 38,
  },
  {
    id: "p_alim_067",
    slug: "mermelada-variada",
    name: "Mermelada Variada (3 frascos)",
    description: "3 frascos de mermelada: fresa, naranja y guayaba.",
    longDescription:
      "Trío de mermeladas Smucker's: fresa, naranja amarga y guayaba. Cada frasco 18 oz. Perfectas para tostadas, panqueques y tartas.",
    category: "alimentos",
    subcategory: "conservas",
    brand: "Smucker's",
    countryOfOrigin: "Estados Unidos",
    price: 9.99,
    currency: "USD",
    thumbnail: IMG.mermelada,
    images: [img(IMG.mermelada, "Mermeladas surtidas")],
    specs: [
      { label: "Cantidad", value: "3 frascos de 18 oz" },
      { label: "Sabores", value: "Fresa, naranja, guayaba" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.5,
    tags: ["mermelada", "dulce", "desayuno"],
    rating: 4.6,
    reviewCount: 23,
  },
  {
    id: "p_alim_068",
    slug: "pulpa-fruta-tropical",
    name: "Pulpa de Fruta Tropical",
    description: "Pulpa de fruta tropical para batidos.",
    longDescription:
      "Pack de pulpas tropicales congeladas Goya: mango, guayaba, mamey y guanábana. Cada paquete 14 oz. Perfectas para batidos cubanos auténticos.",
    category: "alimentos",
    subcategory: "conservas",
    brand: "Goya",
    countryOfOrigin: "Colombia",
    price: 11.99,
    currency: "USD",
    thumbnail: IMG.pulpa,
    images: [img(IMG.pulpa, "Pulpa de fruta tropical")],
    specs: [
      { label: "Cantidad", value: "4 paquetes de 14 oz" },
      { label: "Sabores", value: "Mango, guayaba, mamey, guanábana" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 1.6,
    tags: ["fruta", "tropical", "batido"],
    rating: 4.8,
    reviewCount: 67,
  },

  // ===========================================================
  // ASEO PERSONAL (13)
  // ===========================================================
  {
    id: "p_alim_069",
    slug: "jabon-dove-paquete",
    name: "Jabón Dove (paquete x6)",
    description: "Paquete de 6 jabones Dove humectantes.",
    longDescription:
      "Paquete de 6 jabones Dove Beauty Bar, con 1/4 de crema humectante. Suave con la piel, sin resecar. La marca de aseo más solicitada para envíos a Cuba.",
    category: "alimentos",
    subcategory: "aseo-personal",
    brand: "Dove",
    countryOfOrigin: "Estados Unidos",
    price: 12.99,
    currency: "USD",
    thumbnail: IMG.jabonDove,
    images: [img(IMG.jabonDove, "Jabón Dove pack")],
    specs: [
      { label: "Cantidad", value: "6 jabones de 3.75 oz" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.4,
    tags: ["jabón", "aseo", "Dove"],
    rating: 4.9,
    reviewCount: 178,
    bestseller: true,
    featured: true,
  },
  {
    id: "p_alim_070",
    slug: "jabon-palmolive",
    name: "Jabón Palmolive (paquete x10)",
    description: "Paquete de 10 jabones Palmolive aromáticos.",
    longDescription:
      "Paquete económico de 10 jabones Palmolive con aromas variados. Limpieza diaria, espuma cremosa.",
    category: "alimentos",
    subcategory: "aseo-personal",
    brand: "Palmolive",
    countryOfOrigin: "Colombia",
    price: 11.99,
    currency: "USD",
    thumbnail: IMG.jabonPalmolive,
    images: [img(IMG.jabonPalmolive, "Jabón Palmolive")],
    specs: [
      { label: "Cantidad", value: "10 jabones de 4 oz" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.3,
    tags: ["jabón", "aseo", "económico"],
    rating: 4.6,
    reviewCount: 78,
  },
  {
    id: "p_alim_071",
    slug: "pasta-colgate",
    name: "Pasta Dental Colgate (paquete x4)",
    description: "Pack de 4 pastas dentales Colgate Total.",
    longDescription:
      "Pack de 4 pastas dentales Colgate Total, protección 12 horas. Cada tubo 6 oz. Suficiente para varios meses.",
    category: "alimentos",
    subcategory: "aseo-personal",
    brand: "Colgate",
    countryOfOrigin: "Estados Unidos",
    price: 9.99,
    currency: "USD",
    thumbnail: IMG.pastaColgate,
    images: [img(IMG.pastaColgate, "Pasta dental Colgate")],
    specs: [
      { label: "Cantidad", value: "4 tubos de 6 oz" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 0.85,
    tags: ["pasta", "dental", "aseo"],
    rating: 4.8,
    reviewCount: 96,
    bestseller: true,
  },
  {
    id: "p_alim_072",
    slug: "pasta-crest",
    name: "Pasta Dental Crest (paquete x4)",
    description: "Pack de 4 pastas dentales Crest 3D White.",
    longDescription:
      "Pack de 4 pastas dentales Crest 3D White, blanqueamiento progresivo. Cada tubo 4.8 oz. Sabor menta refrescante.",
    category: "alimentos",
    subcategory: "aseo-personal",
    brand: "Crest",
    countryOfOrigin: "Estados Unidos",
    price: 10.99,
    currency: "USD",
    thumbnail: IMG.pastaCrest,
    images: [img(IMG.pastaCrest, "Pasta dental Crest")],
    specs: [
      { label: "Cantidad", value: "4 tubos de 4.8 oz" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 0.7,
    tags: ["pasta", "dental", "blanqueamiento"],
    rating: 4.7,
    reviewCount: 54,
  },
  {
    id: "p_alim_073",
    slug: "champu-hs",
    name: "Champú Head & Shoulders 32 oz",
    description: "Champú anticaspa Head & Shoulders, botella grande.",
    longDescription:
      "Champú anticaspa Head & Shoulders Classic Clean, botella grande de 32.1 oz. Marca confiable, controla la caspa desde el primer uso.",
    category: "alimentos",
    subcategory: "aseo-personal",
    brand: "Head & Shoulders",
    countryOfOrigin: "Estados Unidos",
    price: 13.99,
    currency: "USD",
    thumbnail: IMG.champu,
    images: [img(IMG.champu, "Champú Head & Shoulders")],
    specs: [
      { label: "Volumen", value: "32.1 oz" },
      { label: "Tipo", value: "Anticaspa Classic Clean" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.05,
    tags: ["champú", "aseo", "anticaspa"],
    rating: 4.8,
    reviewCount: 132,
    bestseller: true,
  },
  {
    id: "p_alim_074",
    slug: "champu-pantene",
    name: "Champú Pantene 32 oz",
    description: "Champú Pantene Pro-V hidratante.",
    longDescription:
      "Champú Pantene Pro-V Hidratación Extrema, botella grande de 33.8 oz. Pelo suave, manejable y brillante. La marca preferida para el cabello.",
    category: "alimentos",
    subcategory: "aseo-personal",
    brand: "Pantene",
    countryOfOrigin: "Estados Unidos",
    price: 12.99,
    currency: "USD",
    thumbnail: IMG.champuPantene,
    images: [img(IMG.champuPantene, "Champú Pantene")],
    specs: [
      { label: "Volumen", value: "33.8 oz" },
      { label: "Tipo", value: "Hidratación Pro-V" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.05,
    tags: ["champú", "aseo", "hidratante"],
    rating: 4.7,
    reviewCount: 88,
  },
  {
    id: "p_alim_075",
    slug: "acondicionador-pantene",
    name: "Acondicionador Pantene 32 oz",
    description: "Acondicionador Pantene Pro-V hidratante.",
    longDescription:
      "Acondicionador Pantene Pro-V Hidratación Extrema. Complementa el champú para un cabello más suave, fuerte y brillante. Botella grande de 33.8 oz.",
    category: "alimentos",
    subcategory: "aseo-personal",
    brand: "Pantene",
    countryOfOrigin: "Estados Unidos",
    price: 11.99,
    currency: "USD",
    thumbnail: IMG.acondicionador,
    images: [img(IMG.acondicionador, "Acondicionador Pantene")],
    specs: [
      { label: "Volumen", value: "33.8 oz" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.05,
    tags: ["acondicionador", "aseo", "cabello"],
    rating: 4.7,
    reviewCount: 71,
  },
  {
    id: "p_alim_076",
    slug: "desodorante-old-spice",
    name: "Desodorante Old Spice (3 unidades)",
    description: "Pack de 3 desodorantes Old Spice masculinos.",
    longDescription:
      "Pack de 3 barras de desodorante antitranspirante Old Spice High Endurance. Aroma masculino fresco, protección 24 horas. Cada barra 3 oz.",
    category: "alimentos",
    subcategory: "aseo-personal",
    brand: "Old Spice",
    countryOfOrigin: "Estados Unidos",
    price: 11.99,
    currency: "USD",
    thumbnail: IMG.desodorante,
    images: [img(IMG.desodorante, "Desodorante Old Spice")],
    specs: [
      { label: "Cantidad", value: "3 barras de 3 oz" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 0.5,
    tags: ["desodorante", "hombre", "aseo"],
    rating: 4.7,
    reviewCount: 56,
  },
  {
    id: "p_alim_077",
    slug: "desodorante-dove",
    name: "Desodorante Dove (3 unidades)",
    description: "Pack de 3 desodorantes Dove para mujer.",
    longDescription:
      "Pack de 3 barras de desodorante antitranspirante Dove con 1/4 de crema humectante. Cuidado de la piel mientras protege contra el sudor. Cada barra 2.6 oz.",
    category: "alimentos",
    subcategory: "aseo-personal",
    brand: "Dove",
    countryOfOrigin: "Estados Unidos",
    price: 13.99,
    currency: "USD",
    thumbnail: IMG.desodorante,
    images: [img(IMG.desodorante, "Desodorante Dove")],
    specs: [
      { label: "Cantidad", value: "3 barras de 2.6 oz" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 0.45,
    tags: ["desodorante", "mujer", "aseo"],
    rating: 4.8,
    reviewCount: 78,
  },
  {
    id: "p_alim_078",
    slug: "toallas-always",
    name: "Toallas Sanitarias Always (paquete x4)",
    description: "Pack de 4 paquetes de toallas Always Ultra Thin.",
    longDescription:
      "Pack de 4 paquetes de toallas sanitarias Always Ultra Thin con alas, talla regular. Total 144 toallas. Producto muy demandado para enviar a Cuba.",
    category: "alimentos",
    subcategory: "aseo-personal",
    brand: "Always",
    countryOfOrigin: "Estados Unidos",
    price: 19.99,
    currency: "USD",
    thumbnail: IMG.toallas,
    images: [img(IMG.toallas, "Toallas sanitarias Always")],
    specs: [
      { label: "Cantidad", value: "4 paquetes (144 unidades)" },
      { label: "Tipo", value: "Ultra Thin con alas" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.4,
    tags: ["toallas", "femenino", "aseo"],
    rating: 4.9,
    reviewCount: 124,
    bestseller: true,
  },
  {
    id: "p_alim_005",
    slug: "panales-pampers",
    name: "Pañales Pampers Baby Dry",
    description: "Pañales desechables Pampers, hasta 12 horas de protección.",
    longDescription:
      "Pañales desechables Pampers Baby Dry con tecnología de absorción que mantiene al bebé seco hasta 12 horas. Ajuste cómodo y suave para la piel. Disponible en tallas 1 a 6.",
    category: "alimentos",
    subcategory: "aseo-personal",
    brand: "Pampers",
    countryOfOrigin: "Estados Unidos",
    price: 32.99,
    currency: "USD",
    thumbnail: IMG.panales,
    images: [img(IMG.panales, "Pañales Pampers Baby Dry")],
    variants: [
      { id: "v_p_t1", name: "Talla 1 (4-6 kg)", type: "size", priceModifier: 0, inStock: true },
      { id: "v_p_t2", name: "Talla 2 (5-8 kg)", type: "size", priceModifier: 0, inStock: true },
      { id: "v_p_t3", name: "Talla 3 (7-13 kg)", type: "size", priceModifier: 2, inStock: true },
      { id: "v_p_t4", name: "Talla 4 (10-17 kg)", type: "size", priceModifier: 4, inStock: true },
      { id: "v_p_t5", name: "Talla 5 (12+ kg)", type: "size", priceModifier: 5, inStock: true },
      { id: "v_p_t6", name: "Talla 6 (16+ kg)", type: "size", priceModifier: 6, inStock: false },
    ],
    specs: [
      { label: "Marca", value: "Pampers Baby Dry" },
      { label: "Cantidad", value: "~80-120 pañales según talla" },
      { label: "Protección", value: "Hasta 12 horas" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 4.5,
    tags: ["bebé", "pañales", "aseo"],
    rating: 4.9,
    reviewCount: 178,
    bestseller: true,
  },
  {
    id: "p_alim_079",
    slug: "papel-higienico-charmin",
    name: "Papel Higiénico Charmin (paquete x12)",
    description: "Pack de 12 rollos de papel higiénico Charmin Ultra Soft.",
    longDescription:
      "Pack de 12 rollos extra-grandes de papel higiénico Charmin Ultra Soft. Ultra suave, doble hoja. Cada rollo equivale a 4 rollos regulares.",
    category: "alimentos",
    subcategory: "aseo-personal",
    brand: "Charmin",
    countryOfOrigin: "Estados Unidos",
    price: 14.99,
    currency: "USD",
    thumbnail: IMG.papelHigienico,
    images: [img(IMG.papelHigienico, "Papel higiénico Charmin")],
    specs: [
      { label: "Cantidad", value: "12 rollos extra-grandes" },
      { label: "Tipo", value: "Ultra Soft doble hoja" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.8,
    tags: ["papel", "higiénico", "aseo"],
    rating: 4.8,
    reviewCount: 144,
    bestseller: true,
  },
  {
    id: "p_alim_080",
    slug: "cuchillas-gillette",
    name: "Cuchillas Gillette (10 unidades)",
    description: "Pack de 10 cartuchos Gillette Fusion5.",
    longDescription:
      "Pack de 10 cartuchos de repuesto Gillette Fusion5 con 5 hojas. Afeitado preciso y suave. Compatible con mango Gillette Fusion.",
    category: "alimentos",
    subcategory: "aseo-personal",
    brand: "Gillette",
    countryOfOrigin: "Estados Unidos",
    price: 18.99,
    currency: "USD",
    thumbnail: IMG.cuchillasGillette,
    images: [img(IMG.cuchillasGillette, "Cuchillas Gillette Fusion5")],
    specs: [
      { label: "Cantidad", value: "10 cartuchos" },
      { label: "Tipo", value: "Fusion5 (5 hojas)" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 0.3,
    tags: ["afeitado", "hombre", "aseo"],
    rating: 4.7,
    reviewCount: 62,
  },

  // ===========================================================
  // LIMPIEZA (10)
  // ===========================================================
  {
    id: "p_alim_081",
    slug: "detergente-tide",
    name: "Detergente Tide 5 lb",
    description: "Detergente en polvo Tide Original.",
    longDescription:
      "Detergente en polvo Tide Original, bolsa de 5 lb. Limpia profundamente, ideal para lavadora o a mano. Aroma fresco que dura.",
    category: "alimentos",
    subcategory: "limpieza",
    brand: "Tide",
    countryOfOrigin: "Estados Unidos",
    price: 14.99,
    currency: "USD",
    thumbnail: IMG.detergente,
    images: [img(IMG.detergente, "Detergente Tide")],
    specs: [
      { label: "Peso", value: "5 lb" },
      { label: "Tipo", value: "Polvo Original" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.27,
    tags: ["detergente", "limpieza", "ropa"],
    rating: 4.9,
    reviewCount: 152,
    bestseller: true,
  },
  {
    id: "p_alim_082",
    slug: "detergente-ariel",
    name: "Detergente Ariel 5 lb",
    description: "Detergente Ariel en polvo, alternativa popular.",
    longDescription:
      "Detergente en polvo Ariel, bolsa de 5 lb. Conocido en toda Latinoamérica por su poder de limpieza y aroma característico.",
    category: "alimentos",
    subcategory: "limpieza",
    brand: "Ariel",
    countryOfOrigin: "México",
    price: 13.99,
    currency: "USD",
    thumbnail: IMG.detergente,
    images: [img(IMG.detergente, "Detergente Ariel")],
    specs: [
      { label: "Peso", value: "5 lb" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.27,
    tags: ["detergente", "limpieza"],
    rating: 4.7,
    reviewCount: 89,
  },
  {
    id: "p_alim_083",
    slug: "cloro-clorox",
    name: "Cloro Clorox 1 galón",
    description: "Cloro líquido Clorox para desinfectar.",
    longDescription:
      "Galón de cloro Clorox concentrado, ideal para blanquear ropa, desinfectar superficies y pisos. Botella de 1 galón (3.78 L).",
    category: "alimentos",
    subcategory: "limpieza",
    brand: "Clorox",
    countryOfOrigin: "Estados Unidos",
    price: 7.99,
    currency: "USD",
    thumbnail: IMG.cloro,
    images: [img(IMG.cloro, "Cloro Clorox")],
    specs: [
      { label: "Volumen", value: "1 galón (3.78 L)" },
      { label: "Tipo", value: "Concentrado" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 4.0,
    tags: ["cloro", "limpieza", "desinfectante"],
    rating: 4.7,
    reviewCount: 67,
  },
  {
    id: "p_alim_084",
    slug: "jabon-fregar-dawn",
    name: "Jabón de Fregar Dawn",
    description: "Jabón líquido Dawn Ultra para platos.",
    longDescription:
      "Botella de jabón líquido Dawn Ultra Original, 28 oz. Corta la grasa al instante, rinde el doble que las marcas regulares.",
    category: "alimentos",
    subcategory: "limpieza",
    brand: "Dawn",
    countryOfOrigin: "Estados Unidos",
    price: 5.99,
    currency: "USD",
    thumbnail: IMG.jabonFregar,
    images: [img(IMG.jabonFregar, "Jabón Dawn")],
    specs: [
      { label: "Volumen", value: "28 oz" },
      { label: "Tipo", value: "Ultra Original" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 0.9,
    tags: ["jabón", "platos", "limpieza"],
    rating: 4.8,
    reviewCount: 92,
  },
  {
    id: "p_alim_085",
    slug: "esponjas-multiuso",
    name: "Esponjas Multiuso (paquete x10)",
    description: "Pack de 10 esponjas multiuso Scotch-Brite.",
    longDescription:
      "Pack de 10 esponjas Scotch-Brite con un lado abrasivo y otro suave. Para platos, sartenes y superficies.",
    category: "alimentos",
    subcategory: "limpieza",
    brand: "Scotch-Brite",
    countryOfOrigin: "Estados Unidos",
    price: 7.99,
    currency: "USD",
    thumbnail: IMG.esponjas,
    images: [img(IMG.esponjas, "Esponjas Scotch-Brite")],
    specs: [
      { label: "Cantidad", value: "10 esponjas" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 0.4,
    tags: ["esponjas", "limpieza"],
    rating: 4.6,
    reviewCount: 34,
  },
  {
    id: "p_alim_086",
    slug: "escoba-recogedor",
    name: "Escoba con Recogedor",
    description: "Set de escoba y recogedor económico.",
    longDescription:
      "Set práctico de escoba con recogedor con mango largo. Cerdas resistentes, recogedor con borde de goma. Para pisos interiores.",
    category: "alimentos",
    subcategory: "limpieza",
    brand: "O-Cedar",
    countryOfOrigin: "Estados Unidos",
    price: 11.99,
    currency: "USD",
    thumbnail: IMG.escoba,
    images: [img(IMG.escoba, "Escoba con recogedor")],
    specs: [
      { label: "Material", value: "Plástico + cerdas sintéticas" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.2,
    tags: ["escoba", "limpieza", "hogar"],
    rating: 4.5,
    reviewCount: 28,
  },
  {
    id: "p_alim_087",
    slug: "trapeador-cubeta",
    name: "Trapeador con Cubeta",
    description: "Set de trapeador con cubeta exprimidora.",
    longDescription:
      "Set completo de trapeador con cubeta y exprimidor manual. Reemplazo de cabezal incluido. Cubeta resistente con asa.",
    category: "alimentos",
    subcategory: "limpieza",
    brand: "O-Cedar",
    countryOfOrigin: "Estados Unidos",
    price: 19.99,
    currency: "USD",
    thumbnail: IMG.trapeador,
    images: [img(IMG.trapeador, "Trapeador con cubeta")],
    specs: [
      { label: "Incluye", value: "Trapeador, cubeta, exprimidor, cabezal extra" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 2.5,
    tags: ["trapeador", "limpieza", "hogar"],
    rating: 4.6,
    reviewCount: 41,
  },
  {
    id: "p_alim_088",
    slug: "ambientador-spray",
    name: "Ambientador Spray (3 unidades)",
    description: "Pack de 3 ambientadores Glade aromáticos.",
    longDescription:
      "Pack de 3 ambientadores Glade en spray con aromas surtidos: floral, frescura limpia y vainilla. Cada uno 8 oz.",
    category: "alimentos",
    subcategory: "limpieza",
    brand: "Glade",
    countryOfOrigin: "Estados Unidos",
    price: 9.99,
    currency: "USD",
    thumbnail: IMG.ambientador,
    images: [img(IMG.ambientador, "Ambientadores Glade")],
    specs: [
      { label: "Cantidad", value: "3 latas de 8 oz" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 0.9,
    tags: ["ambientador", "limpieza", "aroma"],
    rating: 4.5,
    reviewCount: 24,
  },
  {
    id: "p_alim_089",
    slug: "papel-cocina",
    name: "Papel de Cocina (paquete x6)",
    description: "Pack de 6 rollos de papel de cocina Bounty.",
    longDescription:
      "Pack de 6 rollos doble-grandes de papel de cocina Bounty Select-A-Size. Súper absorbente, doble hoja.",
    category: "alimentos",
    subcategory: "limpieza",
    brand: "Bounty",
    countryOfOrigin: "Estados Unidos",
    price: 11.99,
    currency: "USD",
    thumbnail: IMG.papelCocina,
    images: [img(IMG.papelCocina, "Papel de cocina Bounty")],
    specs: [
      { label: "Cantidad", value: "6 rollos doble-grandes" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.6,
    tags: ["papel", "cocina", "limpieza"],
    rating: 4.7,
    reviewCount: 56,
  },
  {
    id: "p_alim_090",
    slug: "bolsas-basura",
    name: "Bolsas de Basura (caja x100)",
    description: "Caja de 100 bolsas de basura resistentes.",
    longDescription:
      "Caja de 100 bolsas de basura Hefty Strong de 13 galones. Plástico resistente con cierre tipo flex. Ideal para cocina.",
    category: "alimentos",
    subcategory: "limpieza",
    brand: "Hefty",
    countryOfOrigin: "Estados Unidos",
    price: 14.99,
    currency: "USD",
    thumbnail: IMG.bolsasBasura,
    images: [img(IMG.bolsasBasura, "Bolsas de basura Hefty")],
    specs: [
      { label: "Cantidad", value: "100 bolsas" },
      { label: "Capacidad", value: "13 galones" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.8,
    tags: ["bolsas", "basura", "limpieza"],
    rating: 4.7,
    reviewCount: 38,
  },
];
