import type { Product } from "@/types";

const IMG = {
  ecoflowDelta: "https://images.unsplash.com/photo-1620677368158-32b078c1c000?w=800",
  ecoflowRiver: "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=800",
  ecoflowPro: "https://images.unsplash.com/photo-1620677368158-32b078c1c000?w=800",
  panelSolar: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800",
  panelSolar400: "https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800",
  generador: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=800",
  powerBank: "https://images.unsplash.com/photo-1609592424823-7d6e6e1a4f5b?w=800",
  lampara: "https://images.unsplash.com/photo-1565183997392-2f6f122e5912?w=800",
  refrigerador: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=800",
  refrigeradorSamsung: "https://images.unsplash.com/photo-1601599561213-832382fd07ba?w=800",
  refrigeradorMabe: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=800",
  nevera: "https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=800",
  congelador: "https://images.unsplash.com/photo-1604335078902-94d7b1f02f6e?w=800",
  refrigeradorSolar: "https://images.unsplash.com/photo-1592833167001-55ddf86b65cd?w=800",
  cocinaInduccion: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800",
  cocinaElectrica: "https://images.unsplash.com/photo-1556909195-d85075a0a96d?w=800",
  cocinaGas: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=800",
  microondas: "https://images.unsplash.com/photo-1574269910231-bc508bcb43e8?w=800",
  instantPot: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800",
  arrocera: "https://images.unsplash.com/photo-1622445275576-721325763afe?w=800",
  sandwichera: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800",
  tostadora: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=800",
  aireSplit: "https://images.unsplash.com/photo-1631545806609-a09e4b16d7d6?w=800",
  aireVentana: "https://images.unsplash.com/photo-1631545806609-a09e4b16d7d6?w=800",
  ventiladorPie: "https://images.unsplash.com/photo-1631545806609-a09e4b16d7d6?w=800",
  ventiladorMesa: "https://images.unsplash.com/photo-1565025474196-25e60dba4d63?w=800",
  ventiladorTecho: "https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=800",
  climatizador: "https://images.unsplash.com/photo-1631545806609-a09e4b16d7d6?w=800",
  licuadora: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800",
  batidora: "https://images.unsplash.com/photo-1593618998160-e34014e67546?w=800",
  plancha: "https://images.unsplash.com/photo-1564024209568-46d1f7d3d3a9?w=800",
  cafetera: "https://images.unsplash.com/photo-1580915411954-282cb1b0d780?w=800",
  procesadora: "https://images.unsplash.com/photo-1574269910231-bc508bcb43e8?w=800",
  hervidora: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800",
  aspiradora: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800",
  lavadora: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=800",
} as const;

const img = (url: string, alt: string) => ({ url, alt, width: 800, height: 800 });

export const electrodomesticos: Product[] = [
  // ===========================================================
  // ENERGÍA (8) ⭐ Sección clave
  // ===========================================================
  {
    id: "p_elec_001",
    slug: "ecoflow-delta-1300",
    name: "EcoFlow Delta 1300 — Estación de Energía Portátil",
    description: "La solución definitiva para los apagones. 1260 Wh, carga rápida y silenciosa.",
    longDescription:
      "EcoFlow Delta 1300 es una estación de energía portátil con 1260 Wh de capacidad, suficiente para alimentar refrigerador, ventilador, lámparas, TV y cargar todos los dispositivos durante horas. Carga al 80% en solo 1 hora. 6 salidas AC + USB + USB-C. Ideal para enfrentar los apagones prolongados de Matanzas. Garantía de 2 años.",
    category: "electrodomesticos",
    subcategory: "energia",
    brand: "EcoFlow",
    countryOfOrigin: "China",
    price: 1099,
    comparePrice: 1299,
    currency: "USD",
    thumbnail: IMG.ecoflowDelta,
    images: [img(IMG.ecoflowDelta, "EcoFlow Delta 1300")],
    specs: [
      { label: "Capacidad", value: "1260 Wh", group: "Eléctrico" },
      { label: "Salida AC", value: "1800W (3300W surge)", group: "Eléctrico" },
      { label: "Salidas", value: "6 AC + 2 USB-C + 4 USB-A", group: "Conectividad" },
      { label: "Tiempo de carga", value: "0-80% en 1 hora", group: "Carga" },
      { label: "Peso", value: "14 kg", group: "Físico" },
      { label: "Garantía", value: "2 años", group: "Servicio" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "7-10 días",
    shippingType: "express",
    weight: 14,
    tags: ["energía", "apagón", "EcoFlow", "premium", "imprescindible"],
    rating: 4.9,
    reviewCount: 87,
    bestseller: true,
    featured: true,
  },
  {
    id: "p_elec_022",
    slug: "ecoflow-river-2",
    name: "EcoFlow River 2 (288 Wh)",
    description: "Estación portátil compacta para emergencias y viajes.",
    longDescription:
      "EcoFlow River 2 con 288 Wh — la versión compacta y portátil. Ideal para apagones cortos, camping o como complemento. Carga rápida en 60 minutos. 5 salidas AC + USB. Pesa solo 3.5 kg.",
    category: "electrodomesticos",
    subcategory: "energia",
    brand: "EcoFlow",
    countryOfOrigin: "China",
    price: 349,
    comparePrice: 429,
    currency: "USD",
    thumbnail: IMG.ecoflowRiver,
    images: [img(IMG.ecoflowRiver, "EcoFlow River 2")],
    specs: [
      { label: "Capacidad", value: "288 Wh", group: "Eléctrico" },
      { label: "Salida AC", value: "300W (600W surge)", group: "Eléctrico" },
      { label: "Tiempo de carga", value: "0-100% en 60 min", group: "Carga" },
      { label: "Peso", value: "3.5 kg", group: "Físico" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "7-10 días",
    shippingType: "express",
    weight: 3.5,
    tags: ["energía", "portátil", "EcoFlow"],
    rating: 4.7,
    reviewCount: 54,
    featured: true,
  },
  {
    id: "p_elec_023",
    slug: "ecoflow-delta-pro",
    name: "EcoFlow Delta Pro 3.6 kWh",
    description: "Estación profesional. Para casa entera durante apagones largos.",
    longDescription:
      "EcoFlow Delta Pro 3.6 kWh — la estación más potente de la familia EcoFlow. Capacidad expandible hasta 25 kWh con baterías extras. Salida 3600W AC. Alimenta una casa entera durante horas. Garantía 5 años.",
    category: "electrodomesticos",
    subcategory: "energia",
    brand: "EcoFlow",
    countryOfOrigin: "China",
    price: 2890,
    comparePrice: 3299,
    currency: "USD",
    thumbnail: IMG.ecoflowPro,
    images: [img(IMG.ecoflowPro, "EcoFlow Delta Pro")],
    specs: [
      { label: "Capacidad", value: "3.6 kWh", group: "Eléctrico" },
      { label: "Salida AC", value: "3600W (7200W surge)", group: "Eléctrico" },
      { label: "Expandible", value: "Hasta 25 kWh", group: "Eléctrico" },
      { label: "Garantía", value: "5 años", group: "Servicio" },
    ],
    inStock: true,
    stockLevel: "low",
    estimatedDelivery: "10-14 días",
    shippingType: "express",
    weight: 45,
    tags: ["energía", "profesional", "EcoFlow", "premium"],
    rating: 4.9,
    reviewCount: 31,
  },
  {
    id: "p_elec_024",
    slug: "panel-solar-200w",
    name: "Panel Solar 200W",
    description: "Panel solar plegable 200W, perfecto para EcoFlow River.",
    longDescription:
      "Panel solar monocristalino plegable de 200W. Ideal para cargar EcoFlow River 2 o Delta 1300 con energía solar gratuita. Resistente al agua IP68. Cables y adaptadores incluidos.",
    category: "electrodomesticos",
    subcategory: "energia",
    brand: "EcoFlow",
    countryOfOrigin: "China",
    price: 249,
    currency: "USD",
    thumbnail: IMG.panelSolar,
    images: [img(IMG.panelSolar, "Panel solar 200W")],
    specs: [
      { label: "Potencia", value: "200W" },
      { label: "Tipo", value: "Monocristalino plegable" },
      { label: "Resistencia", value: "IP68" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "7-10 días",
    shippingType: "express",
    weight: 8,
    tags: ["solar", "energía", "panel"],
    rating: 4.7,
    reviewCount: 42,
  },
  {
    id: "p_elec_025",
    slug: "panel-solar-400w",
    name: "Panel Solar 400W",
    description: "Panel solar 400W para máxima autonomía energética.",
    longDescription:
      "Panel solar monocristalino premium de 400W. Para usuarios que quieren máxima generación. Ideal para combinar con EcoFlow Delta Pro y vivir 100% solar. Estructura de aluminio reforzada.",
    category: "electrodomesticos",
    subcategory: "energia",
    brand: "EcoFlow",
    countryOfOrigin: "China",
    price: 429,
    comparePrice: 499,
    currency: "USD",
    thumbnail: IMG.panelSolar400,
    images: [img(IMG.panelSolar400, "Panel solar 400W")],
    specs: [
      { label: "Potencia", value: "400W" },
      { label: "Tipo", value: "Monocristalino" },
      { label: "Estructura", value: "Aluminio reforzado" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "7-10 días",
    shippingType: "express",
    weight: 16,
    tags: ["solar", "energía", "premium"],
    rating: 4.8,
    reviewCount: 28,
    featured: true,
  },
  {
    id: "p_elec_026",
    slug: "generador-inverter-2200w",
    name: "Generador Inverter 2200W",
    description: "Generador de gasolina silencioso 2200W.",
    longDescription:
      "Generador inverter de 2200W con motor de gasolina, tecnología invertida que produce energía estable para electrónicos sensibles. 8 horas de autonomía con 1 galón. Más silencioso que los generadores tradicionales.",
    category: "electrodomesticos",
    subcategory: "energia",
    brand: "Honda",
    countryOfOrigin: "Japón",
    price: 890,
    currency: "USD",
    thumbnail: IMG.generador,
    images: [img(IMG.generador, "Generador inverter")],
    specs: [
      { label: "Potencia", value: "2200W" },
      { label: "Tipo", value: "Inverter (energía estable)" },
      { label: "Autonomía", value: "8 horas con 1 galón" },
      { label: "Combustible", value: "Gasolina" },
    ],
    inStock: true,
    stockLevel: "low",
    estimatedDelivery: "10-14 días",
    shippingType: "maritime",
    weight: 22,
    tags: ["generador", "energía", "gasolina"],
    rating: 4.8,
    reviewCount: 36,
  },
  {
    id: "p_elec_027",
    slug: "power-bank-30000",
    name: "Power Bank 30,000 mAh",
    description: "Power bank de alta capacidad, carga 8 veces un celular.",
    longDescription:
      "Power bank Anker PowerCore 30,000 mAh — capacidad para cargar un celular hasta 8 veces. 3 puertos USB-A + 1 USB-C con Power Delivery. Pantalla LED indicadora.",
    category: "electrodomesticos",
    subcategory: "energia",
    brand: "Anker",
    countryOfOrigin: "China",
    price: 59.99,
    currency: "USD",
    thumbnail: IMG.powerBank,
    images: [img(IMG.powerBank, "Power Bank 30000mAh")],
    specs: [
      { label: "Capacidad", value: "30,000 mAh" },
      { label: "Salidas", value: "3 USB-A + 1 USB-C PD" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 0.6,
    tags: ["power bank", "carga", "portátil"],
    rating: 4.8,
    reviewCount: 124,
    bestseller: true,
  },
  {
    id: "p_elec_028",
    slug: "lampara-led-solar",
    name: "Lámpara LED Recargable Solar",
    description: "Lámpara LED con panel solar, ideal para apagones.",
    longDescription:
      "Lámpara LED recargable con panel solar integrado. Hasta 12 horas de iluminación. 3 modos: alta, media, SOS. Resistente al agua IPX4. Imprescindible para los apagones.",
    category: "electrodomesticos",
    subcategory: "energia",
    brand: "BioLite",
    countryOfOrigin: "China",
    price: 24.99,
    currency: "USD",
    thumbnail: IMG.lampara,
    images: [img(IMG.lampara, "Lámpara LED solar")],
    specs: [
      { label: "Iluminación", value: "Hasta 12 horas" },
      { label: "Modos", value: "Alta, media, SOS" },
      { label: "Carga", value: "Solar + USB" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 0.5,
    tags: ["lámpara", "LED", "solar", "apagón"],
    rating: 4.7,
    reviewCount: 89,
    bestseller: true,
  },

  // ===========================================================
  // REFRIGERACIÓN (6)
  // ===========================================================
  {
    id: "p_elec_002",
    slug: "refrigerador-royal-250l",
    name: "Refrigerador Royal 250L",
    description: "Refrigerador de 250L, dos puertas, eficiente energéticamente.",
    longDescription:
      "Refrigerador Royal de 250 litros con dos puertas (refrigerador y freezer separados). Eficiencia energética A+. Iluminación LED interior. Estantes ajustables. Diseño compacto perfecto para apartamentos.",
    category: "electrodomesticos",
    subcategory: "refrigeracion",
    brand: "Royal",
    countryOfOrigin: "China",
    price: 580,
    currency: "USD",
    thumbnail: IMG.refrigerador,
    images: [img(IMG.refrigerador, "Refrigerador Royal 250L")],
    specs: [
      { label: "Capacidad", value: "250 L" },
      { label: "Puertas", value: "2 (refrigerador + freezer)" },
      { label: "Eficiencia", value: "A+" },
      { label: "Garantía", value: "1 año" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "3-5 semanas",
    shippingType: "maritime",
    weight: 65,
    tags: ["refrigerador", "Royal", "compacto"],
    rating: 4.5,
    reviewCount: 42,
  },
  {
    id: "p_elec_003",
    slug: "refrigerador-mabe-350l",
    name: "Refrigerador Mabe 350L",
    description: "Refrigerador Mabe 350L, marca confiable y reconocida en Cuba.",
    longDescription:
      "Refrigerador Mabe de 350 litros, dos puertas, sistema No-Frost. Marca emblemática que muchas familias cubanas conocen. Iluminación LED, estantes de cristal templado, gavetas para frutas y vegetales.",
    category: "electrodomesticos",
    subcategory: "refrigeracion",
    brand: "Mabe",
    countryOfOrigin: "México",
    price: 890,
    comparePrice: 1050,
    currency: "USD",
    thumbnail: IMG.refrigeradorMabe,
    images: [img(IMG.refrigeradorMabe, "Refrigerador Mabe 350L")],
    specs: [
      { label: "Capacidad", value: "350 L" },
      { label: "Sistema", value: "No-Frost" },
      { label: "Puertas", value: "2" },
      { label: "Garantía", value: "2 años" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "3-5 semanas",
    shippingType: "maritime",
    weight: 78,
    tags: ["refrigerador", "Mabe", "familiar"],
    rating: 4.8,
    reviewCount: 76,
    bestseller: true,
    featured: true,
  },
  {
    id: "p_elec_004",
    slug: "refrigerador-samsung-450l",
    name: "Refrigerador Samsung 450L No-Frost",
    description: "Refrigerador Samsung 450L premium, tecnología Twin Cooling.",
    longDescription:
      "Refrigerador Samsung de 450 litros con tecnología Twin Cooling Plus para mantener humedad y frescura óptimas en frutas y vegetales. No-Frost, dispensador de hielo, panel digital. Inverter compresor con 10 años de garantía.",
    category: "electrodomesticos",
    subcategory: "refrigeracion",
    brand: "Samsung",
    countryOfOrigin: "Corea del Sur",
    price: 1290,
    currency: "USD",
    thumbnail: IMG.refrigeradorSamsung,
    images: [img(IMG.refrigeradorSamsung, "Refrigerador Samsung 450L")],
    specs: [
      { label: "Capacidad", value: "450 L" },
      { label: "Tecnología", value: "Twin Cooling Plus" },
      { label: "Sistema", value: "No-Frost + Inverter" },
      { label: "Garantía compresor", value: "10 años" },
    ],
    inStock: true,
    stockLevel: "low",
    estimatedDelivery: "3-5 semanas",
    shippingType: "maritime",
    weight: 92,
    tags: ["refrigerador", "Samsung", "premium"],
    rating: 4.9,
    reviewCount: 38,
  },
  {
    id: "p_elec_005",
    slug: "nevera-compacta-90l",
    name: "Nevera Compacta 90L",
    description: "Nevera compacta de 90L, perfecta para cuartos pequeños.",
    longDescription:
      "Nevera compacta de 90L, ideal para cuartos pequeños, oficinas o como nevera secundaria. Bajo consumo eléctrico. Termostato ajustable. Llega con dos repisas y un pequeño congelador interno.",
    category: "electrodomesticos",
    subcategory: "refrigeracion",
    brand: "Frigidaire",
    countryOfOrigin: "México",
    price: 320,
    currency: "USD",
    thumbnail: IMG.nevera,
    images: [img(IMG.nevera, "Nevera compacta")],
    specs: [
      { label: "Capacidad", value: "90 L" },
      { label: "Congelador", value: "Pequeño interno" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "3-5 semanas",
    shippingType: "maritime",
    weight: 32,
    tags: ["nevera", "compacta", "económica"],
    rating: 4.5,
    reviewCount: 22,
  },
  {
    id: "p_elec_006",
    slug: "congelador-horizontal-200l",
    name: "Congelador Horizontal 200L",
    description: "Congelador horizontal 200L, ideal para guardar carnes en cantidad.",
    longDescription:
      "Congelador horizontal (chest freezer) de 200 litros. Perfecto para almacenar carnes, helados y alimentos congelados en cantidad. Cierre hermético, luz interna, drenaje fácil.",
    category: "electrodomesticos",
    subcategory: "refrigeracion",
    brand: "Whirlpool",
    countryOfOrigin: "México",
    price: 620,
    currency: "USD",
    thumbnail: IMG.congelador,
    images: [img(IMG.congelador, "Congelador horizontal")],
    specs: [
      { label: "Capacidad", value: "200 L" },
      { label: "Tipo", value: "Horizontal (chest)" },
      { label: "Drenaje", value: "Sí" },
    ],
    inStock: true,
    stockLevel: "low",
    estimatedDelivery: "3-5 semanas",
    shippingType: "maritime",
    weight: 48,
    tags: ["congelador", "freezer", "almacenaje"],
    rating: 4.7,
    reviewCount: 34,
  },
  {
    id: "p_elec_007",
    slug: "refrigerador-solar-12v",
    name: "Refrigerador Solar 12V 180L",
    description: "Refrigerador 12V que funciona directo con paneles solares.",
    longDescription:
      "Refrigerador solar de 12V/24V con compresor inverter, conexión directa a paneles solares (sin necesidad de inversor AC). 180 litros, ultra-eficiente. Perfecto para zonas con apagones largos.",
    category: "electrodomesticos",
    subcategory: "refrigeracion",
    brand: "Smad",
    countryOfOrigin: "China",
    price: 1150,
    currency: "USD",
    thumbnail: IMG.refrigeradorSolar,
    images: [img(IMG.refrigeradorSolar, "Refrigerador solar 12V")],
    specs: [
      { label: "Capacidad", value: "180 L" },
      { label: "Voltaje", value: "12V/24V DC + AC" },
      { label: "Consumo", value: "Ultra eficiente" },
    ],
    inStock: true,
    stockLevel: "low",
    estimatedDelivery: "3-5 semanas",
    shippingType: "maritime",
    weight: 56,
    tags: ["refrigerador", "solar", "apagón"],
    rating: 4.7,
    reviewCount: 18,
    featured: true,
  },

  // ===========================================================
  // COCINA (8)
  // ===========================================================
  {
    id: "p_elec_008",
    slug: "cocina-induccion-2",
    name: "Cocina de Inducción 2 Hornillas",
    description: "Cocina de inducción 2 hornillas, ahorro de energía.",
    longDescription:
      "Cocina de inducción 2 hornillas, calienta solo el recipiente — ahorro energético y seguridad (no calienta la superficie). 2000W total. Panel táctil con temporizador.",
    category: "electrodomesticos",
    subcategory: "cocina",
    brand: "Nuwave",
    countryOfOrigin: "China",
    price: 189,
    currency: "USD",
    thumbnail: IMG.cocinaInduccion,
    images: [img(IMG.cocinaInduccion, "Cocina de inducción")],
    specs: [
      { label: "Hornillas", value: "2" },
      { label: "Potencia", value: "2000W total" },
      { label: "Tipo", value: "Inducción" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "7-10 días",
    shippingType: "express",
    weight: 6,
    tags: ["cocina", "inducción", "ahorro"],
    rating: 4.7,
    reviewCount: 67,
    bestseller: true,
  },
  {
    id: "p_elec_009",
    slug: "cocina-electrica-4",
    name: "Cocina Eléctrica 4 Hornillas",
    description: "Cocina eléctrica de mesa, 4 hornillas.",
    longDescription:
      "Cocina eléctrica de mesa con 4 hornillas, ideal para apartamentos. 4400W total con controles individuales. Quemadores espirales que se calientan rápido.",
    category: "electrodomesticos",
    subcategory: "cocina",
    brand: "Whirlpool",
    countryOfOrigin: "México",
    price: 290,
    currency: "USD",
    thumbnail: IMG.cocinaElectrica,
    images: [img(IMG.cocinaElectrica, "Cocina eléctrica 4 hornillas")],
    specs: [
      { label: "Hornillas", value: "4" },
      { label: "Potencia", value: "4400W total" },
      { label: "Tipo", value: "Eléctrica espiral" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "10-14 días",
    shippingType: "express",
    weight: 18,
    tags: ["cocina", "eléctrica", "4-hornillas"],
    rating: 4.6,
    reviewCount: 38,
  },
  {
    id: "p_elec_010",
    slug: "cocina-gas-4",
    name: "Cocina de Gas 4 Hornillas",
    description: "Cocina de gas 4 hornillas con horno integrado.",
    longDescription:
      "Cocina de gas con 4 hornillas y horno integrado de 60L. Encendido eléctrico, válvulas de seguridad. Funciona con gas LP. Acabado en acero inoxidable.",
    category: "electrodomesticos",
    subcategory: "cocina",
    brand: "Mabe",
    countryOfOrigin: "México",
    price: 349,
    currency: "USD",
    thumbnail: IMG.cocinaGas,
    images: [img(IMG.cocinaGas, "Cocina de gas con horno")],
    specs: [
      { label: "Hornillas", value: "4" },
      { label: "Horno", value: "60 L integrado" },
      { label: "Combustible", value: "Gas LP" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "3-5 semanas",
    shippingType: "maritime",
    weight: 35,
    tags: ["cocina", "gas", "horno"],
    rating: 4.7,
    reviewCount: 52,
  },
  {
    id: "p_elec_011",
    slug: "microondas-panasonic",
    name: "Microondas Panasonic 0.7 cu ft",
    description: "Microondas compacto Panasonic 0.7 cu ft.",
    longDescription:
      "Microondas compacto Panasonic 700W, 0.7 pies cúbicos. Tecnología inverter para calor parejo. 10 niveles de potencia, sensor de cocción y temporizador. Compacto, perfecto para cualquier cocina.",
    category: "electrodomesticos",
    subcategory: "cocina",
    brand: "Panasonic",
    countryOfOrigin: "Japón",
    price: 129,
    currency: "USD",
    thumbnail: IMG.microondas,
    images: [img(IMG.microondas, "Microondas Panasonic")],
    specs: [
      { label: "Capacidad", value: "0.7 cu ft" },
      { label: "Potencia", value: "700W" },
      { label: "Tecnología", value: "Inverter" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "7-10 días",
    shippingType: "express",
    weight: 11,
    tags: ["microondas", "Panasonic"],
    rating: 4.7,
    reviewCount: 92,
    bestseller: true,
  },
  {
    id: "p_elec_012",
    slug: "instant-pot",
    name: "Olla Presión Eléctrica Instant Pot 6Q",
    description: "Olla Instant Pot 7-en-1, 6 cuartos.",
    longDescription:
      "Instant Pot Duo 6 cuartos, olla multifuncional 7-en-1: olla a presión, lenta, arrocera, vaporera, salteadora, yogurtera y calentador. La olla más vendida del mundo. Cocina rápido y sano.",
    category: "electrodomesticos",
    subcategory: "cocina",
    brand: "Instant Pot",
    countryOfOrigin: "China",
    price: 119,
    currency: "USD",
    thumbnail: IMG.instantPot,
    images: [img(IMG.instantPot, "Instant Pot 6Q")],
    specs: [
      { label: "Capacidad", value: "6 cuartos" },
      { label: "Funciones", value: "7-en-1" },
      { label: "Potencia", value: "1000W" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "7-10 días",
    shippingType: "express",
    weight: 5,
    tags: ["olla", "presión", "Instant Pot"],
    rating: 4.9,
    reviewCount: 156,
    bestseller: true,
    featured: true,
  },
  {
    id: "p_elec_013",
    slug: "olla-arrocera-aroma",
    name: "Olla Arrocera Aroma 8 Tazas",
    description: "Arrocera Aroma 8 tazas, también vaporera.",
    longDescription:
      "Olla arrocera Aroma de 8 tazas con función vaporera. Arroz perfecto cada vez con un solo botón. Mantiene calor automático. Bandeja vaporera incluida.",
    category: "electrodomesticos",
    subcategory: "cocina",
    brand: "Aroma",
    countryOfOrigin: "China",
    price: 59,
    currency: "USD",
    thumbnail: IMG.arrocera,
    images: [img(IMG.arrocera, "Olla arrocera Aroma")],
    specs: [
      { label: "Capacidad", value: "8 tazas" },
      { label: "Función extra", value: "Vaporera" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 2.5,
    tags: ["arrocera", "olla"],
    rating: 4.7,
    reviewCount: 73,
  },
  {
    id: "p_elec_014",
    slug: "sandwichera",
    name: "Sandwichera/Plancha",
    description: "Sandwichera eléctrica con plancha, antiadherente.",
    longDescription:
      "Sandwichera eléctrica 750W con placas antiadherentes intercambiables (sándwich y plancha). Listo en 5 minutos. Indicador de calor LED.",
    category: "electrodomesticos",
    subcategory: "cocina",
    brand: "Hamilton Beach",
    countryOfOrigin: "China",
    price: 39.99,
    currency: "USD",
    thumbnail: IMG.sandwichera,
    images: [img(IMG.sandwichera, "Sandwichera")],
    specs: [
      { label: "Potencia", value: "750W" },
      { label: "Placas", value: "Sándwich + Plancha" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.8,
    tags: ["sandwichera", "plancha"],
    rating: 4.5,
    reviewCount: 28,
  },
  {
    id: "p_elec_015",
    slug: "tostadora-2-slice",
    name: "Tostadora 2 Slices",
    description: "Tostadora compacta 2 ranuras, controles simples.",
    longDescription:
      "Tostadora compacta de 2 ranuras anchas con 6 niveles de tueste, función bagel y descongelar. Bandeja recolectora removible.",
    category: "electrodomesticos",
    subcategory: "cocina",
    brand: "Black+Decker",
    countryOfOrigin: "China",
    price: 34.99,
    currency: "USD",
    thumbnail: IMG.tostadora,
    images: [img(IMG.tostadora, "Tostadora")],
    specs: [
      { label: "Capacidad", value: "2 slices" },
      { label: "Niveles", value: "6 de tueste" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.5,
    tags: ["tostadora", "desayuno"],
    rating: 4.5,
    reviewCount: 22,
  },

  // ===========================================================
  // CLIMATIZACIÓN (6)
  // ===========================================================
  {
    id: "p_elec_016",
    slug: "aire-split-12000",
    name: "Aire Acondicionado Split 12,000 BTU",
    description: "AC split 12,000 BTU inverter, eficiente.",
    longDescription:
      "Aire acondicionado split inverter de 12,000 BTU, ideal para habitaciones de hasta 25 m². Tecnología inverter ahorra hasta 60% en electricidad. Modo frío/caliente, control remoto, modo silencioso.",
    category: "electrodomesticos",
    subcategory: "climatizacion",
    brand: "LG",
    countryOfOrigin: "Corea del Sur",
    price: 590,
    currency: "USD",
    thumbnail: IMG.aireSplit,
    images: [img(IMG.aireSplit, "Aire acondicionado split")],
    specs: [
      { label: "Capacidad", value: "12,000 BTU" },
      { label: "Tecnología", value: "Inverter" },
      { label: "Cobertura", value: "Hasta 25 m²" },
      { label: "Modos", value: "Frío + Caliente" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "3-5 semanas",
    shippingType: "maritime",
    weight: 38,
    tags: ["aire", "split", "inverter"],
    rating: 4.8,
    reviewCount: 56,
    bestseller: true,
  },
  {
    id: "p_elec_017",
    slug: "aire-ventana-8000",
    name: "Aire Acondicionado Ventana 8,000 BTU",
    description: "AC de ventana 8,000 BTU, instalación simple.",
    longDescription:
      "Aire acondicionado de ventana 8,000 BTU, ideal para habitaciones pequeñas (hasta 18 m²). Instalación más simple que un split. Control remoto incluido.",
    category: "electrodomesticos",
    subcategory: "climatizacion",
    brand: "Frigidaire",
    countryOfOrigin: "México",
    price: 390,
    currency: "USD",
    thumbnail: IMG.aireVentana,
    images: [img(IMG.aireVentana, "Aire acondicionado de ventana")],
    specs: [
      { label: "Capacidad", value: "8,000 BTU" },
      { label: "Cobertura", value: "Hasta 18 m²" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "3-5 semanas",
    shippingType: "maritime",
    weight: 28,
    tags: ["aire", "ventana", "frío"],
    rating: 4.6,
    reviewCount: 41,
  },
  {
    id: "p_elec_018",
    slug: "ventilador-pie-18",
    name: 'Ventilador de Pie 18"',
    description: 'Ventilador de pie 18", oscilación 90°.',
    longDescription:
      'Ventilador de pie de 18" con oscilación de 90°, 3 velocidades, altura ajustable. Aspas reforzadas, motor silencioso. Ideal para apartamentos en clima caluroso.',
    category: "electrodomesticos",
    subcategory: "climatizacion",
    brand: "Honeywell",
    countryOfOrigin: "China",
    price: 69.99,
    currency: "USD",
    thumbnail: IMG.ventiladorPie,
    images: [img(IMG.ventiladorPie, "Ventilador de pie")],
    specs: [
      { label: "Tamaño", value: '18"' },
      { label: "Oscilación", value: "90°" },
      { label: "Velocidades", value: "3" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "10-14 días",
    shippingType: "express",
    weight: 6,
    tags: ["ventilador", "climatización"],
    rating: 4.6,
    reviewCount: 67,
    bestseller: true,
  },
  {
    id: "p_elec_019",
    slug: "ventilador-mesa-usb",
    name: "Ventilador de Mesa USB Recargable",
    description: "Ventilador USB recargable, perfecto para apagones.",
    longDescription:
      "Ventilador de mesa portátil con batería recargable USB. 3 velocidades, oscilación, hasta 8 horas de autonomía. Imprescindible para los apagones — silencioso, no consume.",
    category: "electrodomesticos",
    subcategory: "climatizacion",
    brand: "OPOLAR",
    countryOfOrigin: "China",
    price: 39.99,
    currency: "USD",
    thumbnail: IMG.ventiladorMesa,
    images: [img(IMG.ventiladorMesa, "Ventilador USB")],
    specs: [
      { label: "Tipo", value: "Recargable USB" },
      { label: "Autonomía", value: "Hasta 8 horas" },
      { label: "Velocidades", value: "3" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.2,
    tags: ["ventilador", "USB", "apagón"],
    rating: 4.7,
    reviewCount: 134,
    bestseller: true,
    featured: true,
  },
  {
    id: "p_elec_020",
    slug: "ventilador-techo-52",
    name: 'Ventilador de Techo 52"',
    description: 'Ventilador de techo 52" con luz LED integrada.',
    longDescription:
      'Ventilador de techo de 52" con 5 aspas y luz LED integrada (18W). Control remoto, 3 velocidades, función reverse. Eficiente energéticamente.',
    category: "electrodomesticos",
    subcategory: "climatizacion",
    brand: "Hampton Bay",
    countryOfOrigin: "Estados Unidos",
    price: 129,
    currency: "USD",
    thumbnail: IMG.ventiladorTecho,
    images: [img(IMG.ventiladorTecho, "Ventilador de techo")],
    specs: [
      { label: "Tamaño", value: '52"' },
      { label: "Aspas", value: "5" },
      { label: "Luz LED", value: "Integrada 18W" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "10-14 días",
    shippingType: "express",
    weight: 8,
    tags: ["ventilador", "techo"],
    rating: 4.7,
    reviewCount: 32,
  },
  {
    id: "p_elec_021",
    slug: "climatizador-portatil",
    name: "Climatizador Portátil 3-en-1",
    description: "Climatizador 3-en-1: ventilador, humidificador, refrescante.",
    longDescription:
      "Climatizador portátil 3-en-1: ventilador, humidificador y enfriador por evaporación. Tanque de agua de 5L. 3 velocidades, control remoto. Alternativa económica al aire acondicionado.",
    category: "electrodomesticos",
    subcategory: "climatizacion",
    brand: "Honeywell",
    countryOfOrigin: "China",
    price: 189,
    currency: "USD",
    thumbnail: IMG.climatizador,
    images: [img(IMG.climatizador, "Climatizador portátil")],
    specs: [
      { label: "Funciones", value: "Ventilador + Humidificador + Enfriador" },
      { label: "Tanque", value: "5 L" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "10-14 días",
    shippingType: "express",
    weight: 7,
    tags: ["climatizador", "portátil"],
    rating: 4.5,
    reviewCount: 24,
  },

  // ===========================================================
  // PEQUEÑOS ELECTRODOMÉSTICOS (8)
  // ===========================================================
  {
    id: "p_elec_029",
    slug: "licuadora-oster",
    name: "Licuadora Oster 8 Velocidades",
    description: "Licuadora Oster, jarra de cristal, 8 velocidades.",
    longDescription:
      "Licuadora Oster Classic con jarra de cristal de 6 tazas, 8 velocidades + pulse. Cuchillas de acero inoxidable. La icónica licuadora que toda madre cubana conoce. Repuestos accesibles.",
    category: "electrodomesticos",
    subcategory: "pequenos",
    brand: "Oster",
    countryOfOrigin: "México",
    price: 59.99,
    currency: "USD",
    thumbnail: IMG.licuadora,
    images: [img(IMG.licuadora, "Licuadora Oster")],
    specs: [
      { label: "Velocidades", value: "8 + pulse" },
      { label: "Jarra", value: "Cristal 6 tazas" },
      { label: "Potencia", value: "600W" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 3.5,
    tags: ["licuadora", "Oster"],
    rating: 4.8,
    reviewCount: 142,
    bestseller: true,
    featured: true,
  },
  {
    id: "p_elec_030",
    slug: "batidora-mano",
    name: "Batidora de Mano",
    description: "Batidora de mano 5 velocidades.",
    longDescription:
      "Batidora de mano Hamilton Beach con 5 velocidades, batidores de acero inoxidable y ganchos para masa. Ideal para repostería y batidos rápidos.",
    category: "electrodomesticos",
    subcategory: "pequenos",
    brand: "Hamilton Beach",
    countryOfOrigin: "China",
    price: 34.99,
    currency: "USD",
    thumbnail: IMG.batidora,
    images: [img(IMG.batidora, "Batidora de mano")],
    specs: [
      { label: "Velocidades", value: "5" },
      { label: "Incluye", value: "Batidores + ganchos masa" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.5,
    tags: ["batidora", "repostería"],
    rating: 4.6,
    reviewCount: 38,
  },
  {
    id: "p_elec_031",
    slug: "plancha-vapor",
    name: "Plancha de Vapor",
    description: "Plancha de vapor con suela de cerámica, anti-goteo.",
    longDescription:
      "Plancha de vapor Black+Decker con suela de cerámica antiadherente, función vertical, anti-goteo y auto-apagado por seguridad. Tanque de 280 ml.",
    category: "electrodomesticos",
    subcategory: "pequenos",
    brand: "Black+Decker",
    countryOfOrigin: "China",
    price: 44.99,
    currency: "USD",
    thumbnail: IMG.plancha,
    images: [img(IMG.plancha, "Plancha de vapor")],
    specs: [
      { label: "Suela", value: "Cerámica antiadherente" },
      { label: "Tanque", value: "280 ml" },
      { label: "Auto-apagado", value: "Sí" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.5,
    tags: ["plancha", "vapor"],
    rating: 4.6,
    reviewCount: 29,
  },
  {
    id: "p_elec_032",
    slug: "cafetera-electrica",
    name: "Cafetera Eléctrica 12 Tazas",
    description: "Cafetera Mr. Coffee 12 tazas, programable.",
    longDescription:
      "Cafetera eléctrica Mr. Coffee programable de 12 tazas. Pause-and-serve, jarra de cristal, mantiene calor 2 horas. Para empezar el día con buen café.",
    category: "electrodomesticos",
    subcategory: "pequenos",
    brand: "Mr. Coffee",
    countryOfOrigin: "China",
    price: 49.99,
    currency: "USD",
    thumbnail: IMG.cafetera,
    images: [img(IMG.cafetera, "Cafetera Mr. Coffee")],
    specs: [
      { label: "Capacidad", value: "12 tazas" },
      { label: "Programable", value: "Sí" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 2.5,
    tags: ["cafetera", "café"],
    rating: 4.7,
    reviewCount: 64,
  },
  {
    id: "p_elec_033",
    slug: "procesadora-alimentos",
    name: "Procesadora de Alimentos",
    description: "Procesadora 8 tazas, 5 funciones.",
    longDescription:
      "Procesadora de alimentos Cuisinart de 8 tazas con cuchillas de acero inoxidable. Pica, ralla, mezcla, amasa. Con tubo alimentador grande.",
    category: "electrodomesticos",
    subcategory: "pequenos",
    brand: "Cuisinart",
    countryOfOrigin: "China",
    price: 79.99,
    currency: "USD",
    thumbnail: IMG.procesadora,
    images: [img(IMG.procesadora, "Procesadora de alimentos")],
    specs: [
      { label: "Capacidad", value: "8 tazas" },
      { label: "Funciones", value: "5 (picar, rallar, mezclar, amasar)" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 4.2,
    tags: ["procesadora", "cocina"],
    rating: 4.7,
    reviewCount: 41,
  },
  {
    id: "p_elec_034",
    slug: "hervidora-electrica",
    name: "Hervidora Eléctrica",
    description: "Hervidora 1.7L acero inoxidable, apagado automático.",
    longDescription:
      "Hervidora eléctrica de 1.7 litros, acero inoxidable. Hervir agua en 4 minutos. Apagado automático y protección anti-seco.",
    category: "electrodomesticos",
    subcategory: "pequenos",
    brand: "Hamilton Beach",
    countryOfOrigin: "China",
    price: 24.99,
    currency: "USD",
    thumbnail: IMG.hervidora,
    images: [img(IMG.hervidora, "Hervidora eléctrica")],
    specs: [
      { label: "Capacidad", value: "1.7 L" },
      { label: "Material", value: "Acero inoxidable" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.2,
    tags: ["hervidora", "agua"],
    rating: 4.6,
    reviewCount: 32,
  },
  {
    id: "p_elec_035",
    slug: "aspiradora-compacta",
    name: "Aspiradora Compacta",
    description: "Aspiradora vertical compacta, ligera y potente.",
    longDescription:
      "Aspiradora vertical compacta Bissell con cepillo motorizado, filtro HEPA, contenedor sin bolsa de 1L. Ligera (3.5 kg) pero potente.",
    category: "electrodomesticos",
    subcategory: "pequenos",
    brand: "Bissell",
    countryOfOrigin: "China",
    price: 89.99,
    currency: "USD",
    thumbnail: IMG.aspiradora,
    images: [img(IMG.aspiradora, "Aspiradora compacta")],
    specs: [
      { label: "Tipo", value: "Vertical sin bolsa" },
      { label: "Filtro", value: "HEPA" },
      { label: "Peso", value: "3.5 kg" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "7-10 días",
    shippingType: "express",
    weight: 4,
    tags: ["aspiradora", "limpieza"],
    rating: 4.5,
    reviewCount: 28,
  },
  {
    id: "p_elec_036",
    slug: "lavadora-portatil-5kg",
    name: "Lavadora Portátil 5 kg",
    description: "Lavadora portátil 5 kg, ideal para apartamentos.",
    longDescription:
      "Lavadora portátil de 5 kg, semi-automática, doble tina (lavar + centrifugar). Bajo consumo eléctrico y de agua. Ideal para apartamentos pequeños o como complemento.",
    category: "electrodomesticos",
    subcategory: "pequenos",
    brand: "Panda",
    countryOfOrigin: "China",
    price: 290,
    currency: "USD",
    thumbnail: IMG.lavadora,
    images: [img(IMG.lavadora, "Lavadora portátil")],
    specs: [
      { label: "Capacidad", value: "5 kg" },
      { label: "Tipo", value: "Semi-automática doble tina" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "3-5 semanas",
    shippingType: "maritime",
    weight: 18,
    tags: ["lavadora", "ropa"],
    rating: 4.5,
    reviewCount: 47,
  },
];
