import type { Product } from "@/types";

const IMG = {
  motoMishozuki: "https://images.unsplash.com/photo-1558981852-426c6c22a060?w=800",
  motoAvispa: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800",
  motoPremium: "https://images.unsplash.com/photo-1591768793355-74d04bb6608f?w=800",
  motoScooter: "https://images.unsplash.com/photo-1580310614729-ccd69652491d?w=800",
  motoPlegable: "https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800",
  motoOffroad: "https://images.unsplash.com/photo-1532203956053-6f76eccb6e8a?w=800",
  motoHonda: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800",
  motoSuzuki: "https://images.unsplash.com/photo-1558980664-769d59546b3d?w=800",
  motoYamaha: "https://images.unsplash.com/photo-1611411729583-3ca81e5e2c43?w=800",
  motoEconomica: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800",
  biciPlegable: "https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800",
  biciMontana: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800",
  biciUrbana: "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=800",
  biciCargo: "https://images.unsplash.com/photo-1502744688674-c619d1586c9e?w=800",
  bateria: "https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=800",
  cargador: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800",
  cascos: "https://images.unsplash.com/photo-1600716051809-e997e11a5d52?w=800",
  llantas: "https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=800",
  espejos: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800",
} as const;

const img = (url: string, alt: string) => ({ url, alt, width: 800, height: 800 });

export const vehiculos: Product[] = [
  // ===========================================================
  // MOTOS ELÉCTRICAS (6)
  // ===========================================================
  {
    id: "p_veh_001",
    slug: "moto-electrica-mishozuki-pro",
    name: "Moto Eléctrica Mishozuki Pro",
    description: "Moto eléctrica 60V con autonomía de 80 km. La más popular de Yumury.",
    longDescription:
      "Moto eléctrica Mishozuki Pro con motor de 1500W, batería de litio de 60V/32Ah que ofrece hasta 80 km de autonomía por carga. Velocidad máxima 55 km/h. Asiento doble cómodo, frenos de disco delanteros y traseros, suspensión hidráulica, luces LED. Perfecta para Matanzas. Incluye cargador y manual. Llega vía marítima en 4-7 semanas.",
    category: "vehiculos",
    subcategory: "motos-electricas",
    brand: "Mishozuki",
    countryOfOrigin: "China",
    price: 1890,
    currency: "USD",
    thumbnail: IMG.motoMishozuki,
    images: [img(IMG.motoMishozuki, "Moto eléctrica Mishozuki Pro")],
    variants: [
      { id: "v_mish_neg", name: "Negro", type: "color", priceModifier: 0, inStock: true },
      { id: "v_mish_roj", name: "Rojo", type: "color", priceModifier: 0, inStock: true },
      { id: "v_mish_azu", name: "Azul", type: "color", priceModifier: 0, inStock: false },
    ],
    specs: [
      { label: "Motor", value: "1500W", group: "Motor" },
      { label: "Batería", value: "60V / 32Ah Litio", group: "Motor" },
      { label: "Autonomía", value: "80 km", group: "Rendimiento" },
      { label: "Velocidad máx.", value: "55 km/h", group: "Rendimiento" },
      { label: "Tiempo de carga", value: "6-8 horas", group: "Carga" },
      { label: "Frenos", value: "Disco delantero y trasero", group: "Seguridad" },
      { label: "Suspensión", value: "Hidráulica", group: "Estructura" },
      { label: "Capacidad", value: "2 personas", group: "Estructura" },
      { label: "Garantía", value: "1 año", group: "Servicio" },
    ],
    inStock: true,
    stockLevel: "low",
    estimatedDelivery: "4-7 semanas",
    shippingType: "maritime",
    weight: 90,
    tags: ["moto", "eléctrica", "transporte", "premium"],
    rating: 4.8,
    reviewCount: 56,
    bestseller: true,
    featured: true,
  },
  {
    id: "p_veh_002",
    slug: "moto-electrica-avispa",
    name: "Moto Eléctrica Avispa 350W",
    description: "Moto eléctrica económica 350W, ideal para distancias cortas.",
    longDescription:
      "Moto eléctrica Avispa con motor 350W, batería 48V/20Ah, autonomía de 40-50 km. Velocidad máxima 35 km/h. La opción más económica para movilidad básica. Perfecta para uso urbano corto. Incluye cargador.",
    category: "vehiculos",
    subcategory: "motos-electricas",
    brand: "Avispa",
    countryOfOrigin: "China",
    price: 1290,
    currency: "USD",
    thumbnail: IMG.motoAvispa,
    images: [img(IMG.motoAvispa, "Moto Avispa 350W")],
    variants: [
      { id: "v_avi_neg", name: "Negro", type: "color", priceModifier: 0, inStock: true },
      { id: "v_avi_roj", name: "Rojo", type: "color", priceModifier: 0, inStock: true },
    ],
    specs: [
      { label: "Motor", value: "350W", group: "Motor" },
      { label: "Batería", value: "48V / 20Ah", group: "Motor" },
      { label: "Autonomía", value: "40-50 km", group: "Rendimiento" },
      { label: "Velocidad máx.", value: "35 km/h", group: "Rendimiento" },
      { label: "Garantía", value: "6 meses", group: "Servicio" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "4-7 semanas",
    shippingType: "maritime",
    weight: 65,
    tags: ["moto", "eléctrica", "económica"],
    rating: 4.5,
    reviewCount: 38,
  },
  {
    id: "p_veh_003",
    slug: "moto-electrica-premium-1500w",
    name: "Moto Eléctrica Premium 1500W",
    description: "Moto eléctrica premium con motor 1500W y autonomía de 100+ km.",
    longDescription:
      "Moto eléctrica premium con motor de 1500W, batería de litio 72V/40Ah, autonomía superior a 100 km. Velocidad máxima 60 km/h. Suspensión hidráulica reforzada, frenos de disco con ABS. La opción para quienes recorren distancias largas en Matanzas.",
    category: "vehiculos",
    subcategory: "motos-electricas",
    brand: "Sunra",
    countryOfOrigin: "China",
    price: 2490,
    currency: "USD",
    thumbnail: IMG.motoPremium,
    images: [img(IMG.motoPremium, "Moto eléctrica Premium")],
    specs: [
      { label: "Motor", value: "1500W" },
      { label: "Batería", value: "72V / 40Ah Litio" },
      { label: "Autonomía", value: "100+ km" },
      { label: "Velocidad máx.", value: "60 km/h" },
      { label: "Frenos", value: "Disco con ABS" },
    ],
    inStock: true,
    stockLevel: "low",
    estimatedDelivery: "4-7 semanas",
    shippingType: "maritime",
    weight: 95,
    tags: ["moto", "eléctrica", "premium", "larga distancia"],
    rating: 4.9,
    reviewCount: 24,
    featured: true,
  },
  {
    id: "p_veh_004",
    slug: "moto-electrica-scooter",
    name: "Moto Eléctrica Scooter Urbana",
    description: "Scooter eléctrica urbana ágil y elegante.",
    longDescription:
      "Scooter eléctrica urbana estilo Vespa moderna. Motor 1000W, batería 48V/30Ah, autonomía 60 km. Diseño aerodinámico con compartimiento bajo el asiento. Perfecta para uso diario en ciudad.",
    category: "vehiculos",
    subcategory: "motos-electricas",
    brand: "Niu",
    countryOfOrigin: "China",
    price: 1690,
    currency: "USD",
    thumbnail: IMG.motoScooter,
    images: [img(IMG.motoScooter, "Scooter eléctrica urbana")],
    variants: [
      { id: "v_sco_bla", name: "Blanco", type: "color", priceModifier: 0, inStock: true },
      { id: "v_sco_neg", name: "Negro", type: "color", priceModifier: 0, inStock: true },
    ],
    specs: [
      { label: "Motor", value: "1000W" },
      { label: "Batería", value: "48V / 30Ah" },
      { label: "Autonomía", value: "60 km" },
      { label: "Velocidad máx.", value: "45 km/h" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "4-7 semanas",
    shippingType: "maritime",
    weight: 70,
    tags: ["moto", "scooter", "urbana"],
    rating: 4.7,
    reviewCount: 31,
  },
  {
    id: "p_veh_005",
    slug: "moto-electrica-plegable",
    name: "Moto Eléctrica Plegable Urbana",
    description: "Moto eléctrica plegable, fácil de guardar.",
    longDescription:
      "Moto eléctrica plegable con motor 500W, batería removible 48V/15Ah, autonomía 35 km. Se pliega en segundos para guardar en espacios pequeños o en el auto. Ideal para apartamentos.",
    category: "vehiculos",
    subcategory: "motos-electricas",
    brand: "Xiaomi",
    countryOfOrigin: "China",
    price: 1190,
    currency: "USD",
    thumbnail: IMG.motoPlegable,
    images: [img(IMG.motoPlegable, "Moto eléctrica plegable")],
    specs: [
      { label: "Motor", value: "500W" },
      { label: "Batería", value: "Removible 48V / 15Ah" },
      { label: "Autonomía", value: "35 km" },
      { label: "Plegable", value: "Sí, en segundos" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "4-7 semanas",
    shippingType: "maritime",
    weight: 28,
    tags: ["moto", "plegable", "urbana"],
    rating: 4.6,
    reviewCount: 18,
  },
  {
    id: "p_veh_006",
    slug: "moto-electrica-offroad",
    name: "Moto Eléctrica Off-road",
    description: "Moto eléctrica todo terreno, 3000W, suspensión reforzada.",
    longDescription:
      "Moto eléctrica off-road con motor 3000W, batería 72V/45Ah, autonomía 80 km. Suspensión reforzada para terrenos difíciles, llantas todo-terreno, frenos de disco hidráulicos. Para quienes necesitan moverse fuera de carreteras pavimentadas.",
    category: "vehiculos",
    subcategory: "motos-electricas",
    brand: "Sur-Ron",
    countryOfOrigin: "China",
    price: 2890,
    currency: "USD",
    thumbnail: IMG.motoOffroad,
    images: [img(IMG.motoOffroad, "Moto eléctrica off-road")],
    specs: [
      { label: "Motor", value: "3000W" },
      { label: "Batería", value: "72V / 45Ah" },
      { label: "Tipo", value: "Off-road" },
      { label: "Suspensión", value: "Reforzada hidráulica" },
    ],
    inStock: true,
    stockLevel: "low",
    estimatedDelivery: "4-7 semanas",
    shippingType: "maritime",
    weight: 105,
    tags: ["moto", "off-road", "premium"],
    rating: 4.8,
    reviewCount: 12,
  },

  // ===========================================================
  // MOTOS DE COMBUSTIÓN (4)
  // ===========================================================
  {
    id: "p_veh_007",
    slug: "moto-honda-125",
    name: "Moto Honda 125cc",
    description: "Moto Honda 125cc, la más confiable del mercado.",
    longDescription:
      "Moto Honda 125cc, motor 4 tiempos, transmisión manual de 5 velocidades. La marca con la mejor reputación en repuestos y durabilidad. Consumo eficiente (90 km/galón). Frenos de disco delantero, tambor trasero. Repuestos abundantes en Cuba.",
    category: "vehiculos",
    subcategory: "motos-combustion",
    brand: "Honda",
    countryOfOrigin: "Japón",
    price: 2290,
    currency: "USD",
    thumbnail: IMG.motoHonda,
    images: [img(IMG.motoHonda, "Moto Honda 125cc")],
    variants: [
      { id: "v_hon_roj", name: "Rojo", type: "color", priceModifier: 0, inStock: true },
      { id: "v_hon_neg", name: "Negro", type: "color", priceModifier: 0, inStock: true },
    ],
    specs: [
      { label: "Cilindrada", value: "125cc" },
      { label: "Motor", value: "4 tiempos" },
      { label: "Transmisión", value: "Manual 5 vel" },
      { label: "Consumo", value: "~90 km/galón" },
      { label: "Garantía", value: "2 años" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "4-7 semanas",
    shippingType: "maritime",
    weight: 110,
    tags: ["moto", "Honda", "gasolina", "confiable"],
    rating: 4.9,
    reviewCount: 67,
    bestseller: true,
    featured: true,
  },
  {
    id: "p_veh_008",
    slug: "moto-suzuki-150",
    name: "Moto Suzuki 150cc",
    description: "Moto Suzuki 150cc, deportiva y potente.",
    longDescription:
      "Moto Suzuki 150cc deportiva, motor 4 tiempos refrigerado por aire, 14 HP. Transmisión manual 6 velocidades. Frenos de disco delantero y trasero. Diseño deportivo, llantas anchas.",
    category: "vehiculos",
    subcategory: "motos-combustion",
    brand: "Suzuki",
    countryOfOrigin: "Japón",
    price: 2690,
    currency: "USD",
    thumbnail: IMG.motoSuzuki,
    images: [img(IMG.motoSuzuki, "Moto Suzuki 150cc")],
    specs: [
      { label: "Cilindrada", value: "150cc" },
      { label: "Potencia", value: "14 HP" },
      { label: "Transmisión", value: "Manual 6 vel" },
      { label: "Frenos", value: "Disco delantero y trasero" },
    ],
    inStock: true,
    stockLevel: "low",
    estimatedDelivery: "4-7 semanas",
    shippingType: "maritime",
    weight: 130,
    tags: ["moto", "Suzuki", "deportiva"],
    rating: 4.8,
    reviewCount: 28,
  },
  {
    id: "p_veh_009",
    slug: "moto-yamaha-125",
    name: "Moto Yamaha 125cc",
    description: "Moto Yamaha 125cc, balance entre potencia y consumo.",
    longDescription:
      "Moto Yamaha 125cc, conocida por su buen balance entre potencia y eficiencia. Motor 4 tiempos, encendido eléctrico, transmisión 5 velocidades. Diseño elegante.",
    category: "vehiculos",
    subcategory: "motos-combustion",
    brand: "Yamaha",
    countryOfOrigin: "Japón",
    price: 2490,
    currency: "USD",
    thumbnail: IMG.motoYamaha,
    images: [img(IMG.motoYamaha, "Moto Yamaha 125cc")],
    specs: [
      { label: "Cilindrada", value: "125cc" },
      { label: "Motor", value: "4 tiempos" },
      { label: "Encendido", value: "Eléctrico" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "4-7 semanas",
    shippingType: "maritime",
    weight: 115,
    tags: ["moto", "Yamaha", "gasolina"],
    rating: 4.7,
    reviewCount: 31,
  },
  {
    id: "p_veh_010",
    slug: "moto-economica-110",
    name: "Moto Económica 110cc",
    description: "Moto 110cc económica, opción accesible.",
    longDescription:
      "Moto de combustión 110cc, opción económica para quien necesita movilidad básica. Motor 4 tiempos, fácil de mantener, repuestos accesibles. Buen consumo.",
    category: "vehiculos",
    subcategory: "motos-combustion",
    brand: "Italika",
    countryOfOrigin: "México",
    price: 1890,
    currency: "USD",
    thumbnail: IMG.motoEconomica,
    images: [img(IMG.motoEconomica, "Moto económica 110cc")],
    specs: [
      { label: "Cilindrada", value: "110cc" },
      { label: "Motor", value: "4 tiempos" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "4-7 semanas",
    shippingType: "maritime",
    weight: 95,
    tags: ["moto", "económica"],
    rating: 4.4,
    reviewCount: 22,
  },

  // ===========================================================
  // BICICLETAS ELÉCTRICAS (4)
  // ===========================================================
  {
    id: "p_veh_011",
    slug: "bici-electrica-plegable",
    name: "Bicicleta Eléctrica Plegable",
    description: "E-bike plegable, perfecta para uso urbano.",
    longDescription:
      "Bicicleta eléctrica plegable de aluminio, motor 250W, batería 36V/10Ah, autonomía 40 km en modo asistido o 25 km full eléctrico. Se pliega en segundos. Ruedas 16\".",
    category: "vehiculos",
    subcategory: "bicicletas-electricas",
    brand: "Ancheer",
    countryOfOrigin: "China",
    price: 890,
    currency: "USD",
    thumbnail: IMG.biciPlegable,
    images: [img(IMG.biciPlegable, "Bici eléctrica plegable")],
    specs: [
      { label: "Motor", value: "250W" },
      { label: "Batería", value: "36V / 10Ah" },
      { label: "Autonomía", value: "40 km asistido" },
      { label: 'Ruedas', value: '16"' },
      { label: "Plegable", value: "Sí" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "4-7 semanas",
    shippingType: "maritime",
    weight: 22,
    tags: ["bicicleta", "eléctrica", "plegable"],
    rating: 4.6,
    reviewCount: 24,
  },
  {
    id: "p_veh_012",
    slug: "bici-electrica-montana",
    name: "Bicicleta Eléctrica de Montaña",
    description: "E-bike de montaña, suspensión completa.",
    longDescription:
      "Bicicleta eléctrica de montaña con suspensión completa, motor 500W, batería 48V/15Ah, autonomía 60 km. Cambios Shimano 21 velocidades. Cuadro de aluminio reforzado.",
    category: "vehiculos",
    subcategory: "bicicletas-electricas",
    brand: "Trek",
    countryOfOrigin: "China",
    price: 1290,
    currency: "USD",
    thumbnail: IMG.biciMontana,
    images: [img(IMG.biciMontana, "Bici eléctrica de montaña")],
    specs: [
      { label: "Motor", value: "500W" },
      { label: "Batería", value: "48V / 15Ah" },
      { label: "Autonomía", value: "60 km" },
      { label: "Cambios", value: "Shimano 21 vel" },
    ],
    inStock: true,
    stockLevel: "low",
    estimatedDelivery: "4-7 semanas",
    shippingType: "maritime",
    weight: 26,
    tags: ["bicicleta", "eléctrica", "montaña"],
    rating: 4.8,
    reviewCount: 16,
  },
  {
    id: "p_veh_013",
    slug: "bici-electrica-urbana",
    name: 'Bicicleta Eléctrica Urbana 26"',
    description: "E-bike urbana 26\", cómoda y elegante.",
    longDescription:
      'Bicicleta eléctrica urbana de 26", motor 350W, batería 36V/12Ah, autonomía 50 km. Asiento ergonómico, parrilla trasera, luces LED. Perfecta para ir al trabajo o pasear.',
    category: "vehiculos",
    subcategory: "bicicletas-electricas",
    brand: "Vivi",
    countryOfOrigin: "China",
    price: 990,
    currency: "USD",
    thumbnail: IMG.biciUrbana,
    images: [img(IMG.biciUrbana, "Bici eléctrica urbana")],
    specs: [
      { label: "Motor", value: "350W" },
      { label: "Batería", value: "36V / 12Ah" },
      { label: "Autonomía", value: "50 km" },
      { label: 'Ruedas', value: '26"' },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "4-7 semanas",
    shippingType: "maritime",
    weight: 24,
    tags: ["bicicleta", "eléctrica", "urbana"],
    rating: 4.7,
    reviewCount: 22,
    featured: true,
  },
  {
    id: "p_veh_014",
    slug: "bici-electrica-cargo",
    name: "Bicicleta Eléctrica Cargo",
    description: "E-bike cargo con caja delantera para transportar.",
    longDescription:
      "Bicicleta eléctrica cargo con caja delantera de carga (capacidad 50 kg). Motor 750W, batería 48V/20Ah, autonomía 70 km. Para llevar mercancía, niños o compras.",
    category: "vehiculos",
    subcategory: "bicicletas-electricas",
    brand: "Rad Power",
    countryOfOrigin: "China",
    price: 1490,
    currency: "USD",
    thumbnail: IMG.biciCargo,
    images: [img(IMG.biciCargo, "Bici eléctrica cargo")],
    specs: [
      { label: "Motor", value: "750W" },
      { label: "Batería", value: "48V / 20Ah" },
      { label: "Carga", value: "50 kg en caja delantera" },
    ],
    inStock: true,
    stockLevel: "low",
    estimatedDelivery: "4-7 semanas",
    shippingType: "maritime",
    weight: 35,
    tags: ["bicicleta", "cargo", "eléctrica"],
    rating: 4.7,
    reviewCount: 8,
  },

  // ===========================================================
  // REPUESTOS Y ACCESORIOS (5)
  // ===========================================================
  {
    id: "p_veh_015",
    slug: "bateria-litio-60v",
    name: "Batería Litio 60V para Moto Eléctrica",
    description: "Batería de repuesto 60V/32Ah para motos eléctricas.",
    longDescription:
      "Batería de litio 60V/32Ah de repuesto, compatible con motos Mishozuki Pro y similares. 1000+ ciclos de carga. Garantía de 1 año. Incluye cargador universal.",
    category: "vehiculos",
    subcategory: "repuestos",
    brand: "Mishozuki",
    countryOfOrigin: "China",
    price: 390,
    currency: "USD",
    thumbnail: IMG.bateria,
    images: [img(IMG.bateria, "Batería litio 60V")],
    specs: [
      { label: "Voltaje", value: "60V" },
      { label: "Capacidad", value: "32Ah" },
      { label: "Ciclos", value: "1000+" },
      { label: "Garantía", value: "1 año" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "10-14 días",
    shippingType: "express",
    weight: 12,
    tags: ["batería", "moto", "repuesto"],
    rating: 4.7,
    reviewCount: 18,
  },
  {
    id: "p_veh_016",
    slug: "cargador-universal-moto",
    name: "Cargador Universal Moto Eléctrica",
    description: "Cargador universal compatible con la mayoría de motos eléctricas.",
    longDescription:
      "Cargador universal 48V-72V con detección automática de voltaje. Compatible con la mayoría de motos eléctricas chinas. Protección contra sobrecarga, sobrecalentamiento y cortocircuito. Cable de 1.8m.",
    category: "vehiculos",
    subcategory: "repuestos",
    countryOfOrigin: "China",
    price: 89,
    currency: "USD",
    thumbnail: IMG.cargador,
    images: [img(IMG.cargador, "Cargador universal")],
    specs: [
      { label: "Voltaje", value: "48V - 72V" },
      { label: "Detección", value: "Automática" },
      { label: "Protecciones", value: "Sobrecarga, sobrecalentamiento, cortocircuito" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.2,
    tags: ["cargador", "repuesto"],
    rating: 4.6,
    reviewCount: 14,
  },
  {
    id: "p_veh_017",
    slug: "cascos-x2",
    name: "Cascos Certificados (2 unidades)",
    description: "Pack de 2 cascos certificados DOT para moto.",
    longDescription:
      "Pack de 2 cascos abiertos certificados DOT, ajustables, con visera anti-niebla y forro acolchado removible. Ventilación superior. Talla universal ajustable.",
    category: "vehiculos",
    subcategory: "repuestos",
    brand: "GLX",
    countryOfOrigin: "China",
    price: 79,
    currency: "USD",
    thumbnail: IMG.cascos,
    images: [img(IMG.cascos, "Cascos para moto")],
    specs: [
      { label: "Cantidad", value: "2 cascos" },
      { label: "Certificación", value: "DOT" },
      { label: "Talla", value: "Universal ajustable" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 3,
    tags: ["casco", "seguridad", "moto"],
    rating: 4.7,
    reviewCount: 32,
  },
  {
    id: "p_veh_018",
    slug: "kit-llantas-camaras",
    name: "Kit Llantas + Cámaras",
    description: "Kit de 2 llantas con cámaras para moto eléctrica.",
    longDescription:
      "Kit de 2 llantas tubeless con cámaras de aire reforzadas. Medida 90/90-12 (universal para la mayoría de motos eléctricas). Compuesto resistente. Incluye herramientas de montaje básicas.",
    category: "vehiculos",
    subcategory: "repuestos",
    countryOfOrigin: "China",
    price: 129,
    currency: "USD",
    thumbnail: IMG.llantas,
    images: [img(IMG.llantas, "Kit de llantas y cámaras")],
    specs: [
      { label: "Cantidad", value: "2 llantas + 2 cámaras" },
      { label: "Medida", value: "90/90-12" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "10-14 días",
    shippingType: "express",
    weight: 6,
    tags: ["llantas", "moto", "repuesto"],
    rating: 4.5,
    reviewCount: 11,
  },
  {
    id: "p_veh_019",
    slug: "espejos-manillares",
    name: "Espejos y Manillares",
    description: "Set de espejos retrovisores y manillares para moto.",
    longDescription:
      "Set completo de 2 espejos retrovisores cromados ajustables y manillares deportivos universales. Material de aluminio anodizado. Tornillería incluida.",
    category: "vehiculos",
    subcategory: "repuestos",
    countryOfOrigin: "China",
    price: 59,
    currency: "USD",
    thumbnail: IMG.espejos,
    images: [img(IMG.espejos, "Espejos y manillares")],
    specs: [
      { label: "Incluye", value: "2 espejos + manillares" },
      { label: "Material", value: "Aluminio anodizado" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 1.5,
    tags: ["espejos", "manillar", "repuesto"],
    rating: 4.4,
    reviewCount: 9,
  },
];
