import type { Category } from "@/types";

export const categories: Category[] = [
  {
    id: "cat_alimentos",
    slug: "alimentos",
    name: "Alimentos",
    description:
      "Todo lo que tu familia necesita para llenar la despensa, desde básicos hasta especialidades.",
    shortDescription: "Comida y aseo para el día a día",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200",
    icon: "UtensilsCrossed",
    color: "#15803D",
    productCount: 75,
    featured: true,
    subcategories: [
      {
        id: "sub_carnes",
        slug: "carnes-y-pollo",
        categorySlug: "alimentos",
        name: "Carnes y Pollo",
        description: "Pollo, cerdo, res, embutidos y mariscos congelados",
        image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800",
        productCount: 15,
      },
      {
        id: "sub_granos",
        slug: "granos",
        categorySlug: "alimentos",
        name: "Granos y Pastas",
        description: "Arroz, frijoles, lentejas, espagueti y harinas",
        image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800",
        productCount: 12,
      },
      {
        id: "sub_aceites",
        slug: "aceites-condimentos",
        categorySlug: "alimentos",
        name: "Aceites y Condimentos",
        description: "Aceites, sal, azúcar, especias, café y salsas",
        image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800",
        productCount: 14,
      },
      {
        id: "sub_lacteos",
        slug: "lacteos",
        categorySlug: "alimentos",
        name: "Lácteos",
        description: "Leche en polvo, condensada, quesos y mantequilla",
        image: "https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=800",
        productCount: 12,
      },
      {
        id: "sub_conservas",
        slug: "conservas",
        categorySlug: "alimentos",
        name: "Conservas y Enlatados",
        description: "Atún, sardinas, jamoneta, vegetales y frutas en lata",
        image: "https://images.unsplash.com/photo-1607612822681-2caa9d3da90e?w=800",
        productCount: 14,
      },
      {
        id: "sub_aseo",
        slug: "aseo-personal",
        categorySlug: "alimentos",
        name: "Aseo Personal",
        description: "Jabón, pasta dental, champú, desodorante y pañales",
        image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800",
        productCount: 13,
      },
      {
        id: "sub_limpieza",
        slug: "limpieza",
        categorySlug: "alimentos",
        name: "Limpieza del Hogar",
        description: "Detergente, cloro, papel higiénico y productos de limpieza",
        image: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=800",
        productCount: 10,
      },
    ],
  },
  {
    id: "cat_combos",
    slug: "combos",
    name: "Combos",
    description:
      "Combos pre-armados curados para cada ocasión. Pensados con propósito, no solo bulk.",
    shortDescription: "Listos para enviar, sin pensar",
    image: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1200",
    icon: "Package",
    color: "#EA8A1C",
    productCount: 15,
    featured: true,
    subcategories: [
      {
        id: "sub_combos_basicos",
        slug: "basicos",
        categorySlug: "combos",
        name: "Combos Básicos",
        description: "Para enviar lo esencial sin complicaciones",
        image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800",
        productCount: 4,
      },
      {
        id: "sub_combos_familiares",
        slug: "familiares",
        categorySlug: "combos",
        name: "Combos Familiares",
        description: "Para alimentar familias completas",
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800",
        productCount: 4,
      },
      {
        id: "sub_combos_emergencia",
        slug: "emergencia",
        categorySlug: "combos",
        name: "Combos Emergencia",
        description: "Apagones, ciclones y situaciones críticas",
        image: "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=800",
        productCount: 3,
      },
      {
        id: "sub_combos_especiales",
        slug: "especiales",
        categorySlug: "combos",
        name: "Combos Especiales",
        description: "Cumpleaños, bebés, dietas especiales",
        image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800",
        productCount: 4,
      },
    ],
  },
  {
    id: "cat_electro",
    slug: "electrodomesticos",
    name: "Electrodomésticos",
    description:
      "Calidad garantizada para hacer la vida más fácil en Matanzas. Refrigeración, cocina, climatización y energía.",
    shortDescription: "Calidad que dura",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200",
    icon: "Refrigerator",
    color: "#DC2626",
    productCount: 36,
    featured: true,
    subcategories: [
      {
        id: "sub_refrig",
        slug: "refrigeracion",
        categorySlug: "electrodomesticos",
        name: "Refrigeración",
        description: "Refrigeradores, neveras y congeladores",
        image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=800",
        productCount: 6,
      },
      {
        id: "sub_cocina",
        slug: "cocina",
        categorySlug: "electrodomesticos",
        name: "Cocina",
        description: "Hornillas, microondas, ollas eléctricas y cocinas",
        image: "https://images.unsplash.com/photo-1556909195-d85075a0a96d?w=800",
        productCount: 8,
      },
      {
        id: "sub_clima",
        slug: "climatizacion",
        categorySlug: "electrodomesticos",
        name: "Climatización",
        description: "Aires acondicionados, ventiladores y climatizadores",
        image: "https://images.unsplash.com/photo-1631545806609-a09e4b16d7d6?w=800",
        productCount: 6,
      },
      {
        id: "sub_energia",
        slug: "energia",
        categorySlug: "electrodomesticos",
        name: "Energía",
        description: "EcoFlow, paneles solares, generadores y baterías",
        image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800",
        productCount: 8,
      },
      {
        id: "sub_pequenos",
        slug: "pequenos",
        categorySlug: "electrodomesticos",
        name: "Pequeños Electrodomésticos",
        description: "Licuadoras, batidoras, planchas y más",
        image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800",
        productCount: 8,
      },
    ],
  },
  {
    id: "cat_vehiculos",
    slug: "vehiculos",
    name: "Vehículos",
    description:
      "Movilidad para tu familia. Motos eléctricas, motos de combustión, bicicletas y repuestos.",
    shortDescription: "Movilidad confiable",
    image: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=1200",
    icon: "Bike",
    color: "#0F5F2E",
    productCount: 19,
    featured: true,
    subcategories: [
      {
        id: "sub_motos_e",
        slug: "motos-electricas",
        categorySlug: "vehiculos",
        name: "Motos Eléctricas",
        description: "Motos eléctricas con autonomía de hasta 120 km",
        image: "https://images.unsplash.com/photo-1558981852-426c6c22a060?w=800",
        productCount: 6,
      },
      {
        id: "sub_motos_c",
        slug: "motos-combustion",
        categorySlug: "vehiculos",
        name: "Motos de Combustión",
        description: "Motos de gasolina Honda, Suzuki, Yamaha",
        image: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800",
        productCount: 4,
      },
      {
        id: "sub_bicis",
        slug: "bicicletas-electricas",
        categorySlug: "vehiculos",
        name: "Bicicletas Eléctricas",
        description: "E-bikes plegables, urbanas, de montaña y cargo",
        image: "https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800",
        productCount: 4,
      },
      {
        id: "sub_repuestos",
        slug: "repuestos",
        categorySlug: "vehiculos",
        name: "Repuestos y Accesorios",
        description: "Baterías, cargadores, cascos, llantas",
        image: "https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=800",
        productCount: 5,
      },
    ],
  },
];

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getSubcategoryBySlug(categorySlug: string, subSlug: string) {
  const cat = getCategoryBySlug(categorySlug);
  return cat?.subcategories.find((s) => s.slug === subSlug);
}
