import type { Product } from "@/types";

const img = (url: string, alt: string) => ({ url, alt, width: 800, height: 800 });

export const combos: Product[] = [
  // 1. COMBO APAGÓN READY
  {
    id: "combo_001",
    slug: "combo-apagon-ready",
    name: "Combo Apagón Ready",
    description: "Para los apagones largos. Energía, luz y aire para tu familia.",
    longDescription:
      "Diseñado específicamente para enfrentar los cortes de electricidad prolongados que afectan a Matanzas. Una estación de energía portátil EcoFlow + lámparas LED recargables + ventilador USB + power bank que mantendrán a tu familia con luz, comunicación y refrescada hasta por 12 horas continuas. Una inversión que se nota desde el primer apagón.",
    category: "combos",
    subcategory: "emergencia",
    price: 890,
    comparePrice: 1010,
    currency: "USD",
    thumbnail: "https://images.unsplash.com/photo-1620677368158-32b078c1c000?w=800",
    images: [
      img(
        "https://images.unsplash.com/photo-1620677368158-32b078c1c000?w=800",
        "Combo Apagón Ready",
      ),
    ],
    isCombo: true,
    comboTheme: "apagon-ready",
    comboBadge: "Apagón Ready",
    comboItems: [
      { name: "Estación EcoFlow Delta 1300", quantity: 1, unit: "unidad", productId: "p_elec_001" },
      { name: "Lámpara LED Recargable Solar", quantity: 2, unit: "unidad", productId: "p_elec_028" },
      { name: "Power Bank 30,000 mAh", quantity: 1, unit: "unidad", productId: "p_elec_027" },
      { name: "Ventilador USB Recargable", quantity: 1, unit: "unidad", productId: "p_elec_019" },
      { name: "Linterna LED Potente", quantity: 1, unit: "unidad" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "7-10 días",
    shippingType: "express",
    weight: 18,
    tags: ["apagón", "emergencia", "energía", "imprescindible"],
    rating: 4.9,
    reviewCount: 87,
    bestseller: true,
    featured: true,
  },

  // 2. COMBO CICLÓN READY
  {
    id: "combo_002",
    slug: "combo-ciclon-ready",
    name: "Combo Ciclón Ready",
    description: "Para temporada de ciclones. Lo esencial para 5-7 días de emergencia.",
    longDescription:
      "Combo de emergencia diseñado para la temporada ciclónica. Incluye linterna, radio a baterías para mantener comunicación, velas, fósforos, agua embotellada, conservas variadas y botiquín básico. Lo que tu familia necesita para esos primeros días críticos sin servicios.",
    category: "combos",
    subcategory: "emergencia",
    price: 145,
    comparePrice: 170,
    currency: "USD",
    thumbnail: "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=800",
    images: [
      img(
        "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=800",
        "Combo Ciclón Ready",
      ),
    ],
    isCombo: true,
    comboTheme: "ciclon-ready",
    comboBadge: "Ciclón Ready",
    comboItems: [
      { name: "Linterna LED", quantity: 2, unit: "unidad" },
      { name: "Radio AM/FM a baterías", quantity: 1, unit: "unidad" },
      { name: "Velas grandes", quantity: 10, unit: "unidad" },
      { name: "Fósforos resistentes al agua", quantity: 5, unit: "cajas" },
      { name: "Agua embotellada", quantity: 1, unit: "caja" },
      { name: "Atún en lata", quantity: 6, unit: "unidad" },
      { name: "Galletas saladas", quantity: 4, unit: "paquetes" },
      { name: "Botiquín básico", quantity: 1, unit: "unidad" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 12,
    tags: ["ciclón", "emergencia", "preparación"],
    rating: 4.8,
    reviewCount: 43,
    featured: true,
  },

  // 3. COMBO FAMILIAR BÁSICO
  {
    id: "combo_003",
    slug: "combo-familiar-basico",
    name: "Combo Familiar Básico",
    description: "Lo esencial para una familia. Comida básica para 1-2 semanas.",
    longDescription:
      "El combo más popular de Yumury. Pensado para alimentar a una familia con productos básicos durante 1-2 semanas. Arroz, frijoles, aceite, pollo, picadillo, azúcar, sal y café — todo lo que se necesita para cocinar comidas completas. La opción más económica y completa.",
    category: "combos",
    subcategory: "familiares",
    price: 69.99,
    comparePrice: 84.99,
    currency: "USD",
    thumbnail: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800",
    images: [
      img(
        "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800",
        "Combo familiar básico",
      ),
    ],
    isCombo: true,
    comboTheme: "familiar-basico",
    comboBadge: "Más vendido",
    comboItems: [
      { name: "Arroz de grano largo", quantity: 10, unit: "lb", productId: "p_alim_001" },
      { name: "Frijoles negros", quantity: 5, unit: "lb", productId: "p_alim_021" },
      { name: "Aceite de soya", quantity: 1, unit: "galón", productId: "p_alim_003" },
      { name: "Pollo entero congelado", quantity: 5, unit: "lb", productId: "p_alim_002" },
      { name: "Picadillo de res", quantity: 3, unit: "lb", productId: "p_alim_009" },
      { name: "Azúcar blanca", quantity: 4, unit: "lb", productId: "p_alim_034" },
      { name: "Sal de mesa", quantity: 1, unit: "paquete", productId: "p_alim_033" },
      { name: "Café La Llave", quantity: 1, unit: "paquete", productId: "p_alim_041" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 25,
    tags: ["familiar", "básico", "alimentos", "imprescindible", "económico"],
    rating: 4.9,
    reviewCount: 234,
    bestseller: true,
    featured: true,
  },

  // 4. COMBO FAMILIAR PREMIUM
  {
    id: "combo_004",
    slug: "combo-familiar-premium",
    name: "Combo Familiar Premium",
    description: "El familiar básico ampliado con carnes premium, lácteos y frutas.",
    longDescription:
      "Para quien quiere ofrecerle lo mejor a su familia. Incluye todo del Familiar Básico más carne de cerdo, mariscos, lácteos premium, frutas y vegetales en conserva. Alimenta a una familia de 4-5 personas durante casi 3 semanas.",
    category: "combos",
    subcategory: "familiares",
    price: 129.99,
    comparePrice: 159.99,
    currency: "USD",
    thumbnail: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800",
    images: [
      img(
        "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800",
        "Combo familiar premium",
      ),
    ],
    isCombo: true,
    comboTheme: "familiar-premium",
    comboBadge: "Premium",
    comboItems: [
      { name: "Todo del Combo Familiar Básico", quantity: 1, unit: "set" },
      { name: "Carne de cerdo", quantity: 5, unit: "lb", productId: "p_alim_011" },
      { name: "Mariscos surtidos", quantity: 3, unit: "lb", productId: "p_alim_019" },
      { name: "Leche en polvo Nido", quantity: 1, unit: "paquete", productId: "p_alim_004" },
      { name: "Queso amarillo", quantity: 2, unit: "lb", productId: "p_alim_048" },
      { name: "Mantequilla", quantity: 1, unit: "lb", productId: "p_alim_050" },
      { name: "Frutas en almíbar", quantity: 3, unit: "frascos", productId: "p_alim_065" },
      { name: "Vegetales mixtos", quantity: 4, unit: "latas", productId: "p_alim_061" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 38,
    tags: ["familiar", "premium", "completo"],
    rating: 4.8,
    reviewCount: 124,
    featured: true,
  },

  // 5. COMBO FAMILIAR XL
  {
    id: "combo_005",
    slug: "combo-familiar-xl",
    name: "Combo Familiar XL — 1 Mes Completo",
    description: "Despensa para un mes completo. Para familias de 4-6 personas.",
    longDescription:
      "El combo más completo de Yumury. Despensa completa para un mes para una familia de 4-6 personas. Todo lo necesario: carnes variadas, granos en cantidad, aceites, lácteos, conservas, productos de aseo y limpieza. La opción ideal para enviar una sola vez al mes.",
    category: "combos",
    subcategory: "familiares",
    price: 189.99,
    comparePrice: 235,
    currency: "USD",
    thumbnail: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800",
    images: [
      img(
        "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800",
        "Combo familiar XL",
      ),
    ],
    isCombo: true,
    comboTheme: "familiar-xl",
    comboBadge: "Despensa del mes",
    comboItems: [
      { name: "Arroz", quantity: 20, unit: "lb" },
      { name: "Frijoles variados", quantity: 10, unit: "lb" },
      { name: "Pollo entero", quantity: 10, unit: "lb" },
      { name: "Carne de res molida", quantity: 5, unit: "lb" },
      { name: "Carne de cerdo", quantity: 5, unit: "lb" },
      { name: "Aceite", quantity: 2, unit: "galones" },
      { name: "Leche en polvo", quantity: 1, unit: "paquete grande" },
      { name: "Café", quantity: 2, unit: "paquetes" },
      { name: "Conservas variadas", quantity: 12, unit: "unidades" },
      { name: "Aseo personal básico", quantity: 1, unit: "kit" },
      { name: "Limpieza básica", quantity: 1, unit: "kit" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 65,
    tags: ["familiar", "mes completo", "despensa", "XL"],
    rating: 4.9,
    reviewCount: 89,
  },

  // 6. COMBO MAMÁ DIABÉTICA
  {
    id: "combo_006",
    slug: "combo-mama-diabetica",
    name: "Combo Mamá Diabética",
    description: "Productos sin azúcar y aptos para diabéticos. Cuidado especial.",
    longDescription:
      "Combo pensado especialmente para personas con diabetes. Incluye productos sin azúcar, avena integral, café descafeinado, endulzante natural (stevia), vegetales especiales, harinas integrales y proteínas magras. Cuida a quien más quieres con productos seleccionados.",
    category: "combos",
    subcategory: "especiales",
    price: 79.99,
    comparePrice: 95,
    currency: "USD",
    thumbnail: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800",
    images: [
      img("https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800", "Combo diabético"),
    ],
    isCombo: true,
    comboTheme: "diabetica",
    comboBadge: "Cuidado especial",
    comboItems: [
      { name: "Avena integral", quantity: 3, unit: "lb" },
      { name: "Pechuga de pollo", quantity: 3, unit: "lb", productId: "p_alim_006" },
      { name: "Stevia (endulzante natural)", quantity: 2, unit: "paquetes" },
      { name: "Café descafeinado", quantity: 1, unit: "paquete" },
      { name: "Pan integral", quantity: 2, unit: "paquetes" },
      { name: "Vegetales mixtos", quantity: 6, unit: "latas", productId: "p_alim_061" },
      { name: "Aceite de oliva", quantity: 1, unit: "litro", productId: "p_alim_031" },
      { name: "Mermelada sin azúcar", quantity: 1, unit: "frasco" },
      { name: "Galletas integrales", quantity: 2, unit: "paquetes" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 14,
    tags: ["diabético", "sin azúcar", "especial", "cuidado"],
    rating: 4.9,
    reviewCount: 67,
    featured: true,
  },

  // 7. COMBO CUMPLEAÑOS
  {
    id: "combo_007",
    slug: "combo-cumpleanos",
    name: "Combo Cumpleaños",
    description: "Sorprende con un cumpleaños completo. Torta, dulces y decoración.",
    longDescription:
      "Hace que el cumpleaños de tu familiar sea especial sin importar la distancia. Incluye torta dulce, caramelos surtidos, decoración (globos, sombreros, pancarta de Feliz Cumpleaños), velas, y un mensaje personalizado escrito a mano por el equipo de Yumury que se entrega con el combo.",
    category: "combos",
    subcategory: "especiales",
    price: 54.99,
    currency: "USD",
    thumbnail: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800",
    images: [
      img(
        "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800",
        "Combo cumpleaños",
      ),
    ],
    isCombo: true,
    comboTheme: "cumpleanos",
    comboBadge: "Especial",
    comboItems: [
      { name: "Torta dulce", quantity: 1, unit: "unidad" },
      { name: "Caramelos surtidos", quantity: 2, unit: "paquetes" },
      { name: "Globos decorativos", quantity: 12, unit: "unidad" },
      { name: "Sombreros de fiesta", quantity: 6, unit: "unidad" },
      { name: "Pancarta Feliz Cumpleaños", quantity: 1, unit: "unidad" },
      { name: "Velas de cumpleaños", quantity: 1, unit: "paquete" },
      { name: "Mensaje personalizado", quantity: 1, unit: "tarjeta" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 4,
    tags: ["cumpleaños", "celebración", "especial", "regalo"],
    rating: 4.9,
    reviewCount: 156,
    featured: true,
  },

  // 8. COMBO ASEO PERSONAL
  {
    id: "combo_008",
    slug: "combo-aseo-personal",
    name: "Combo Aseo Personal",
    description: "Productos de aseo para varios meses. Marcas reconocidas.",
    longDescription:
      "Kit completo de aseo personal con marcas reconocidas. Jabones, pasta dental, champú, acondicionador, desodorantes y papel higiénico para que tu familia esté abastecida por meses.",
    category: "combos",
    subcategory: "basicos",
    price: 42.99,
    comparePrice: 52,
    currency: "USD",
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800",
    images: [
      img(
        "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800",
        "Combo aseo personal",
      ),
    ],
    isCombo: true,
    comboTheme: "aseo",
    comboItems: [
      { name: "Jabón Dove", quantity: 12, unit: "unidad", productId: "p_alim_069" },
      { name: "Pasta dental Colgate", quantity: 4, unit: "unidad", productId: "p_alim_071" },
      { name: "Champú Head & Shoulders", quantity: 1, unit: "botella", productId: "p_alim_073" },
      { name: "Acondicionador Pantene", quantity: 1, unit: "botella", productId: "p_alim_075" },
      { name: "Desodorante Old Spice", quantity: 3, unit: "unidad", productId: "p_alim_076" },
      { name: "Toallas sanitarias Always", quantity: 1, unit: "paquete", productId: "p_alim_078" },
      { name: "Papel higiénico Charmin", quantity: 12, unit: "rollos", productId: "p_alim_079" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 8,
    tags: ["aseo", "personal", "familiar"],
    rating: 4.8,
    reviewCount: 178,
  },

  // 9. COMBO LIMPIEZA HOGAR
  {
    id: "combo_009",
    slug: "combo-limpieza-hogar",
    name: "Combo Limpieza del Hogar",
    description: "Todo para mantener la casa limpia por meses.",
    longDescription:
      "Kit de productos de limpieza con marcas confiables. Detergente, cloro, esponjas, jabón de fregar, ambientador y bolsas de basura. Suficiente para varios meses de limpieza profunda.",
    category: "combos",
    subcategory: "basicos",
    price: 39.99,
    currency: "USD",
    thumbnail: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=800",
    images: [
      img("https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=800", "Combo limpieza"),
    ],
    isCombo: true,
    comboTheme: "limpieza",
    comboItems: [
      { name: "Detergente Tide", quantity: 5, unit: "lb", productId: "p_alim_081" },
      { name: "Cloro Clorox", quantity: 1, unit: "galón", productId: "p_alim_083" },
      { name: "Esponjas multiuso", quantity: 10, unit: "unidad", productId: "p_alim_085" },
      { name: "Jabón de fregar Dawn", quantity: 1, unit: "botella", productId: "p_alim_084" },
      { name: "Ambientador spray", quantity: 3, unit: "unidad", productId: "p_alim_088" },
      { name: "Bolsas de basura", quantity: 100, unit: "unidad", productId: "p_alim_090" },
      { name: "Papel de cocina", quantity: 6, unit: "rollos", productId: "p_alim_089" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 10,
    tags: ["limpieza", "hogar", "básico"],
    rating: 4.7,
    reviewCount: 94,
  },

  // 10. COMBO BEBÉ
  {
    id: "combo_010",
    slug: "combo-bebe",
    name: "Combo Bebé",
    description: "Todo para el cuidado del bebé. Pañales, toallitas y aseo.",
    longDescription:
      "Kit completo para el cuidado del bebé: pañales (talla seleccionable), toallitas húmedas, talco, aceite mineral, loción y shampoo de bebé. Marcas reconocidas como Pampers y Johnson's.",
    category: "combos",
    subcategory: "especiales",
    price: 59.99,
    comparePrice: 75,
    currency: "USD",
    thumbnail: "https://images.unsplash.com/photo-1607000853019-fa39f1a90eb1?w=800",
    images: [
      img("https://images.unsplash.com/photo-1607000853019-fa39f1a90eb1?w=800", "Combo bebé"),
    ],
    isCombo: true,
    comboTheme: "bebe",
    comboBadge: "Para los más pequeños",
    variants: [
      { id: "v_bebe_t1", name: "Talla 1", type: "size", priceModifier: 0, inStock: true },
      { id: "v_bebe_t2", name: "Talla 2", type: "size", priceModifier: 0, inStock: true },
      { id: "v_bebe_t3", name: "Talla 3", type: "size", priceModifier: 0, inStock: true },
      { id: "v_bebe_t4", name: "Talla 4", type: "size", priceModifier: 3, inStock: true },
    ],
    comboItems: [
      {
        name: "Pañales Pampers (talla seleccionada)",
        quantity: 1,
        unit: "paquete",
        productId: "p_alim_005",
      },
      { name: "Toallitas húmedas", quantity: 4, unit: "paquetes" },
      { name: "Talco para bebé", quantity: 2, unit: "unidad" },
      { name: "Aceite mineral Johnson's", quantity: 1, unit: "unidad" },
      { name: "Loción Johnson's", quantity: 1, unit: "unidad" },
      { name: "Shampoo de bebé", quantity: 1, unit: "unidad" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 6,
    tags: ["bebé", "pañales", "especial"],
    rating: 4.9,
    reviewCount: 112,
  },

  // 11. COMBO COCINA ESENCIAL
  {
    id: "combo_011",
    slug: "combo-cocina-esencial",
    name: "Combo Cocina Esencial",
    description: "Lo básico para empezar a cocinar bien.",
    longDescription:
      "Kit de productos esenciales para una cocina bien surtida: aceite, sal, azúcar, vinagre, especias variadas, salsa de tomate, mayonesa, café y té. Lo que toda cocina cubana necesita.",
    category: "combos",
    subcategory: "basicos",
    price: 74.99,
    currency: "USD",
    thumbnail: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800",
    images: [
      img(
        "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800",
        "Combo cocina esencial",
      ),
    ],
    isCombo: true,
    comboTheme: "cocina-esencial",
    comboItems: [
      { name: "Aceite de soya", quantity: 1, unit: "galón", productId: "p_alim_003" },
      { name: "Sal", quantity: 5, unit: "lb", productId: "p_alim_033" },
      { name: "Azúcar", quantity: 5, unit: "lb", productId: "p_alim_034" },
      { name: "Vinagre blanco", quantity: 1, unit: "litro", productId: "p_alim_036" },
      { name: "Kit de especias", quantity: 1, unit: "set", productId: "p_alim_040" },
      { name: "Salsa de tomate", quantity: 3, unit: "unidades", productId: "p_alim_037" },
      { name: "Mayonesa Hellmann's", quantity: 1, unit: "pomo grande", productId: "p_alim_039" },
      { name: "Café La Llave", quantity: 2, unit: "paquetes", productId: "p_alim_041" },
      { name: "Té en bolsas", quantity: 1, unit: "caja", productId: "p_alim_043" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 16,
    tags: ["cocina", "esencial", "condimentos"],
    rating: 4.7,
    reviewCount: 78,
  },

  // 12. COMBO SOLO CARNES
  {
    id: "combo_012",
    slug: "combo-solo-carnes",
    name: "Combo Solo Carnes",
    description: "Variedad de carnes premium congeladas. Para los que quieren proteína.",
    longDescription:
      "Selección premium de carnes congeladas con cadena de frío garantizada. Pollo, res, cerdo, mariscos — todo lo necesario para una alimentación rica en proteínas durante semanas.",
    category: "combos",
    subcategory: "familiares",
    price: 89.99,
    comparePrice: 105,
    currency: "USD",
    thumbnail: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800",
    images: [
      img("https://images.unsplash.com/photo-1544025162-d76694265947?w=800", "Combo carnes"),
    ],
    isCombo: true,
    comboTheme: "carnes",
    comboItems: [
      { name: "Pollo entero", quantity: 4, unit: "lb", productId: "p_alim_002" },
      { name: "Pechuga de pollo", quantity: 3, unit: "lb", productId: "p_alim_006" },
      { name: "Picadillo de res", quantity: 3, unit: "lb", productId: "p_alim_009" },
      { name: "Masa de cerdo", quantity: 3, unit: "lb", productId: "p_alim_011" },
      { name: "Camarones congelados", quantity: 1, unit: "lb", productId: "p_alim_017" },
      { name: "Filetes de pescado", quantity: 2, unit: "lb", productId: "p_alim_018" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "express",
    weight: 16,
    tags: ["carnes", "proteína", "congelado"],
    rating: 4.8,
    reviewCount: 67,
  },

  // 13. COMBO DESPENSA MES
  {
    id: "combo_013",
    slug: "combo-despensa-mes",
    name: "Combo Despensa del Mes",
    description: "Despensa completa equivalente a un mes de comida.",
    longDescription:
      "Despensa estratégicamente armada para 1 mes de comida para 2-3 personas. Granos, conservas, aceites, lácteos, café y conservas en cantidad suficiente para no preocuparse por comprar en un mes entero.",
    category: "combos",
    subcategory: "familiares",
    price: 159.99,
    comparePrice: 195,
    currency: "USD",
    thumbnail: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800",
    images: [
      img(
        "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800",
        "Despensa del mes",
      ),
    ],
    isCombo: true,
    comboTheme: "despensa",
    comboBadge: "Mes completo",
    comboItems: [
      { name: "Arroz", quantity: 15, unit: "lb", productId: "p_alim_001" },
      { name: "Frijoles negros", quantity: 5, unit: "lb", productId: "p_alim_021" },
      { name: "Lentejas", quantity: 2, unit: "lb", productId: "p_alim_024" },
      { name: "Aceite", quantity: 1, unit: "galón", productId: "p_alim_003" },
      { name: "Leche en polvo", quantity: 1, unit: "paquete grande", productId: "p_alim_004" },
      { name: "Café", quantity: 2, unit: "paquetes", productId: "p_alim_041" },
      { name: "Atún", quantity: 1, unit: "caja x10", productId: "p_alim_055" },
      { name: "Sardinas", quantity: 1, unit: "caja x12", productId: "p_alim_057" },
      { name: "Vegetales mixtos en lata", quantity: 6, unit: "unidades", productId: "p_alim_061" },
      { name: "Galletas saladas", quantity: 4, unit: "paquetes" },
    ],
    inStock: true,
    stockLevel: "medium",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 32,
    tags: ["despensa", "mes", "completo"],
    rating: 4.8,
    reviewCount: 53,
  },

  // 14. COMBO ENERGÍA SOLAR
  {
    id: "combo_014",
    slug: "combo-energia-solar",
    name: "Combo Energía Solar Completo",
    description: "Solución solar autónoma. Panel + EcoFlow + accesorios.",
    longDescription:
      "La solución más completa para independencia energética en Matanzas. Panel solar de 400W + EcoFlow Delta 1300 + cables, conectores y soporte de instalación. Genera tu propia electricidad y olvídate de los apagones para siempre.",
    category: "combos",
    subcategory: "emergencia",
    price: 1290,
    comparePrice: 1450,
    currency: "USD",
    thumbnail: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800",
    images: [
      img("https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800", "Combo solar"),
    ],
    isCombo: true,
    comboTheme: "solar",
    comboBadge: "Solar Pro",
    comboItems: [
      { name: "Panel Solar 400W", quantity: 1, unit: "unidad", productId: "p_elec_025" },
      { name: "EcoFlow Delta 1300", quantity: 1, unit: "unidad", productId: "p_elec_001" },
      { name: "Cables MC4", quantity: 1, unit: "set" },
      { name: "Conectores y adaptadores", quantity: 1, unit: "kit" },
      { name: "Soporte de instalación", quantity: 1, unit: "unidad" },
      { name: "Manual en español", quantity: 1, unit: "unidad" },
    ],
    inStock: true,
    stockLevel: "low",
    estimatedDelivery: "7-10 días",
    shippingType: "express",
    weight: 35,
    tags: ["solar", "energía", "apagón", "premium"],
    rating: 4.9,
    reviewCount: 32,
    featured: true,
  },

  // 15. COMBO ESTUDIANTE
  {
    id: "combo_015",
    slug: "combo-estudiante",
    name: "Combo Estudiante",
    description: "Útiles escolares + snacks. Para estudiantes en Matanzas.",
    longDescription:
      "Kit pensado para estudiantes: útiles escolares (libretas, lápices, bolígrafos, mochila), más snacks saludables y productos de aseo personal. Perfecto para enviar a sobrinos, hijos o cualquier estudiante.",
    category: "combos",
    subcategory: "especiales",
    price: 44.99,
    currency: "USD",
    thumbnail: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800",
    images: [
      img(
        "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800",
        "Combo estudiante",
      ),
    ],
    isCombo: true,
    comboTheme: "estudiante",
    comboItems: [
      { name: "Libretas", quantity: 5, unit: "unidad" },
      { name: "Lápices y bolígrafos", quantity: 1, unit: "kit" },
      { name: "Mochila escolar", quantity: 1, unit: "unidad" },
      { name: "Calculadora", quantity: 1, unit: "unidad" },
      { name: "Snacks saludables variados", quantity: 1, unit: "pack" },
      { name: "Aseo personal básico", quantity: 1, unit: "kit" },
    ],
    inStock: true,
    stockLevel: "high",
    estimatedDelivery: "5-7 días",
    shippingType: "standard",
    weight: 5,
    tags: ["estudiante", "útiles", "escolar"],
    rating: 4.7,
    reviewCount: 41,
  },
];
