import type { Family } from "@/types";

export const mockFamilies: Family[] = [
  {
    id: "family_001",
    alias: "Mamá Mercedes",
    fullName: "Mercedes González Pérez",
    relationship: "Madre",
    age: 67,
    avatar: "👵",
    phone: "+53 5234 5678",
    altPhone: "+53 4523 1234",
    address: {
      street: "Calle 12",
      number: "234",
      between: "entre 3ra y 5ta",
      municipality: "cardenas",
      municipalityLabel: "Cárdenas",
      province: "Matanzas",
      reference: "Casa azul a la izquierda del CUPET",
    },
    birthday: "1958-06-12",
    preferences: ["café", "arroz", "pollo", "aseo personal"],
    alerts: ["Diabética"],
    notes: "Le encanta el café fuerte. Prefiere productos sin azúcar.",
    stats: {
      totalOrdersReceived: 12,
      lastOrderDate: "2025-04-22",
      totalReceived: 567.89,
    },
    createdAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "family_002",
    alias: "Tío Pedro",
    fullName: "Pedro Ramírez Castro",
    relationship: "Tío",
    age: 72,
    avatar: "👴",
    phone: "+53 5345 6789",
    address: {
      street: "Avenida 1ro de Mayo",
      number: "15",
      between: "entre Maceo y Martí",
      municipality: "matanzas",
      municipalityLabel: "Matanzas (capital)",
      province: "Matanzas",
      reference: "Edificio amarillo, segundo piso",
    },
    birthday: "1953-09-08",
    preferences: ["conservas", "café", "limpieza"],
    alerts: ["Hipertenso"],
    notes: "Vive solo, le mandamos productos básicos cada mes.",
    stats: {
      totalOrdersReceived: 8,
      lastOrderDate: "2025-04-15",
      totalReceived: 389.5,
    },
    createdAt: "2024-02-20T14:15:00Z",
  },
  {
    id: "family_003",
    alias: "Sobrina Camila",
    fullName: "Camila Fernández González",
    relationship: "Sobrina",
    age: 24,
    avatar: "👧",
    phone: "+53 5456 7890",
    address: {
      street: "Calle 23",
      number: "108",
      between: "entre Avenida 1ra y 3ra",
      municipality: "varadero",
      municipalityLabel: "Varadero",
      province: "Matanzas",
      reference: "Cerca del hotel Iberostar",
    },
    birthday: "2001-11-30",
    preferences: ["aseo personal premium", "comida especial", "electrodomésticos"],
    alerts: [],
    notes: "Trabaja en hotelería, le gustan productos de marca.",
    stats: {
      totalOrdersReceived: 5,
      lastOrderDate: "2025-03-28",
      totalReceived: 234.99,
    },
    createdAt: "2024-05-10T09:00:00Z",
  },
];
