import type { Review } from "@/types";

export const mockReviews: Review[] = [
  // ===== ARROZ (p_alim_001) =====
  {
    id: "rev_001",
    productId: "p_alim_001",
    userName: "Yusniel R.",
    userAvatar: "👨🏽",
    userLocation: "Miami, FL",
    rating: 5,
    title: "Llegó perfecto",
    content:
      "Mi mamá lo recibió en 6 días. Arroz de muy buena calidad, sin granos partidos. Ya pedí otra vez.",
    date: "2025-04-20",
    helpful: 23,
    verified: true,
  },
  {
    id: "rev_002",
    productId: "p_alim_001",
    userName: "Mariela G.",
    userAvatar: "👩🏽",
    userLocation: "Tampa, FL",
    rating: 5,
    title: "El que prefiere mi familia",
    content:
      "Los granos quedan sueltos y blancos. Ya van 4 veces que pido y siempre llega bien.",
    date: "2025-04-15",
    helpful: 18,
    verified: true,
  },
  {
    id: "rev_003",
    productId: "p_alim_001",
    userName: "Roberto P.",
    userAvatar: "👨🏽",
    userLocation: "Madrid, España",
    rating: 4,
    title: "Buen arroz, bien empacado",
    content:
      "Calidad buena. Llegó un día después de lo prometido pero todo bien. Empaque resistente.",
    date: "2025-04-08",
    helpful: 12,
    verified: true,
  },

  // ===== POLLO ENTERO (p_alim_002) =====
  {
    id: "rev_004",
    productId: "p_alim_002",
    userName: "Yamila C.",
    userAvatar: "👩🏽",
    userLocation: "Hialeah, FL",
    rating: 5,
    title: "Llegó congelado al 100%",
    content:
      "Tenía dudas si el pollo iba a llegar bien por la cadena de frío, pero llegó perfecto. Mi familia en Cárdenas estaba feliz.",
    date: "2025-04-25",
    helpful: 34,
    verified: true,
  },
  {
    id: "rev_005",
    productId: "p_alim_002",
    userName: "Carlos F.",
    userAvatar: "👨🏽",
    userLocation: "Houston, TX",
    rating: 5,
    title: "Excelente calidad",
    content:
      "Pollo de muy buen tamaño, bien limpio. La cadena de frío funcionó perfecto. Recomendado.",
    date: "2025-04-18",
    helpful: 21,
    verified: true,
  },
  {
    id: "rev_006",
    productId: "p_alim_003",
    userName: "Yanet S.",
    userAvatar: "👩🏽",
    userLocation: "Miami, FL",
    rating: 5,
    title: "Galón completo, no como en otras tiendas",
    content:
      "Por fin un galón completo y de buena marca. En otras agencias mandan medio galón disfrazado.",
    date: "2025-04-22",
    helpful: 28,
    verified: true,
  },

  // ===== LECHE EN POLVO (p_alim_004) =====
  {
    id: "rev_007",
    productId: "p_alim_004",
    userName: "Osvaldo R.",
    userAvatar: "👨🏽",
    userLocation: "Newark, NJ",
    rating: 5,
    title: "La leche del Nido",
    content:
      "Esta es la marca que toda la vida hemos consumido. Llegó perfectamente sellada y vencimiento bien lejos.",
    date: "2025-04-19",
    helpful: 19,
    verified: true,
  },
  {
    id: "rev_008",
    productId: "p_alim_004",
    userName: "Lourdes D.",
    userAvatar: "👩🏽",
    userLocation: "Madrid, España",
    rating: 5,
    title: "Le hace mucha falta a mis padres",
    content:
      "Mis padres son mayores y necesitan leche todos los días. Gracias a Yumury siempre tienen.",
    date: "2025-04-12",
    helpful: 41,
    verified: true,
  },

  // ===== ECOFLOW (p_elec_001) =====
  {
    id: "rev_009",
    productId: "p_elec_001",
    userName: "Daniel M.",
    userAvatar: "👨🏽",
    userLocation: "Miami, FL",
    rating: 5,
    title: "Cambió la vida de mis padres",
    content:
      "Inversión de 1099 dólares pero vale cada centavo. Mis padres ya no sufren los apagones largos en Cárdenas. Pueden ver TV, cargar el celular y tener un ventilador prendido toda la noche.",
    date: "2025-03-28",
    helpful: 89,
    verified: true,
    photos: ["https://images.unsplash.com/photo-1620677368158-32b078c1c000?w=600"],
  },
  {
    id: "rev_010",
    productId: "p_elec_001",
    userName: "Liset H.",
    userAvatar: "👩🏽",
    userLocation: "Tampa, FL",
    rating: 5,
    title: "Funciona como dice",
    content:
      "Llegó en 9 días. Mi hermana lo conectó al refrigerador durante un apagón de 8 horas y aguantó perfecto.",
    date: "2025-03-15",
    helpful: 56,
    verified: true,
  },

  // ===== COMBO FAMILIAR BÁSICO (combo_003) =====
  {
    id: "rev_011",
    productId: "combo_003",
    userName: "Alejandro V.",
    userAvatar: "👨🏽",
    userLocation: "Hialeah, FL",
    rating: 5,
    title: "Lo pido cada mes religiosamente",
    content:
      "Es el combo perfecto. No tengo que pensar qué mandar. Llega completo y a buen precio.",
    date: "2025-04-23",
    helpful: 67,
    verified: true,
  },
  {
    id: "rev_012",
    productId: "combo_003",
    userName: "Yuvisay L.",
    userAvatar: "👩🏽",
    userLocation: "Orlando, FL",
    rating: 5,
    title: "Mi mamá quedó feliz",
    content:
      "Le mandé este combo a mi mamá y le duró casi 2 semanas. Buen pollo, buen arroz, buen café. Recomendado.",
    date: "2025-04-10",
    helpful: 45,
    verified: true,
  },

  // ===== COMBO APAGÓN READY (combo_001) =====
  {
    id: "rev_013",
    productId: "combo_001",
    userName: "Maritza A.",
    userAvatar: "👩🏽",
    userLocation: "Miami, FL",
    rating: 5,
    title: "La mejor inversión que he hecho",
    content:
      "En Matanzas los apagones son terribles. Mandé este combo a mi madre y mi hermana y ahora pueden dormir con ventilador y luz. Cambió todo.",
    date: "2025-04-05",
    helpful: 73,
    verified: true,
    photos: ["https://images.unsplash.com/photo-1620677368158-32b078c1c000?w=600"],
  },

  // ===== MOTO MISHOZUKI (p_veh_001) =====
  {
    id: "rev_014",
    productId: "p_veh_001",
    userName: "Yander B.",
    userAvatar: "👨🏽",
    userLocation: "Las Vegas, NV",
    rating: 5,
    title: "Mi sobrino feliz",
    content:
      "Le mandé la moto a mi sobrino para que no tenga que tomar guagua. Llegó en 5 semanas como dijeron. Funciona perfecto.",
    date: "2025-03-20",
    helpful: 34,
    verified: true,
    photos: ["https://images.unsplash.com/photo-1558981852-426c6c22a060?w=600"],
  },
  {
    id: "rev_015",
    productId: "p_veh_001",
    userName: "Dayana O.",
    userAvatar: "👩🏽",
    userLocation: "Atlanta, GA",
    rating: 4,
    title: "Buena moto, buen servicio",
    content:
      "La moto llegó en buen estado y mi familia me mandó video probándola. Una rueda llegó con poco aire pero la inflaron y todo bien.",
    date: "2025-02-28",
    helpful: 22,
    verified: true,
  },

  // ===== REFRIGERADOR MABE (p_elec_003) =====
  {
    id: "rev_016",
    productId: "p_elec_003",
    userName: "Yoel G.",
    userAvatar: "👨🏽",
    userLocation: "Louisville, KY",
    rating: 5,
    title: "Mis abuelos felices",
    content:
      "Le compré el refrigerador Mabe a mis abuelos. Llegó en 3 semanas. El equipo lo subió hasta el segundo piso. Excelente.",
    date: "2025-03-10",
    helpful: 48,
    verified: true,
  },

  // ===== COMBO CUMPLEAÑOS (combo_007) =====
  {
    id: "rev_017",
    productId: "combo_007",
    userName: "Noslen J.",
    userAvatar: "👩🏽",
    userLocation: "Miami, FL",
    rating: 5,
    title: "Perfecto para sorpresa de cumpleaños",
    content:
      "Le hice una sorpresa a mi sobrina por su cumpleaños 15. La torta llegó perfecta, los globos, todo. Ella lloró cuando lo recibió.",
    date: "2025-04-08",
    helpful: 89,
    verified: true,
    photos: ["https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600"],
  },

  // ===== COMBO DIABÉTICA (combo_006) =====
  {
    id: "rev_018",
    productId: "combo_006",
    userName: "Idania R.",
    userAvatar: "👩🏽",
    userLocation: "Madrid, España",
    rating: 5,
    title: "Perfecto para mi mamá",
    content:
      "Mi mamá es diabética y este combo le ha cambiado la alimentación. Productos que no se consiguen en Cuba. Gracias!",
    date: "2025-03-25",
    helpful: 56,
    verified: true,
  },

  // ===== Más reviews para variedad =====
  {
    id: "rev_019",
    productId: "p_alim_009",
    userName: "Yusniel R.",
    userAvatar: "👨🏽",
    userLocation: "Miami, FL",
    rating: 5,
    title: "Picadillo perfecto",
    content:
      "Carne molida 80/20, justo lo que pedí. Mi mamá hizo un picadillo a la habanera que cuentan que estaba para chuparse los dedos.",
    date: "2025-04-21",
    helpful: 17,
    verified: true,
  },
  {
    id: "rev_020",
    productId: "p_alim_011",
    userName: "Mariela G.",
    userAvatar: "👩🏽",
    userLocation: "Tampa, FL",
    rating: 5,
    title: "Masa de cerdo de calidad",
    content:
      "La masa llegó cortada en trozos perfectos. Mi familia frió y quedó crocante por fuera y jugosa adentro. Volveré a pedir.",
    date: "2025-04-17",
    helpful: 14,
    verified: true,
  },
  {
    id: "rev_021",
    productId: "p_alim_041",
    userName: "Roberto P.",
    userAvatar: "👨🏽",
    userLocation: "Madrid, España",
    rating: 5,
    title: "Mejor que otras agencias",
    content:
      "El café La Llave me llegó sellado al vacío y bien fresco. La diferencia con otras agencias es notable. Recomendado.",
    date: "2025-04-09",
    helpful: 21,
    verified: true,
  },
  {
    id: "rev_022",
    productId: "p_alim_041",
    userName: "Belinda G.",
    userAvatar: "👩🏽",
    userLocation: "Los Angeles, CA",
    rating: 5,
    title: "Imprescindible",
    content:
      "Cada mes le mando café a mi madre. Es lo único que extraña aunque le mando comida. Sabor inconfundible.",
    date: "2025-04-02",
    helpful: 18,
    verified: true,
  },
  {
    id: "rev_023",
    productId: "p_alim_069",
    userName: "Yanet S.",
    userAvatar: "👩🏽",
    userLocation: "Miami, FL",
    rating: 5,
    title: "Dove para mi familia",
    content:
      "El paquete de jabones Dove le hace una falta enorme a mi familia. En Cuba esto no se consigue. Llegó intacto.",
    date: "2025-04-19",
    helpful: 15,
    verified: true,
  },
  {
    id: "rev_024",
    productId: "p_alim_069",
    userName: "Idania R.",
    userAvatar: "👩🏽",
    userLocation: "Madrid, España",
    rating: 4,
    title: "Bien empacados",
    content:
      "Buen producto, llegó con un día de retraso pero todo bien. Los jabones intactos, sin daños.",
    date: "2025-03-30",
    helpful: 9,
    verified: true,
  },
  {
    id: "rev_025",
    productId: "p_alim_005",
    userName: "Yoandri P.",
    userAvatar: "👨🏽",
    userLocation: "Newark, NJ",
    rating: 5,
    title: "Pampers de los buenos",
    content:
      "Mi sobrina recién nacida es alérgica a marcas baratas. Pampers Baby Dry son los únicos que le funcionan. Le mando cada mes.",
    date: "2025-04-14",
    helpful: 32,
    verified: true,
  },
  {
    id: "rev_026",
    productId: "p_alim_073",
    userName: "Lourdes D.",
    userAvatar: "👩🏽",
    userLocation: "Madrid, España",
    rating: 5,
    title: "El de toda la vida",
    content:
      "Head & Shoulders es la marca que mi mamá ha usado siempre. La botella grande dura 4 meses. Llegó bien sellada.",
    date: "2025-04-11",
    helpful: 19,
    verified: true,
  },
  {
    id: "rev_027",
    productId: "p_alim_081",
    userName: "Carlos F.",
    userAvatar: "👨🏽",
    userLocation: "Houston, TX",
    rating: 5,
    title: "Tide funciona",
    content:
      "Detergente de calidad. Mi madre dice que la ropa queda más blanca con Tide que con otras marcas. Recomendado.",
    date: "2025-04-06",
    helpful: 11,
    verified: true,
  },
  {
    id: "rev_028",
    productId: "p_alim_046",
    userName: "Yamila C.",
    userAvatar: "👩🏽",
    userLocation: "Hialeah, FL",
    rating: 5,
    title: "La caja entera intacta",
    content:
      "12 latas de leche condensada La Lechera y todas llegaron sin abolladuras. Mi familia hace flanes y postres con esto.",
    date: "2025-04-03",
    helpful: 24,
    verified: true,
  },
  {
    id: "rev_029",
    productId: "p_alim_055",
    userName: "Daniel M.",
    userAvatar: "👨🏽",
    userLocation: "Miami, FL",
    rating: 5,
    title: "Atún que dura meses",
    content:
      "Caja de 10 latas de atún en aceite. Mi madre las usa para almuerzos rápidos cuando no hay nada más. Excelente para tener guardado.",
    date: "2025-03-31",
    helpful: 13,
    verified: true,
  },
  {
    id: "rev_030",
    productId: "p_alim_058",
    userName: "Liset H.",
    userAvatar: "👩🏽",
    userLocation: "Tampa, FL",
    rating: 5,
    title: "Jamoneta sabrosa",
    content:
      "La jamoneta llegó perfecta, sabor tradicional. Mi tía hace bocaditos para los nietos.",
    date: "2025-03-22",
    helpful: 17,
    verified: true,
  },

  // ===== COMBOS extra =====
  {
    id: "rev_031",
    productId: "combo_002",
    userName: "Alejandro V.",
    userAvatar: "👨🏽",
    userLocation: "Hialeah, FL",
    rating: 5,
    title: "Para temporada de ciclones",
    content:
      "Lo mandé en mayo antes de la temporada de ciclones. Mi familia tuvo todo lo necesario cuando vino la tormenta.",
    date: "2025-04-25",
    helpful: 29,
    verified: true,
  },
  {
    id: "rev_032",
    productId: "combo_004",
    userName: "Yuvisay L.",
    userAvatar: "👩🏽",
    userLocation: "Orlando, FL",
    rating: 5,
    title: "El premium vale la pena",
    content:
      "Pagué un poquito más por el premium y la diferencia es enorme. Mariscos, cerdo, queso amarillo. Mi familia comió como reyes 3 semanas.",
    date: "2025-04-18",
    helpful: 38,
    verified: true,
  },
  {
    id: "rev_033",
    productId: "combo_005",
    userName: "Maritza A.",
    userAvatar: "👩🏽",
    userLocation: "Miami, FL",
    rating: 5,
    title: "Mes completo resuelto",
    content:
      "Una sola compra al mes y mi familia entera (4 personas) tiene todo. Antes mandaba 3-4 paquetes pequeños y salía más caro.",
    date: "2025-04-12",
    helpful: 51,
    verified: true,
  },
  {
    id: "rev_034",
    productId: "combo_008",
    userName: "Belinda G.",
    userAvatar: "👩🏽",
    userLocation: "Los Angeles, CA",
    rating: 5,
    title: "Aseo personal completo",
    content:
      "Las marcas que mi familia no consigue: Dove, Pantene, Charmin, Always. Todo en un solo combo. Una ayuda enorme.",
    date: "2025-04-07",
    helpful: 33,
    verified: true,
  },
  {
    id: "rev_035",
    productId: "combo_010",
    userName: "Yoandri P.",
    userAvatar: "👨🏽",
    userLocation: "Newark, NJ",
    rating: 5,
    title: "Para mi sobrino recién nacido",
    content:
      "Pampers, toallitas, talco, todo Johnson's. Mi cuñada agradecidísima. Lo pido mensualmente.",
    date: "2025-04-04",
    helpful: 27,
    verified: true,
  },
  {
    id: "rev_036",
    productId: "combo_014",
    userName: "Lourdes D.",
    userAvatar: "👩🏽",
    userLocation: "Madrid, España",
    rating: 5,
    title: "Independencia energética total",
    content:
      "Panel solar 400W + EcoFlow. Mi familia ya no depende de la corriente. La inversión más inteligente que he hecho.",
    date: "2025-03-18",
    helpful: 42,
    verified: true,
    photos: ["https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600"],
  },

  // ===== ELECTROS varios =====
  {
    id: "rev_037",
    productId: "p_elec_022",
    userName: "Yusniel R.",
    userAvatar: "👨🏽",
    userLocation: "Miami, FL",
    rating: 5,
    title: "EcoFlow River — la versión chica",
    content:
      "Para apagones cortos es perfecto. No necesitas el Delta grande si solo quieres cargar celulares y luces. 349 dólares bien invertidos.",
    date: "2025-04-16",
    helpful: 22,
    verified: true,
  },
  {
    id: "rev_038",
    productId: "p_elec_028",
    userName: "Mariela G.",
    userAvatar: "👩🏽",
    userLocation: "Tampa, FL",
    rating: 5,
    title: "Lámpara LED solar perfecta",
    content:
      "Mi mamá la deja al sol todo el día y por la noche cuando hay apagón le da luz a toda la sala. 12 horas como dicen.",
    date: "2025-04-13",
    helpful: 28,
    verified: true,
  },
  {
    id: "rev_039",
    productId: "p_elec_019",
    userName: "Roberto P.",
    userAvatar: "👨🏽",
    userLocation: "Madrid, España",
    rating: 5,
    title: "Ventilador USB salvavidas",
    content:
      "Mis abuelos lo usan en los apagones de noche. Aguanta 8 horas sin problema. Pequeño pero potente.",
    date: "2025-04-01",
    helpful: 35,
    verified: true,
  },
  {
    id: "rev_040",
    productId: "p_elec_011",
    userName: "Yamila C.",
    userAvatar: "👩🏽",
    userLocation: "Hialeah, FL",
    rating: 5,
    title: "Microondas Panasonic",
    content:
      "Mi madre estaba esperando un microondas hace años. Llegó en 9 días y funciona perfecto. Calienta parejo.",
    date: "2025-03-26",
    helpful: 19,
    verified: true,
  },
  {
    id: "rev_041",
    productId: "p_elec_012",
    userName: "Carlos F.",
    userAvatar: "👨🏽",
    userLocation: "Houston, TX",
    rating: 5,
    title: "Instant Pot cambia todo",
    content:
      "La olla Instant Pot le ahorra horas de cocina a mi madre. Hace frijoles en 20 minutos. Vale cada dólar.",
    date: "2025-03-19",
    helpful: 41,
    verified: true,
  },
  {
    id: "rev_042",
    productId: "p_elec_029",
    userName: "Yanet S.",
    userAvatar: "👩🏽",
    userLocation: "Miami, FL",
    rating: 5,
    title: "Oster de toda la vida",
    content:
      "La Oster que toda madre cubana conoce. Llegó en su caja sellada. Mi abuela ya lleva 40 años usando una y siempre vuelve a esta marca.",
    date: "2025-03-12",
    helpful: 26,
    verified: true,
  },
  {
    id: "rev_043",
    productId: "p_elec_018",
    userName: "Osvaldo R.",
    userAvatar: "👨🏽",
    userLocation: "Newark, NJ",
    rating: 4,
    title: "Buen ventilador",
    content:
      'El ventilador de pie 18" cumple bien. Tres velocidades, oscilación. Lo único, el ruido en velocidad alta es notable.',
    date: "2025-03-05",
    helpful: 11,
    verified: true,
  },

  // ===== VEHICULOS extra =====
  {
    id: "rev_044",
    productId: "p_veh_007",
    userName: "Daniel M.",
    userAvatar: "👨🏽",
    userLocation: "Miami, FL",
    rating: 5,
    title: "Honda 125, la confiable",
    content:
      "Llegó en 6 semanas via marítima. Mi hermano la usa diario para ir al trabajo en Cárdenas. Repuestos accesibles. La mejor decisión.",
    date: "2025-02-25",
    helpful: 47,
    verified: true,
  },
  {
    id: "rev_045",
    productId: "p_veh_002",
    userName: "Liset H.",
    userAvatar: "👩🏽",
    userLocation: "Tampa, FL",
    rating: 4,
    title: "Económica pero cumple",
    content:
      "La Avispa 350W es para distancias cortas. Mi tío la usa solo dentro de Matanzas. 40 km de autonomía es justo. Para más, hay que mejor inversión.",
    date: "2025-02-20",
    helpful: 14,
    verified: true,
  },
  {
    id: "rev_046",
    productId: "p_veh_011",
    userName: "Alejandro V.",
    userAvatar: "👨🏽",
    userLocation: "Hialeah, FL",
    rating: 4,
    title: "Bici plegable útil",
    content:
      "Para apartamento es perfecta porque se pliega. Mi prima la guarda dentro. Para distancias cortas funciona bien.",
    date: "2025-03-08",
    helpful: 9,
    verified: true,
  },

  // ===== Más reviews variados =====
  {
    id: "rev_047",
    productId: "p_alim_021",
    userName: "Yuvisay L.",
    userAvatar: "👩🏽",
    userLocation: "Orlando, FL",
    rating: 5,
    title: "Frijoles de buena calidad",
    content:
      "Granos uniformes, sin piedras ni partidos. Mi madre dice que cocinan parejo y quedan suaves.",
    date: "2025-04-18",
    helpful: 16,
    verified: true,
  },
  {
    id: "rev_048",
    productId: "combo_009",
    userName: "Maritza A.",
    userAvatar: "👩🏽",
    userLocation: "Miami, FL",
    rating: 4,
    title: "Combo limpieza completo",
    content:
      "Detergente Tide, Clorox, Dawn... todo. El precio es bueno. Lo único, la cubeta del trapeador no estaba incluida en mi combo (creo que es opcional).",
    date: "2025-04-15",
    helpful: 22,
    verified: true,
  },
  {
    id: "rev_049",
    productId: "combo_011",
    userName: "Yander B.",
    userAvatar: "👨🏽",
    userLocation: "Las Vegas, NV",
    rating: 3,
    title: "Cumple, pero esperaba más",
    content:
      "El combo cocina esencial está bien pero por 75 dólares pensé que traía más cosas. La calidad de los productos sí es buena.",
    date: "2025-04-09",
    helpful: 7,
    verified: true,
  },
  {
    id: "rev_050",
    productId: "p_alim_001",
    userName: "Noslen J.",
    userAvatar: "👩🏽",
    userLocation: "Miami, FL",
    rating: 4,
    title: "Buen arroz, tracking impreciso",
    content:
      "El arroz llegó bien y la calidad es buena. Lo único, el tracking se quedó parado un día en aduana sin actualizaciones, me preocupé. Después todo bien.",
    date: "2025-04-04",
    helpful: 13,
    verified: true,
  },
];

export function getProductReviews(productId: string): Review[] {
  return mockReviews.filter((r) => r.productId === productId);
}

export function getProductRatingStats(productId: string) {
  const reviews = getProductReviews(productId);
  if (reviews.length === 0) return null;
  const sum = reviews.reduce((acc, r) => acc + r.rating, 0);
  const avg = sum / reviews.length;
  const breakdown = [5, 4, 3, 2, 1].map((stars) => ({
    stars,
    count: reviews.filter((r) => r.rating === stars).length,
  }));
  return { average: avg, total: reviews.length, breakdown };
}
