import type { TrackingEvent } from "@/types";

const PHOTOS = {
  empacando: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600",
  almacenMatanzas: "https://images.unsplash.com/photo-1605367898060-aff44dc2ed25?w=600",
  entregaMercedes: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600",
  entregaPedro: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600",
  entregaCamila: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600",
  motoEntregada: "https://images.unsplash.com/photo-1558981852-426c6c22a060?w=600",
  enReparto: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=600",
} as const;

// ============================================================
// ORDER 001 — SHIPPED (en tránsito) — current: evt 4
// ============================================================
export const trackingEvents001: TrackingEvent[] = [
  {
    id: "evt_001_1",
    status: "pending",
    title: "Pedido recibido",
    description: "Hemos recibido tu pedido y estamos validando el pago.",
    location: "Miami, FL",
    timestamp: "2025-05-03T10:32:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_001_2",
    status: "confirmed",
    title: "Pedido confirmado",
    description: "Pago procesado correctamente. Empezamos a preparar tu pedido.",
    location: "Miami, FL",
    timestamp: "2025-05-03T10:35:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_001_3",
    status: "preparing",
    title: "Preparando en almacén Miami",
    description: "Tu pedido está siendo empacado con cuidado por nuestro equipo.",
    location: "Miami, FL",
    timestamp: "2025-05-03T14:15:00Z",
    photo: PHOTOS.empacando,
    photoCaption: "Tu pedido empacado y listo para enviar",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_001_4",
    status: "shipped",
    title: "En tránsito hacia Cuba",
    description: "Vuelo internacional MIA → HAV. Tu pedido viaja con prioridad.",
    location: "Vuelo internacional",
    timestamp: "2025-05-03T18:00:00Z",
    isCompleted: true,
    isCurrent: true,
  },
  {
    id: "evt_001_5",
    status: "in-customs",
    title: "En aduana cubana",
    description: "Tu pedido está en proceso de despacho aduanal.",
    location: "La Habana, Cuba",
    timestamp: "2025-05-04T11:00:00Z",
    isCompleted: false,
    isCurrent: false,
    estimated: true,
  },
  {
    id: "evt_001_6",
    status: "in-warehouse",
    title: "Llegada al almacén Matanzas",
    description: "Tu pedido llegó a nuestro centro de distribución en Matanzas.",
    location: "Matanzas, Cuba",
    timestamp: "2025-05-05T09:00:00Z",
    isCompleted: false,
    isCurrent: false,
    estimated: true,
  },
  {
    id: "evt_001_7",
    status: "out-for-delivery",
    title: "En reparto hacia Cárdenas",
    description: "El repartidor está en camino a la dirección de tu familiar.",
    location: "Cárdenas, Matanzas",
    timestamp: "2025-05-05T14:00:00Z",
    isCompleted: false,
    isCurrent: false,
    estimated: true,
  },
  {
    id: "evt_001_8",
    status: "delivered",
    title: "Entregado a Mamá Mercedes",
    description: "Tu pedido fue entregado correctamente.",
    location: "Cárdenas, Matanzas",
    timestamp: "2025-05-05T16:30:00Z",
    isCompleted: false,
    isCurrent: false,
    estimated: true,
  },
];

// ============================================================
// ORDER 002 — DELIVERED — todos completados, foto al final
// ============================================================
export const trackingEvents002: TrackingEvent[] = [
  {
    id: "evt_002_1",
    status: "pending",
    title: "Pedido recibido",
    description: "Hemos recibido tu pedido.",
    location: "Miami, FL",
    timestamp: "2025-04-15T14:22:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_002_2",
    status: "confirmed",
    title: "Pedido confirmado",
    description: "Pago procesado correctamente.",
    location: "Miami, FL",
    timestamp: "2025-04-15T14:25:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_002_3",
    status: "preparing",
    title: "Preparando en almacén Miami",
    description: "Pedido empacado.",
    location: "Miami, FL",
    timestamp: "2025-04-15T17:00:00Z",
    photo: PHOTOS.empacando,
    photoCaption: "Empacado en Miami",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_002_4",
    status: "shipped",
    title: "En tránsito hacia Cuba",
    description: "Vuelo MIA → HAV.",
    location: "Vuelo internacional",
    timestamp: "2025-04-16T08:00:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_002_5",
    status: "in-customs",
    title: "En aduana cubana",
    description: "Despacho aduanal completado.",
    location: "La Habana, Cuba",
    timestamp: "2025-04-17T13:00:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_002_6",
    status: "in-warehouse",
    title: "Llegada al almacén Matanzas",
    description: "Recibido en centro de distribución.",
    location: "Matanzas, Cuba",
    timestamp: "2025-04-19T10:00:00Z",
    photo: PHOTOS.almacenMatanzas,
    photoCaption: "En el almacén de Matanzas",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_002_7",
    status: "out-for-delivery",
    title: "En reparto hacia Matanzas centro",
    description: "Repartidor en camino.",
    location: "Matanzas, Cuba",
    timestamp: "2025-04-21T09:30:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_002_8",
    status: "delivered",
    title: "Entregado a Tío Pedro",
    description: "Pedido entregado con éxito. ¡Gracias por confiar en Yumury!",
    location: "Matanzas, Cuba",
    timestamp: "2025-04-21T15:45:00Z",
    photo: PHOTOS.entregaPedro,
    photoCaption: "Tío Pedro recibió su pedido",
    isCompleted: true,
    isCurrent: false,
  },
];

// ============================================================
// ORDER 003 — OUT FOR DELIVERY — current: evt 7
// ============================================================
export const trackingEvents003: TrackingEvent[] = [
  {
    id: "evt_003_1",
    status: "pending",
    title: "Pedido recibido",
    description: "Pago en validación.",
    location: "Miami, FL",
    timestamp: "2025-04-28T09:15:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_003_2",
    status: "confirmed",
    title: "Pedido confirmado",
    description: "Pago procesado.",
    location: "Miami, FL",
    timestamp: "2025-04-28T09:20:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_003_3",
    status: "preparing",
    title: "Preparando en almacén Miami",
    description: "Combo Apagón Ready empacado con cuidado.",
    location: "Miami, FL",
    timestamp: "2025-04-28T15:00:00Z",
    photo: PHOTOS.empacando,
    photoCaption: "Combo Apagón Ready empacado",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_003_4",
    status: "shipped",
    title: "En tránsito hacia Cuba",
    description: "Vuelo MIA → HAV.",
    location: "Vuelo internacional",
    timestamp: "2025-04-29T07:30:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_003_5",
    status: "in-customs",
    title: "En aduana cubana",
    description: "Despacho aduanal completado.",
    location: "La Habana, Cuba",
    timestamp: "2025-05-01T12:00:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_003_6",
    status: "in-warehouse",
    title: "Llegada al almacén Matanzas",
    description: "Recibido en centro de distribución.",
    location: "Matanzas, Cuba",
    timestamp: "2025-05-04T08:30:00Z",
    photo: PHOTOS.almacenMatanzas,
    photoCaption: "En el almacén de Matanzas",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_003_7",
    status: "out-for-delivery",
    title: "En reparto hacia Cárdenas",
    description: "El repartidor está en camino con tu pedido.",
    location: "Cárdenas, Matanzas",
    timestamp: "2025-05-05T08:00:00Z",
    photo: PHOTOS.enReparto,
    photoCaption: "Repartidor en ruta",
    isCompleted: true,
    isCurrent: true,
  },
  {
    id: "evt_003_8",
    status: "delivered",
    title: "Entregado a Mamá Mercedes",
    description: "Pendiente de entrega final.",
    location: "Cárdenas, Matanzas",
    timestamp: "2025-05-05T13:00:00Z",
    isCompleted: false,
    isCurrent: false,
    estimated: true,
  },
];

// ============================================================
// ORDER 004 — IN CUSTOMS — current: evt 5
// ============================================================
export const trackingEvents004: TrackingEvent[] = [
  {
    id: "evt_004_1",
    status: "pending",
    title: "Pedido recibido",
    description: "Pago validado.",
    location: "Miami, FL",
    timestamp: "2025-04-30T11:00:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_004_2",
    status: "confirmed",
    title: "Pedido confirmado",
    description: "Pago procesado.",
    location: "Miami, FL",
    timestamp: "2025-04-30T11:10:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_004_3",
    status: "preparing",
    title: "Preparando en almacén Miami",
    description: "Microondas empacado con embalaje reforzado.",
    location: "Miami, FL",
    timestamp: "2025-04-30T16:00:00Z",
    photo: PHOTOS.empacando,
    photoCaption: "Microondas empacado",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_004_4",
    status: "shipped",
    title: "En tránsito hacia Cuba",
    description: "Vuelo MIA → HAV.",
    location: "Vuelo internacional",
    timestamp: "2025-05-01T08:00:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_004_5",
    status: "in-customs",
    title: "En aduana cubana",
    description: "Tu pedido está en proceso de despacho aduanal. Esto puede tomar 1-2 días.",
    location: "La Habana, Cuba",
    timestamp: "2025-05-02T10:00:00Z",
    isCompleted: true,
    isCurrent: true,
  },
  {
    id: "evt_004_6",
    status: "in-warehouse",
    title: "Llegada al almacén Matanzas",
    description: "Pendiente de llegada al centro de distribución.",
    location: "Matanzas, Cuba",
    timestamp: "2025-05-06T09:00:00Z",
    isCompleted: false,
    isCurrent: false,
    estimated: true,
  },
  {
    id: "evt_004_7",
    status: "out-for-delivery",
    title: "En reparto hacia Varadero",
    description: "Pendiente de salida a reparto.",
    location: "Varadero, Matanzas",
    timestamp: "2025-05-07T10:00:00Z",
    isCompleted: false,
    isCurrent: false,
    estimated: true,
  },
  {
    id: "evt_004_8",
    status: "delivered",
    title: "Entregado a Sobrina Camila",
    description: "Pendiente de entrega final.",
    location: "Varadero, Matanzas",
    timestamp: "2025-05-08T14:00:00Z",
    isCompleted: false,
    isCurrent: false,
    estimated: true,
  },
];

// ============================================================
// ORDER 005 — PREPARING — current: evt 3
// ============================================================
export const trackingEvents005: TrackingEvent[] = [
  {
    id: "evt_005_1",
    status: "pending",
    title: "Pedido recibido",
    description: "Hemos recibido tu pedido.",
    location: "Miami, FL",
    timestamp: "2025-05-04T16:45:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_005_2",
    status: "confirmed",
    title: "Pedido confirmado",
    description: "Pago procesado correctamente.",
    location: "Miami, FL",
    timestamp: "2025-05-04T16:50:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_005_3",
    status: "preparing",
    title: "Preparando Combo Mamá Diabética",
    description: "Estamos seleccionando los productos especiales para diabéticos con cuidado.",
    location: "Miami, FL",
    timestamp: "2025-05-05T08:00:00Z",
    isCompleted: true,
    isCurrent: true,
  },
  {
    id: "evt_005_4",
    status: "shipped",
    title: "En tránsito hacia Cuba",
    description: "Pendiente de envío.",
    location: "Vuelo internacional",
    timestamp: "2025-05-06T18:00:00Z",
    isCompleted: false,
    isCurrent: false,
    estimated: true,
  },
  {
    id: "evt_005_5",
    status: "in-customs",
    title: "En aduana cubana",
    description: "Pendiente.",
    location: "La Habana, Cuba",
    timestamp: "2025-05-07T11:00:00Z",
    isCompleted: false,
    isCurrent: false,
    estimated: true,
  },
  {
    id: "evt_005_6",
    status: "in-warehouse",
    title: "Llegada al almacén Matanzas",
    description: "Pendiente.",
    location: "Matanzas, Cuba",
    timestamp: "2025-05-10T09:00:00Z",
    isCompleted: false,
    isCurrent: false,
    estimated: true,
  },
  {
    id: "evt_005_7",
    status: "out-for-delivery",
    title: "En reparto hacia Matanzas",
    description: "Pendiente.",
    location: "Matanzas, Cuba",
    timestamp: "2025-05-12T10:00:00Z",
    isCompleted: false,
    isCurrent: false,
    estimated: true,
  },
  {
    id: "evt_005_8",
    status: "delivered",
    title: "Entregado a Tío Pedro",
    description: "Pendiente de entrega.",
    location: "Matanzas, Cuba",
    timestamp: "2025-05-13T14:00:00Z",
    isCompleted: false,
    isCurrent: false,
    estimated: true,
  },
];

// ============================================================
// ORDER 006 — DELIVERED — todos completados (sin foto final, variante)
// ============================================================
export const trackingEvents006: TrackingEvent[] = [
  {
    id: "evt_006_1",
    status: "pending",
    title: "Pedido recibido",
    description: "Pago en validación.",
    location: "Miami, FL",
    timestamp: "2025-04-10T08:30:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_006_2",
    status: "confirmed",
    title: "Pedido confirmado",
    description: "Pago procesado.",
    location: "Miami, FL",
    timestamp: "2025-04-10T08:35:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_006_3",
    status: "preparing",
    title: "Preparando Combo Cumpleaños",
    description: "Empacando torta y decoraciones con cuidado especial.",
    location: "Miami, FL",
    timestamp: "2025-04-10T13:00:00Z",
    photo: PHOTOS.empacando,
    photoCaption: "Combo Cumpleaños listo",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_006_4",
    status: "shipped",
    title: "En tránsito hacia Cuba",
    description: "Vuelo MIA → HAV.",
    location: "Vuelo internacional",
    timestamp: "2025-04-11T07:30:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_006_5",
    status: "in-customs",
    title: "En aduana cubana",
    description: "Despacho aduanal completado.",
    location: "La Habana, Cuba",
    timestamp: "2025-04-13T13:00:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_006_6",
    status: "in-warehouse",
    title: "Llegada al almacén Matanzas",
    description: "Recibido en almacén.",
    location: "Matanzas, Cuba",
    timestamp: "2025-04-15T10:00:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_006_7",
    status: "out-for-delivery",
    title: "En reparto hacia Varadero",
    description: "Repartidor en ruta.",
    location: "Varadero, Matanzas",
    timestamp: "2025-04-17T09:00:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_006_8",
    status: "delivered",
    title: "Entregado a Sobrina Camila",
    description: "Pedido entregado con éxito. ¡Felicidades sobrina!",
    location: "Varadero, Matanzas",
    timestamp: "2025-04-17T14:30:00Z",
    isCompleted: true,
    isCurrent: false,
  },
];

// ============================================================
// ORDER 007 — PENDING — current: evt 1
// ============================================================
export const trackingEvents007: TrackingEvent[] = [
  {
    id: "evt_007_1",
    status: "pending",
    title: "Pedido recibido",
    description: "Hemos recibido tu pedido y estamos validando el pago.",
    location: "Miami, FL",
    timestamp: "2025-05-05T08:00:00Z",
    isCompleted: false,
    isCurrent: true,
  },
  {
    id: "evt_007_2",
    status: "confirmed",
    title: "Pedido confirmado",
    description: "Pendiente de confirmación.",
    location: "Miami, FL",
    timestamp: "2025-05-05T08:30:00Z",
    isCompleted: false,
    isCurrent: false,
    estimated: true,
  },
  {
    id: "evt_007_3",
    status: "preparing",
    title: "Preparando en almacén Miami",
    description: "Pendiente.",
    location: "Miami, FL",
    timestamp: "2025-05-05T14:00:00Z",
    isCompleted: false,
    isCurrent: false,
    estimated: true,
  },
  {
    id: "evt_007_4",
    status: "shipped",
    title: "En tránsito hacia Cuba",
    description: "Pendiente.",
    location: "Vuelo internacional",
    timestamp: "2025-05-06T08:00:00Z",
    isCompleted: false,
    isCurrent: false,
    estimated: true,
  },
  {
    id: "evt_007_5",
    status: "in-customs",
    title: "En aduana cubana",
    description: "Pendiente.",
    location: "La Habana, Cuba",
    timestamp: "2025-05-07T11:00:00Z",
    isCompleted: false,
    isCurrent: false,
    estimated: true,
  },
  {
    id: "evt_007_6",
    status: "in-warehouse",
    title: "Llegada al almacén Matanzas",
    description: "Pendiente.",
    location: "Matanzas, Cuba",
    timestamp: "2025-05-10T09:00:00Z",
    isCompleted: false,
    isCurrent: false,
    estimated: true,
  },
  {
    id: "evt_007_7",
    status: "out-for-delivery",
    title: "En reparto hacia Cárdenas",
    description: "Pendiente.",
    location: "Cárdenas, Matanzas",
    timestamp: "2025-05-13T10:00:00Z",
    isCompleted: false,
    isCurrent: false,
    estimated: true,
  },
  {
    id: "evt_007_8",
    status: "delivered",
    title: "Entregado a Mamá Mercedes",
    description: "Pendiente.",
    location: "Cárdenas, Matanzas",
    timestamp: "2025-05-14T14:00:00Z",
    isCompleted: false,
    isCurrent: false,
    estimated: true,
  },
];

// ============================================================
// ORDER 008 — DELIVERED (envío marítimo de moto, ~4 semanas)
// ============================================================
export const trackingEvents008: TrackingEvent[] = [
  {
    id: "evt_008_1",
    status: "pending",
    title: "Pedido recibido",
    description: "Pago en validación.",
    location: "Miami, FL",
    timestamp: "2025-03-15T10:00:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_008_2",
    status: "confirmed",
    title: "Pedido confirmado",
    description: "Pago procesado correctamente.",
    location: "Miami, FL",
    timestamp: "2025-03-15T10:30:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_008_3",
    status: "preparing",
    title: "Preparando moto eléctrica para envío marítimo",
    description: "Moto inspeccionada y embalada en caja reforzada para envío marítimo.",
    location: "Miami, FL",
    timestamp: "2025-03-18T15:00:00Z",
    photo: PHOTOS.empacando,
    photoCaption: "Moto Mishozuki Pro embalada para envío marítimo",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_008_4",
    status: "shipped",
    title: "En tránsito marítimo hacia Cuba",
    description: "Carga en buque MIA → Mariel. Tiempo estimado: 2-3 semanas.",
    location: "Buque marítimo MIA → Mariel",
    timestamp: "2025-03-20T08:00:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_008_5",
    status: "in-customs",
    title: "En aduana cubana",
    description: "Despacho aduanal de envío marítimo completado.",
    location: "Puerto del Mariel, Cuba",
    timestamp: "2025-04-04T14:00:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_008_6",
    status: "in-warehouse",
    title: "Llegada al almacén Matanzas",
    description: "Moto recibida y revisada en almacén.",
    location: "Matanzas, Cuba",
    timestamp: "2025-04-08T11:00:00Z",
    photo: PHOTOS.almacenMatanzas,
    photoCaption: "Moto en el almacén de Matanzas",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_008_7",
    status: "out-for-delivery",
    title: "En reparto hacia Varadero",
    description: "Equipo en ruta para entrega y entrenamiento básico.",
    location: "Varadero, Matanzas",
    timestamp: "2025-04-12T09:00:00Z",
    isCompleted: true,
    isCurrent: false,
  },
  {
    id: "evt_008_8",
    status: "delivered",
    title: "Entregada a Sobrina Camila",
    description: "Moto entregada y probada con la familia. ¡Disfruten el regalo!",
    location: "Varadero, Matanzas",
    timestamp: "2025-04-12T15:30:00Z",
    photo: PHOTOS.motoEntregada,
    photoCaption: "Sobrina Camila con su nueva moto",
    isCompleted: true,
    isCurrent: false,
  },
];
